### ISSUE TITLE
Move the Clinical Service Graphql Resolver From Platform API to RDPC Clinical

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/argo-clinical#1016]
## Detailed Description
As step 2 to https://github.com/icgc-argo/argo-clinical/issues/1015, 
move the clinical service graphql resolver from platform API to RDPC clinical service. 
![Screenshot 2023-06-19 at 3 30 51 PM](https://github.com/icgc-argo/argo-clinical/assets/8744047/70fb8372-afb9-4d21-9612-17d74e04529b)

**Removing the platform Clinical resolver or delete it?**

**Comment by bhavikbhagat93** [comment]
This ticket was further broken down into individual resolvers ticket
