### ISSUE TITLE
Request to delete record from surgery data for APGI-AU program

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-clinical#1053]
We have a request from the data submitter for the `APGI-AU` program to delete a single record in their surgery file that was submitted by mistake:

![gloria_email_delete_surgery_record](https://github.com/icgc-argo/argo-clinical/assets/4992044/3f5a761f-10f1-45b7-a61a-a4462aa9058c)

The record that needs to be deleted from the `surgery` file includes the following (do not need to delete whole donor, just this single line from the surgery file):

donor_id `DO32831`	
program_id `APGI-AU`
submitter_donor_id `ICGC_0006`
submitter_specimen_id `8052609`	
submitter_treatment_id `TM0004`
surgery_type `Distal subtotal pancreatectomy`

The record that needs to be deleted from the `treatment` file:
donor_id `DO32831`
program_id `APGI-AU`
submitter_donor_id `ICGC_0006`
submitter_treatment_id `TM0004`
submitter_primary_diagnosis_id `DN0004`
treatment_type `Surgery`	
is_primary_treatment `Yes`
treatment_start_interval `1`	
treatment_duration `1`
treatment_intent `Curative`
treatment_setting `Not applicable`
response_to_treatment_criteria_method `Physician Assessed Response Criteria`
response_to_treatment `Physician assessed stable disease`
outcome_of_treatment `Treatment completed as prescribed`

**Comment by joneubank** [comment]
Data corrected and reindexed.

**Comment by hknahal** [comment]
Thanks @joneubank! I confirmed the record is removed from the `treatment` and `surgery` files when I check the Program Dashboard and clinical files.
