### ISSUE TITLE
Request to delete records from `treatment` table for PACA-CA program

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/argo-clinical#1080]
~~We have a request from PACA-CA program to delete all records from `treatment` table that was submitted, and she wants to re-upload an updated version.~~

**Comment by lindaxiang** [comment]
I have confirmed with the data submitter from PACA-CA, the treatment records with the following 13 `treatment_ids` should be deleted from our system. I have confirmed that all these treatment_ids don't have any additional reference data in the submission system. 
```
treatment_id_0048_1
treatment_id_0074_1
treatment_id_0099_1
treatment_id_0161_1
treatment_id_0297_1
treatment_id_0301_1
treatment_id_0354_1
treatment_id_0392_1
treatment_id_0465_1
treatment_id_0472_1
treatment_id_0549_1
treatment_id_0629_1
treatment_id_0649_1
```

**Comment by joneubank** [comment]
These treatments have been removed and the donor index re-synced. The submitted data pages reflect the changes. Please let me know if any further issues.
