### ISSUE TITLE
Exception Manifest - 1 - Function to generate exception records for donors

### ISSUE THREAD

**Issue by joneubank** [icgc-argo/argo-clinical#1142]
Create a function that will collect all exceptions related to a clinical data request and return the collection of those exception records sorted and ready to be converted into an exception manifest file.

### Types for ExceptionRecords
```ts
type ExceptionType = 'MissingEntity'| 'ProgramProperty' | 'EntityProperty'
type MissingEntityExceptionRecord = {
    exceptionType: 'MissingEntity';
    programId: string;
    donorId: string;
    submitterDonorId: string;
}
type ProgramPropertyExceptionRecord = {
    exceptionType: 'ProgramProperty';
    programId: string;
    donorId: string;
    submitterDonorId: string;
    schemaName: string;
    propertyName: string;
    exceptionValue: string;
}
type EntityPropertyExceptionRecord = {
    exceptionType: 'EntityProperty';
    programId: string;
    donorId: string;
    submitterDonorId: string;
    entityId: string;
    submitterEntityId: string;
    schemaName: string;
    propertyName: string;
    exceptionValue: string;
     
}
type ExceptionRecord = MissingEntityExceptionRecord | ProgramPropertyExceptionRecord | EntityPropertyExceptionRecord;
```

### Function Inputs
The filter for donor data could be provided by any combination of donorIDs or submitterDonorIDs. This function will need to have an input for each type of IDs.

```ts
function (filters: { donorIDs: number[], submitterDonorIDs: string[] })
```

### Return
Sorted array of ExceptionRecords.

Sorting rules:
  1. Program ID
  2. Submitter Donor ID (all program level exceptions have empty donor id, sort these above all other exceptions)
  3. Exception Type
  4. Schema Name
  5. Submitter Entity ID (could be submitter's followup id, treatment id, specimen id)

### Process

![image](https://github.com/icgc-argo/argo-clinical/assets/8339820/24942a54-899e-4c45-9e20-787235528eda)

**Comment by demariadaniel** [comment]
Sorting will be finalized in https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/argo-clinical/1143

Records are already generally sorted as specified. See output of unit test below:
<img width="412" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK20wQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b394d9a7afd4dc87bcf597cbe43d29720bcb5310/Screenshot%202024-03-05%20at%203.05.54%E2%80%AFPM.png" alt="Screenshot 2024-03-05 at 3.05.54 PM.png" />
