### ISSUE TITLE
Treatment Detail Exception - API - Create / Update Exception

### ISSUE THREAD

**Issue by joneubank** [icgc-argo/argo-clinical#1155]
Implement the API Endpoint to add treatment detail exception to donors for a program.

## Detailed Description

Refer to wiki for endpoint details: https://wiki.oicr.on.ca/display/icgcargotech/Treatment+Details+Exception

Will need to make a service module to provide the create exception implementation that is called by the api endpoint.

## Possible Implementation
Implementation will be very similar to Missing Entity Exception and can be used as a model. One important distinction: when a treatment detail exception is added no recalculation of existing donor data needs to be done as it was with missing entity exceptions.

**Comment by demariadaniel** [comment]
Working Swagger endpoints for:
- GET /exception/treatment-details
- GET /exception/treatment-details/{programId}
- POST /exception/treatment-details/{programId}

<img width="782" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWJzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--139f9a4af24c8ab72bc8e783f5fdf2820b7c83a7/Screenshot%202024-03-18%20at%2012.54.28%E2%80%AFPM.png" alt="Screenshot 2024-03-18 at 12.54.28 PM.png" />

<img width="904" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWZzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2af7fc764d138ce7b4083ec85ba0bd89a37a2ff/Screenshot%202024-03-18%20at%2012.54.16%E2%80%AFPM.png" alt="Screenshot 2024-03-18 at 12.54.16 PM.png" />

<img width="699" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW5zQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61946f009c3132077ea241342fb5a0b4b8ae1f0a/Screenshot%202024-03-18%20at%2012.54.06%E2%80%AFPM.png" alt="Screenshot 2024-03-18 at 12.54.06 PM.png" />
