### ISSUE TITLE
Treatment Detail Exception - API - Get Exception

### ISSUE THREAD

**Issue by joneubank** [icgc-argo/argo-clinical#1156]
Implement the API Endpoint to get treatment detail exception to donors for a program.

## Detailed Description

Refer to wiki for endpoint details: https://wiki.oicr.on.ca/display/icgcargotech/Treatment+Details+Exception

Will need to make a service module to provide the get exception implementation that is called by the api endpoint.

## Possible Implementation
Implementation will be very similar to Missing Entity Exception and can be used as a model.

**Comment by bhavikbhagat93** [comment]
Done with #1155
