### ISSUE TITLE
Treatment Detail Exception - API - Remove Donors from Program's Exception

### ISSUE THREAD

**Issue by joneubank** [icgc-argo/argo-clinical#1158]
Implement the API Endpoint to remove donors from a program's treatment detail exception.

## Detailed Description

Refer to wiki for endpoint details: https://wiki.oicr.on.ca/display/icgcargotech/Treatment+Details+Exception

Will need to make a service module to provide the remove donors from exception implementation that is called by the api endpoint.

## Possible Implementation
Implementation will be very similar to Missing Entity Exception and can be used as a model. One important distinction: when a treatment detail exception is added no recalculation of existing donor data needs to be done as it was with missing entity exceptions.

**Comment by demariadaniel** [comment]
Working Swagger result

<img width="1046" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTBYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3aac6aa127595f46b0f68e48f7d07fbe4d39722a/Screenshot%202024-03-27%20at%202.47.09%E2%80%AFPM.png" alt="Screenshot 2024-03-27 at 2.47.09 PM.png" />
