### ISSUE TITLE
Treatment Detail Exception - Add new exception type to Exceptions Manifest

### ISSUE THREAD

**Issue by joneubank** [icgc-argo/argo-clinical#1160]
The exceptions manifest needs to be updated to include reference to Treatment Detail Exceptions.

## Detailed Description
Details TBD. Ticket to be updated with specifics of data model.

**Comment by demariadaniel** [comment]
Sorting can get complicated when there are many records
Unit tests now cover 15 different cases, see output below to validate sort order is correct:

<img width="424" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEVQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--148f04001024ee7639a5eef5833d1e1ec1a80c08/Screenshot%202024-03-26%20at%2011.43.03%E2%80%AFAM.png" alt="Screenshot 2024-03-26 at 11.43.03 AM.png" />

<img width="411" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE1QQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--689647b73d44a3a9609326566c6f227c2b508571/Screenshot%202024-03-26%20at%2011.42.53%E2%80%AFAM.png" alt="Screenshot 2024-03-26 at 11.42.53 AM.png" />

<img width="355" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFFQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1466762ac4585e8f788ba7da59a3f65c2c446ff/Screenshot%202024-03-26%20at%2011.42.35%E2%80%AFAM.png" alt="Screenshot 2024-03-26 at 11.42.35 AM.png" />

**Comment by demariadaniel** [comment]
TSV Output example: 

<img width="1854" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0VQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0acc96a1206afb0442faa6ee3f7a58df3b2fe462/Screenshot%202024-03-25%20at%202.43.37%E2%80%AFPM.png" alt="Screenshot 2024-03-25 at 2.43.37 PM.png" />
