### ISSUE TITLE
Implement the validation rules for specimen 

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/argo-clinical#117]
- Get the schema and validations from BAs 
- This is blocked by the validation tickets, depends on how we want to put in the validation rules 

There will be some special cross-file validations that need to occur that are outside of schema validation provided in the dictionary. 

Wiki Reference of validations: https://wiki.oicr.on.ca/display/icgcargotech/Clinical+Submission+Business+Requirements#ClinicalSubmissionBusinessRequirements-Cross-EntityValidations

The scope of this ticket includes implementing these validations related to specimens:

- [x] All records should belong to the same Program; if an id is found, but does not belong to the program an error should be returned.
- [x] All donor, specimen, and sample submitter IDs across all files must be registered..  If an id is submitted that is valid format, but is not found in the registry, then an error should be returned.

**Comment by rosibaj** [comment]
Note - this is for the clinical submission endpoint not registration)
