### ISSUE TITLE
Create the argo-clinical endpoints that are needed by SONG

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/argo-clinical#118]
- Investigation on how current SONG uses the ID service
- SONG needs to pull in the ARGO IDs for Donor, Specimen & Sample

**Comment by rosibaj** [comment]
tested - the endpoints respond to the correct scopes and also find the correct donors

One issue is that the find is `case-sensitive` - i think this could be an issue. Issue possibly covered in #139
