### ISSUE TITLE
Delete existing registration if user reuploads an invalid file

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/argo-clinical#122]
if the user uploads an invalid file and there is an existing registration saved, we should delete it.

**Comment by joneubank** [comment]
On any new upload, we should remove the existing saved registration data. replace with the new file if it is good. if the new file is invalid then we have cleared all the data correctly.

**Comment by rosibaj** [comment]
Tested - was able to upload a registration and see an invalid registration clear, as well as see a valid registration overwrite the previously submitted one. 

Looks great! Thanks @jaserud !!
