### ISSUE TITLE
Updates to support new jwt structure

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#133]
The platform ui has a token utility to understand a users permissions.  Since the ego jwt format is being updated, the clinical system needs to respond to that jwt change.  It would be nice if all applications that can use a centralized token 
## Detailed Description

Update clinical to ego-token-utils  (https://github.com/icgc-argo/ego-token-utils) to support the new Ego JWT structure update.

**Comment by blabadi** [comment]
currently clinical is reading the scopes from jwt `context` part but it doesn't use ego-token-utils, if that is needed this ticket still valid, but it's working the way it is

**Comment by joneubank** [comment]
With the JWT shape change we need to update the token utils, and update clinical as well (maybe...). If we are updating clinical in this way we might as well bring in the token utils to solve it

**Comment by joneubank** [comment]
JWT Validation in Clinical is reading the correct fields corresponding to the EGO updates... no work is required.
