### ISSUE TITLE
Clear clinical submission endpoint 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#158]
There are 2 requirements for clearing a clinical submission: 
- [ ] First, the ability to clear for the entire submission.  This will remove the entire submission and no active submission should be available. 
- [x] Second, the ability to clear a single entity in a submission.

**Comment by joneubank** [comment]
https://github.com/icgc-argo/argo-clinical/tree/feat/158-clear-submission

**Comment by rosibaj** [comment]
So much magic.  Worked amazing. Thanks @joneubank !!
