### ISSUE TITLE
Get upload time per entity file

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/argo-clinical#169]
Currently there is no way to retrieve the upload date for a given file, only for the whole submission. We need this for the following UI feature:
![Screen Shot 2019-10-02 at 3.47.16 PM.png](https://images.zenhubusercontent.com/5a69f6494b5806bc2bc447b7/30803850-8723-437d-9b38-7bb9a96b62d8)

## Exit Criteria 
Add `updated data` in addition to the batch_name at the time of upload

**Comment by jaserud** [comment]
This should be fixed once in these PRs are merged:
 - https://github.com/icgc-argo/argo-clinical/pull/173
 - https://github.com/icgc-argo/platform-api/pull/70
