### ISSUE TITLE
Endpoint for TSV of Submission Workspace validation

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#174]
- supporting https://github.com/icgc-argo/platform-ui/issues/659 
- also to support API submission we need an endpoint for whole-submission validation

**Comment by blabadi** [comment]
Not sure I understand this issue

**Comment by rosibaj** [comment]
@blabadi It was discussed in the past that if a user wished to submit through the API (not UI), then they would not be able to download the error files as it is a UI only download. 

If users want to same an error file, then we would need to have a TSV endpoint. 

I don't think this is urgent, and mayne its not even needed.  I think we can consider closing this.
