### ISSUE TITLE
Feature Request - Add empty body for each clinical type 

### ISSUE THREAD

**Issue by jaserud** [icgc-argo/argo-clinical#179]
The UI needs to display a clinical data for every clinical type.
## Detailed Description
Right now clinical only returns the clinical entities that were submitted during the upload stage. But the UI needs to show data for all clinical types in our schema (even if empty)

![image](https://user-images.githubusercontent.com/34698315/66506514-79743480-ea9b-11e9-9076-a7048984af96.png)

## Possible Implementation
 - In clinical: when the activeSubmission is created in DB, we could have an empty entity for all clinical types as place holders
- In clinical: when ever an activeSubmission is returned we add empty entities for the ones that don't exist
- In gateway: anytime query/mutation returns activeSubmission, get list of schemas from clinical then add missing entities

**Comment by hlminh2000** [comment]
after a discussion with @joneubank, we've decided to move forward with this ticket.
We will be implementing this with the `in gateway` solution, that is: 
- In gateway: anytime query/mutation returns activeSubmission, get list of schemas from clinical then add missing entities

**Comment by rosibaj** [comment]
LGTM - i see all entities in the no data state now!
