### ISSUE TITLE
Technical Specs - Updating Dictionary Versions into Clinical

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#180]
Deploying a new dictionary has the potential to cause breaking changed in the clinical system.  Changes that need to be managed include: 
- Adding a new schema 
- renaming a schema
- changing a field from not required --> required
- introducing a new breaking script validation

**Comment by blabadi** [comment]
updated the technical design wiki page :

https://wiki.oicr.on.ca/display/icgcargotech/Technical+Architecture

section #8
