### ISSUE TITLE
Add global state of clinical submission 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#201]
We need to add a health state of the `Active Submission validation status after migration`

When a Dictionary is updated, active submissions will be scanned and marked as OK against the new schema or NOT OK against the new schema(s) 

If a submission is marked NOT OK, then we need to 
- [ ] Show a message to the user of an invalid submission that the dictionary has been updated to XX version (with a link)
- [ ] Show a message to the user (preferably with exactly what is wrong) 
- [ ] Set the submission back to "open"

Related UI ticket: https://github.com/icgc-argo/platform-ui/issues/927

**Comment by akachru-github** [comment]
Is this related to migration? Need to flesh this out a bit more before committing.

**Comment by blabadi** [comment]
from clinical side this is done in issue #234
