### ISSUE TITLE
🐛 can't validate multiple specimen for a donor in specimen file validation

### ISSUE THREAD

**Issue by jaserud** [icgc-argo/argo-clinical#244]
## Describe the bug
The validation only validates the last specimen for a submitter_donor_id in a file. Example below shows unregistrered `submitter_donor_id` but it's the same with other errors.

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Upload file with multiple unregistered specimen
2. Click validate
3. Only last specimen is validated

![image](https://user-images.githubusercontent.com/34698315/68788309-23059300-0611-11ea-80f5-95d16272a091.png)

## Expected behaviour
should validate all specimen
![image](https://user-images.githubusercontent.com/34698315/68789000-83e19b00-0612-11ea-89b0-f06061ea3136.png)

**Comment by rosibaj** [comment]
tested - looks amazing! All the validation works.  Thanks @jaserud !!!!
