### ISSUE TITLE
Real Usage Perfomance Tests

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/argo-clinical#248]
Grooming note: recommended to be implemented before production to make sure we don't find unpleasant performance surprises.
 

We need a performance test suite to evaluate the service performance against different situations

## Detailed Description
different situations:
- large files submitted 
- different concurrent submissions
- schema migration against large clinical db

## Exit Criteria 
1. Devlop TSVs for 2 programs, 50,000 donors in total, with "real" i.e following rules clinical data
2. submit this through the UI
3. Take a baseline performance and see how it works. 

find a way to make this reusable so we can regenreate TSV's if the schema changes  in future to restest with

**Comment by rosibaj** [comment]
waiting on basic use cases

**Comment by rosibaj** [comment]
let's break down this ticket later into more discreet testing units

**Comment by blabadi** [comment]
let's close this, we will write performance test along #422 when we do the optimization, it turned out to be easier to do it that way
