### ISSUE TITLE
Initial performance test for clinical submission

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/argo-clinical#254]
- Update the tool that @P-Saha made with sample_registration to work with clinical_submission files 
- Concurrent files, large files... large concurrent files!
- Automated performance tests in an environment testing for performance

- [ ] Create data randomizer to create large files 
- [ ] Create test cases 
- [ ] Schedule meeting to go through tests 
- [ ] Use donor/specimen/sample  for upload (schema validation)

**Comment by rosibaj** [comment]
Was going to do in Sprint 30 - moving to 31 as wajiha off!

**Comment by rosibaj** [comment]
closing as this has not been actioned on in this form. 

If we need to revist, i think a redeisgned approach is best.
