### ISSUE TITLE
lock submissions while migration running 

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/argo-clinical#257]
when a migration starts we need to block submissions & sample registrations
and when it's done we will unblock 

## Detailed Description

To avoid potential conflicts and modifications of documents that have already been checked 
we should prevent data modification while the migration is over.

## Possible Implementation

store a status of submissions in the db and check that before accepting any new uploads or alteration on existing submissions/registrations

**Comment by rosibaj** [comment]
@blabadi I tested this, and it does appear to be working but the naming is a little confusing here. 
![image](https://user-images.githubusercontent.com/15824252/70091718-c0d5f780-15ea-11ea-878d-fb27b617868c.png)

Can we name this to be a little more clear, and also imporove the descriptions? 

For example: 
`/submission/status `: description: `Get the status of the submission service`
`/submission/configs/status-update` : description: `Disable or Reopen the submission service for sample registration and clinical submission.`
would make more sense than the current endpoints. 

Im sure you have a better way to say that exactly, but i think the current state is unclear.

**Comment by blabadi** [comment]
using `status` indicates that there could be many statuses, but this endpoint is only to enable/disable submissions.

I'll update the swagger description
