### ISSUE TITLE
Revalidate donor after marked invalid by migration

### ISSUE THREAD

**Issue by jaserud** [icgc-argo/argo-clinical#283]
No way for invalid donors documents in clinical to become valid

## Detailed Description
- If a donor is marked `isValid=false` during migration, there is no flow where it can be changed to `true`
- probably want to have some way to mark donors as valid...

## Possible Implementation
- if the donor will be manually marked `isValid=true` then its a simple endpoint
- otherwise during the `commit` (or `approve`) stage of clinical submission, we can recheck if donor is now valid and set `isValid=true` accordingly

**Comment by blabadi** [comment]
To test this
1- submit clinical donor data based on Dictionary version X1 (donor should be valid )
2- create update dictionary to a version ( X2 ) that makes that donor invalid (remove an enum value used in that donor clinical data)
3- migrate clinical to version X2 
4- check that donor is now marked as invalid
5- update the invalid clinical file by submitting a new file that adheres to X2 (replace the old invalid value in the enum with a valid one)
6- observe that the donor is back to valid and the last valid schema version is X2
