### ISSUE TITLE
Add Followup as a data point in clinical import

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#285]
Draft Schema: https://github.com/icgc-argo/argo-dictionary/blob/master/schemas/follow_up.json 

A donor can have multiple follow-ups. 

- [ ]  fill errors in wiki  https://wiki.oicr.on.ca/display/icgcargotech/Clinical+Submission+Validation+Errors

**Comment by blabadi** [comment]
@rosibaj  I have checked the wiki, https://wiki.oicr.on.ca/display/icgcargotech/Business+Requirements , and comments, but couldn't conclude if there is a data validation rule for follow ups or not, is there any connection between survival_time and interval_of_followup that we should enforce?

**Comment by rosibaj** [comment]
@blabadi currently there is NOT a validation rule for follow up with survival time - we are waiting on a decision to know if we will accept post-mortem follow-ups and samples or not from the working group. I'll update the wiki as soon as we know!

**Comment by blabadi** [comment]
moving back to in progress, found a bug that follow up requires a validation to make sure a follow up submitter Id is associated with one donor only

**Comment by blabadi** [comment]
unique follow up validation on dev
![image.png](https://images.zenhubusercontent.com/5c99083bd2fde800015cf9fa/47b85828-d253-4cb9-af03-dc451cb8f39d)

**Comment by blabadi** [comment]
to Test this on QA the follow up schema has to be added to lectern and clinical has to migrate to that new schema, it's also preferable to delete existing donors for the program under test DELETE /clinical/donors

**Comment by rosibaj** [comment]
Tested from QA UI - I can successfully upload a follow-up file for the RAWR-CA test program
