### ISSUE TITLE
Add Treatment as a file upload to clinical 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#286]
Draft Schema to work off of: 
https://github.com/icgc-argo/argo-dictionary/pull/7

- [ ] Add Treatment/Chemotherapy as files that can be uploaded. 
- [ ] There should be a cross file validation that a chemo treatment is added if the treatment type is one of these 
- [ ] Both of these data elements need to be submitted together and validate with each other (treatment requires a chemo)

```
"Combined chemo+immunotherapy",
"Combined chemo+radiation therapy",
"Combined chemo-radiotherapy and surgery",```

**Comment by blabadi** [comment]
@jaserud I returned this back to ready for implementation to implement the happy flow integration test as we discussed yesterday

**Comment by blabadi** [comment]
adding this note here to not forget, submitter_treatment_id needs a data validation uniqueness check
