### ISSUE TITLE
Identify validation field dependencies

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#290]
This a list of the currently used fields in clinical data validation

[
*.program_id, 
*.submitter_(schemaName)_id, 
*.submitter_donor_id, 
specimen.acquisition_interval,
 donor.vital_status,
 donor.survival_time
treatment & therapy stuff
]

When one of these fields is updated (ex name_change) the dictionary migration needs to highlight this as the validations will stop working. To do this, it needs to know what these fields are. 

## Potential solutions
- Mark these fields in the dictionary with a `meta` tag. 
- Make the clinical migration respond to the changes. 
- Send a warning if a field has been changed.

**Comment by blabadi** [comment]
this is now missing treatment & therapy stuff

**Comment by rosibaj** [comment]
@blabadi i think regardless, we still need to decide how to tag these and then go back to the lectern to tag those - am i understanding correctly?

**Comment by blabadi** [comment]
> @blabadi i think regardless, we still need to decide how to tag these and then go back to the lectern to tag those - am i understanding correctly?

yes I just added my note to add the fields to the list in the description

**Comment by rosibaj** [comment]
https://wiki.oicr.on.ca/display/icgcargotech/Clinical+Submission+Validation+Errors#ClinicalSubmissionValidationErrors-CrossFileValidationErrors-CodetoTextMapping  I started adding them to this list so we can keep track better too! Im still working in filling it in, but will need to check with you for the details for some of them!
