### ISSUE TITLE
better tests from schema migration

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/argo-clinical#293]
## Detailed Description
We need better and more coverage for schema migration in integration tests to avoid regressions

Simulate migration changes with JSON files switching versions (changing one by one) each type of migration change.  For example: 

- change an enum 
- changing script 
-  other breaking changes 

all changes listes here (minus adding/removing a file) need to be tested.

https://wiki.oicr.on.ca/display/icgcargotech/Submission+System+Technical+Architecture#SubmissionSystemTechnicalArchitecture-8.ClinicalDictionaryversionupdate

**Comment by jaserud** [comment]
There may be more specs needed for this ticket. The way migration is setup you cannot add new schema files because clinical will not know show to find them in the donor. Also clinical has a list of schema file types it expects so removing will not even start migrations.

**Comment by blabadi** [comment]
no Product testing required for this.

However Wajiha did a great job here in structuring the tests. kudos
