### ISSUE TITLE
🐛Unique record check doesn't cover all cases

### ISSUE THREAD

**Issue by jaserud** [icgc-argo/argo-clinical#300]
## Describe the bug
It seems like just one field is not enough to check for unique records during submission

## Steps To Reproduce
For example chemo file is using `chemotherapy_drug_name` as unique identifier
1. upload chemo file with rows containing different submitter_donor_id & treatment_id but same chemotherapy_drug_name
2. will receive error for both row saying they conflict with each other which doesn't really make sense

E.g. file
```
program_id	submitter_donor_id	submitter_treatment_id	chemotherapy_drug_name	chemotherapy_dosage_units	cumulative_drug_dosage
PACA-AU	ICGC_0002	T_02	Allopurinol	mg/m²	4
PACA-AU	ICGC_0003	T_03	Allopurinol	µg/m²	20

```

## Expected behaviour
For treatment entities the "unique" portion is a multiple primary key composed of the `donor_id`, `treatment_id` and `unique_regimen_identifier`.  For the current treatment files, this consists of:

**Treatment**: submitter_donor_id, treatment_id, chemotherapy_drug_name
**Radiation**: submitter_donor_id, treatment_id, hormone_therapy_drug_name
**Hormone Therapy**: submitter_donor_id, treatment_id, radiation_therapy_modality

**Comment by blabadi** [comment]
@jaserud  is this still a valid bug ?

**Comment by jaserud** [comment]
yea, it is. But, I guess the example above isn't accurate though, I've updated it.

**Comment by rosibaj** [comment]
ask @hknahal about a `chemotherapy id` and updates for expected

**Comment by rosibaj** [comment]
tested in qa - the unique record is being correctly interperted at time of upload for the clinical files. 

Thanks @jaserud !!
