### ISSUE TITLE
store primary diagnosis in a consistent way with other other clinical entities

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/argo-clinical#301]
## Detailed Description
primary diagnosis is now stored directly in primaryDiagnosis field in donor 
we should make it consistent by adding clinicalInfo field to allow adding other non clinical fields if needed and make accessing functions have a clear convention to fetch clinical data

**Comment by blabadi** [comment]
to test:
1- submit clinical primary diagnosis file and sign off
2- in donor endpoint check that primary diagnosis is stored correctly, ex
![image.png](https://images.zenhubusercontent.com/5c99083bd2fde800015cf9fa/b858a309-90d2-471f-a4d0-1589025a5d6d)

**Comment by rosibaj** [comment]
Was done outside of sprint - this is already deployed in the current environments.
