### ISSUE TITLE
Update sample type in ICGC clinical import 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#345]
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/af229cc2-5f9b-4dcd-acae-0891b8b54ae0)

Currently a default placeholder value is being provided in the sample_type field. The import endpoints need to be updated to include the sample type information as well.  `Sample_type` was not provided in ICGC directly related to the sample.  The only way to tell this information is to review which `sample` is associated to a `file` with a specific `experimental_strategy`.  
- If the experimental_strategy = `WGS` or `WXS`, then `sample_type` = `Total DNA`
- If the experimental_strategy = `RNA-Seq`  then `sample_type` = `Total RNA`
- If the experimental_strategy = `miRNA-Seq`  then `sample_type` = `Other RNA fractions `

--

For example, for file `FI96` it has `experimental_strategy`= `WGS`, and is related to sample `SA533768` with `submitter_sample_id` = `ASHPC_0026_Pa_P`, thus the argo sample_type for this sample would be `Total DNA` 
- this information can be found in the file index: https://dcc.icgc.org/api/v1/repository/files?filters=%7B%22file%22:%7B%22projectCode%22:%7B%22is%22:%5B%22PACA-CA%22%5D%7D%7D%7D&from=1&include=facets&size=25 
![image](https://user-images.githubusercontent.com/15824252/75196715-8f248680-572a-11ea-8d3b-f1127b6fce57.png)

**Comment by blabadi** [comment]
so to get the experimental strategy we can use icgc song database :
```sql
select sample.id as sample_icgc_id,
       sample.type as sample_type,
       sample.submitter_id as sample_submitter_id,
       a.id as analysis_id,
       s2.id as sequence_read_id,
       s2.library_strategy as library_strategy,
       v.id variant_call_id
from sample
         inner join sampleset s on sample.id = s.sample_id
         inner join analysis a on s.analysis_id = a.id
         left join sequencingread s2 on a.id = s2.id
         left join variantcall v on a.id = v.id
and a.study_id='PACA-CA'
```
(you can ask rob for this or get a database dump and import it in local postgres instance

**Comment by blabadi** [comment]
latest query is on the related wiki page

**Comment by rosibaj** [comment]
@blabadi can i get the dataset files for PACA-CA for testing?

**Comment by blabadi** [comment]
https://drive.google.com/drive/u/1/folders/1cZ38ZPjukKDmuneFal5JanmUXnqbQNLz

**Comment by rosibaj** [comment]
spot checked a few sample sin PACA-CA in dev - lgtm!
