### ISSUE TITLE
Update Clinical Data to include new core field calculations 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#358]
Clinical needs to have these fields added:

- [x] `core_fields_complete_percentage`
- [ ] `extended_field_complete_percentage`

These fields calculations need to be updated at 3 points in time: 
- [x] Sign-off on clinical submission
- [ ] Submit on sample_registration

**Comment by jaserud** [comment]
Clinical is currently not storing any references of extended field calculations in the db. This is done on purpose to make it easier to migrate later when this calculation is added (we'll just look for donors without this calculation). Also any extended field calculation is zero anyways, so it should be ok for now.

**Comment by rosibaj** [comment]
@jaserud I will make a follow-up ticket for the extended calulation for later - Can you confirm that clinical is calculating on both sign-off and sample_registration actions?

**Comment by jaserud** [comment]
It is doing it for sign-off. And I remember we agreed sample_registration doesn't have any core fields calculations so it's just zero??

**Comment by rosibaj** [comment]
@jaserud  badly asked question :p you are right! it should just initialize at zero when samples are registered.

**Comment by jaserud** [comment]
@rosibaj  :tada: then all is good :+1:  This ticket calculates core fields after commit/sign-off
