### ISSUE TITLE
🐛 Donor count instead of sample count on sample_registration stats 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#360]
## Describe the bug
The sample_registration page is counting by donors, not samples in the new/updated stats. 

![image](https://user-images.githubusercontent.com/15824252/73385416-1ea95780-429b-11ea-939d-64d305a18c07.png)

For the program KIM-CA, this is the response.  In the count for newly registered the count is 4 - this is counting the `DONORS` not the `SAMPLES`
![image](https://user-images.githubusercontent.com/15824252/73385703-9d9e9000-429b-11ea-81a7-4f1a8fcbbe16.png)

## Expected behaviour
This should say the # of samples that are total, not donors.

**Comment by blabadi** [comment]
this seems to happen only when there are already registered samples 

I tried registering first time and the count was good:
![reg-bug-1](https://user-images.githubusercontent.com/8655252/73576361-4558c100-4448-11ea-87bc-440b65364c63.png)

on the next upload the ui seem to add the alreadyRegistered stats in response (which is currently a donor count) to the newSamples stats

![reg-bug-2](https://user-images.githubusercontent.com/8655252/73577159-2bb87900-444a-11ea-8b03-93168b251bb0.png)

**Comment by blabadi** [comment]
tested on dev env
![image.png](https://images.zenhubusercontent.com/5c99083bd2fde800015cf9fa/36ec1f6e-f2d8-42b9-bf36-70eb1a07b7c1)

**Comment by rosibaj** [comment]
tested on qa 
- was able to register a totally new file with correct counts
- was able to register 0 changes, and no changes were registered
- was able to register a file with only 1 new sample, and all counts were correct. 
looks great!  thanks @blabadi !
