### ISSUE TITLE
Error text: uploading sample_registration file in clinical submission section

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-clinical#361]
When I upload the sample_registration.tsv file in the clinical section it says:
![Screen Shot 2020-01-29 at 11 44 04 AM](https://user-images.githubusercontent.com/18424138/73385561-64feb680-429b-11ea-88fe-dcdaa601bd2d.png)

But even renaming this file wouldn't help.  In this case, please use the error text:

> 1 of 7 files failed to upload: sample_registration.tsv
Please upload this file in the Register Samples section. 

- this should be a clinical thing

**Comment by rosibaj** [comment]
tested in QA - the message is present when trying to upload a `register_sample` file in the clinical section.  Thank @wajiha-oicr!!
