### ISSUE TITLE
Add core field calculations to the Migration process

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#362]
Update the migrations
- [x] Check for core field meta to see if anything changed,
- [x] During dictionary migration, check donors to see if they need to have %core fields updated. 
- [x] If the donor is marked invalid during migration, the calculations are left as is. 
- [x] When the donor becomes valid the entire donor's core (and in the future extended) fields is recalculated.

**Comment by jaserud** [comment]
In addition to the specs above:
If the donor is marked invalid during migration, the calculations are left as is. When the donor becomes valid the entire donor's core (and in the future extended) fields will be recalculated.
