### ISSUE TITLE
🐛 Record is indicated as "updated" but is not

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#388]
## Steps To Reproduce
1. Go to RAWR-CA on the clinical submission in QA environment: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/RAWR-CA/clinical-submission?tab=chemotherapy
2. Upload these files:
`treatment`
```
program_id	submitter_donor_id	submitter_treatment_id	treatment_type	age_at_consent_for_treatment	is_primary_treatment	treatment_start_interval	treatment_duration	therapeutic_intent	response_to_therapy
RAWR-CA	rawr-1	T_04	Hormonal therapy	15	Yes	123	195	Concurrent	Partial response
RAWR-CA	rawr-1	T_03	Radiation therapy	15	Yes	192	204	Concurrent	Partial response
RAWR-CA	rawr-1	T_06	Chemotherapy	13	Yes	192	204	Concurrent	Partial response
RAWR-CA	rawr-2	T_07	Chemotherapy	13	Yes	192	204	Concurrent	Partial response
```
`chemotherapy`
```
program_id	submitter_donor_id	submitter_treatment_id	chemotherapy_drug_name	chemotherapy_dosage_units	cumulative_drug_dosage
RAWR-CA	rawr-1	T_06	Still need it	µg/m²	14
RAWR-CA	rawr-1	T_06	Need list	µg/m²	12
RAWR-CA	rawr-2	T_07	Need list	µg/m²	12
```
3. Click Validate.  You will see it is saying that some records are updated:
![image](https://user-images.githubusercontent.com/15824252/75072448-83845600-54c5-11ea-9a0e-2ef2369dbba5.png)

4. Submit/approve the files.
5. Reupload the SAME EXACT FILES.  these records will still be counted as updated, even thought hey are not updates. 

## Expected behaviour
`No changes` in submitted should not be counted as `updates`

## Possible issues

**Comment by blabadi** [comment]
I can't reproduce this on QA (I used other program: TEST-CA):
![image.png](https://images.zenhubusercontent.com/5c99083bd2fde800015cf9fa/d755dc5e-7ffc-44fa-9bfd-d308bc7964ef)

**Comment by rosibaj** [comment]
@blabadi I slacked you my exact file where i see the issue!

**Comment by blabadi** [comment]
Was able to reproduce with these files: https://drive.google.com/drive/u/1/folders/1mioGSqG_VJczm0cKOZqdizvoGBiq4UpV

**Comment by blabadi** [comment]
the bug seems to affect every clinical file where a single donor can have multiple instances of like follow up, treatment, specimen (clinical file)

**Comment by rosibaj** [comment]
tested on qa with RAWR-CA and TEST-CA - was able to upload the same files  in multiple submissions without this issue happeneing  

lgtm!  Thanks @blabadi !

**Comment by rosibaj** [comment]
verified on prod - lgtm
