### ISSUE TITLE
🐛 Specimen required fields for tumour

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-clinical#408]
## Describe the bug
Two more fields are required if the specimen is tumour
(sorry, they were not included in here: icgc-argo/argo-dictionary#54)

tumour_histological_type
central_pathology_confirmed

## Expected behaviour
A submitter should need to fill those out if their specimen is a tumour

related to: https://github.com/icgc-argo/argo-docs/issues/139

**Comment by rosibaj** [comment]
tested on platfrm qa 
- uploaded a specimen file with these two fields missing; schema validation passed
- clicked validate and got 2 errored that they are required if tumour_normal_designation is tumor

lgtm @blabadi @wajiha-oicr !!

**Comment by blabadi** [comment]
deployed to prod pending testing

**Comment by rosibaj** [comment]
tested on production - working as expected now!
