### ISSUE TITLE
Multi-threaded application implementation - sample registration 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#421]
- [ ] Parallelize the request in smaller chunks to speed up processing 
- [ ] This scope is for sample_registration  only

**Comment by blabadi** [comment]
current problems that were fixed :
1- schema validation: (scripts mostly), can be parallelized by worker a threads pool 

2 - there was a 3 x n^2 loops in the in-file cross-record validation:
- for each new donor we iterate over all submitted records to check in file conflicts 
- for each specimen we iterate over all submitted records to check in file conflicts
- for each sample we iterate over all submitted records to check in file conflicts 
solution do a single loop and create indexes to lookup submitted record by sample, specimen, donor sub Id
and use that to find where it was referenced in the same file

**Comment by blabadi** [comment]
related PR: https://github.com/icgc-argo/argo-clinical/pull/439/files

**Comment by blabadi** [comment]
Testing:
- Check time for one upload (use network tab in browser dev tools)
- Check time for concurrent upload (open two browsers, different programs, upload 2 big files same time)
(we have 2 instances of Clinical on QA now, we should serve 2 uploads in less than 6 secs)
- any regressions on sample registration

**Comment by rosibaj** [comment]
@blabadi do you have a large file already formatted that i can use for testing?

**Comment by blabadi** [comment]
@rosibaj  yeah here: https://github.com/icgc-argo/argo-clinical/tree/master/test/performance-test 
check the 3k / 1k / 300 tsvs

**Comment by rosibaj** [comment]
I tested 3K with the UI - it has a lot of issues from the frontend.  The Sample Registration page crashed several times in the process.  @blabadi did you have a time for how long 3K samples took thru the api only for load/registration that I can compare to?

**Comment by blabadi** [comment]
the browser can have hard time rendering the 3k rows, the UI needs to do pagination which I mentioned before. 
I'll give it a shot on QA and see the time it takes there.

**Comment by blabadi** [comment]
through the UI i got this time (7 secs) not including the rendering delay
![testca 3k qa](https://user-images.githubusercontent.com/8655252/78793862-fe73d400-7980-11ea-9c6b-d292e23cfcb5.png)

**Comment by blabadi** [comment]
note that the response is around 13 MB which is too big and can affect response time based on the internet speed of the user with our servers, I believe we can use compression there but that's another war to fight

**Comment by rosibaj** [comment]
yup @blabadi - I just wanted to compare some times in various scenarios. 

Did you have a benchmark time through the api for both the upload and commit steps that you were seeing that I can compare to in my testing?

**Comment by blabadi** [comment]
from the API - around 6.8 secs on QA: 
![image](https://user-images.githubusercontent.com/8655252/78806766-29feba80-7991-11ea-83e8-2620e354ecc2.png)

**Comment by blabadi** [comment]
the commit API is not on QA yet, it currently will take around 27 seconds give or take
