### ISSUE TITLE
optimizing queries in sample registration commit

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#423]
the upload has been optimized, but the commit is still sow
we need to perform the same optimization on the registration commit steps.

**Comment by blabadi** [comment]
Refactored the commit endpoint to be more performant
baseline : 3k document took 27-28 seconds on localhost
now it takes between 9-12 secs on localhost

there is a bottleneck that I'm suspecting related to generating sequential unique id that even with parallelization of update/create statements for documents. but for this sprint this is a good improvement to begin with.

**Comment by blabadi** [comment]
tested upload & commit on QA
tested invalid rules (using conflicting specimen id, sample id)
tested invalid header name
tested registering existing specimen to new donor
tested uploading new & old samples, counts seem correct

**Comment by blabadi** [comment]
@rosibaj you can test it now if you want, then we can decide to deploy this on prod, from my end it looks good and I would deploy it to prod today.

**Comment by rosibaj** [comment]
@blabadi if you have tested then im happy to deplpy this to prod today.

**Comment by blabadi** [comment]
ok will release it now then
