### ISSUE TITLE
Solid tissue case is incorrect in icgc import 🐛 

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/argo-clinical#426]
Description:
Reported here: https://github.com/icgc-argo/roadmap/issues/321

Root cause
the import had a typo 'Solid Tissue' instead of 'Solid tissue' value for specimen tissue that didn't match dictionary.

Fix
fix the typo to match dictionary 'Solid tissue'

Impacted systems
rdpc - clinical QA, in case they did the import in QA already
no impact on production argo platform

**Comment by rosibaj** [comment]
Tested on Qa with re-import into PACA-CA - i see the correct `Solid tissue` recorded now.
