### ISSUE TITLE
🐛 Treatment type updates for the same treatment id

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-clinical#435]
## Describe the bug
As a data submitter, I can upload a treatment and associated treatment file using one id. Then I can change the treatment type for that same id and upload a new associated treatment file.  What happens to the old treatment type data? Do we need a validation that warns them that the old treatment data will be deleted for this treatment id?

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to register samples section and register: https://drive.google.com/open?id=1yDtcdA_mlNS_ysLfTC04nnhud66h9J1d
2. Go to Clinical Submission and upload the treatment file + associated chemo file:
Treatment file: https://drive.google.com/open?id=1eqW22BVcLEds8f2h2bA_1-mvaOXUwKSR
Chemo file: https://drive.google.com/open?id=1hZxT3FWTpreMP-Q30r4SzhIR6Vmv12YO
3. validate and sign off - so TRE-108 is associated with a chemotherapy file
4. Start a new submission. Change the treatment type for TRE-108 to Hormonal Therapy. Upload the treatment file + associated hormone therapy file
Treatment file:https://drive.google.com/open?id=1K2ZvtDs009bALxGr6nXMlnoEBklMRueS
Hormone Therapy file: https://drive.google.com/open?id=1RWCRtil1OI1HKxTCaSLE4GW1JH7S8JS7

What happens to that Chemotherapy data that used to be associated with TRE-108?

## Expected behaviour

We will removed the "combined terms:
- Combined chemo+immunotherapy
- Combined chemo+radiation therapy
- Combined chemo-radiotherapy and surgery

Instead, `treatment_type` to accept an array of values instead of a single value from the codelist. So for example, if a patient had combined chemotherapy and radiation therapy treatment, the data submitter would submit an array of two treatments:

 `treatment_type: ["Chemotherapy", "Radiation therapy"]`

In this array: 
- order does not matter (ie. treatment_type: ["Chemotherapy", "Radiation therapy"] and - -- treatment_type: ["Radiation therapy", "Chemotherapy"] are the same.
- values within a single must be unique (ie. treatment_type: ["Chemotherapy", "Radiation therapy", "Chemotherapy"] not allowed.

If a user updates a `treatment_type` array with: 
- **Adding** a `treatment_type`, then the validtion should require all listed treatment types. 
For example, a users goes from   `treatment_type: ["Chemotherapy"]`  to  `treatment_type: ["Chemotherapy","Hormone therapy]`,  and has a `chemotherapy` file already submitted, then during submission a `hormone_therapy` file should be required during the `validation` step.

- **Removing** a `treatment_type`, then the associated data should be removed (but the user should be warned.)
- if multiple values are removed from the array, multiple `treatment_type` datas will be removed

For example, a users goes from   `treatment_type: ["Chemotherapy", "Radiation therapy"]`  to  `treatment_type: ["Chemotherapy"]`, then during submission:
- the treatment type should be updated
- the `radiation_therapy` fields/data that had been previously submitted should be deleted

UI for discussion: 
![image](https://user-images.githubusercontent.com/15824252/82930000-a0ac4300-9f52-11ea-9c58-56c79038953f.png)

Zeplin link: https://zpl.io/beEQkqW

## Clinical Tasks for this: 

- [ ] Update the validation response to inlcude a `warning` type
- [ ] In the commit, implement the logic to delete the indicated treatment objects

**Comment by blabadi** [comment]
@rosibaj 
if you go from `Chemo` to `Chemo + something else` that's ok  because you are adding, but if you go from `Chemo` to `radiation` then you are deleting records and we will have to REMOVE the related therapy data . I think this should be handled sooner than later

we either do that, or we change treatment types to avoid this weird combination logic.. and let submitters use 1 type per treatement, and they submit different treatments and they endup without ability to delete like other clinical files.

**Comment by kcullion** [comment]
@blabadi I did a mockup for this - to show a warning for the user that their previously submitted data will be deleted: https://invis.io/FES2W305M6Q#/410685210_Clinical_Treatment_Update

I didn't add to the ticket yet, @rosibaj I think we were still reviewing

**Comment by rosibaj** [comment]
> @rosibaj I think this should be handled sooner than later
> if you go from `Chemo` to `Chemo + something else` that's ok because you are adding, but if you go from `Chemo` to `radiation` then you are deleting records and we will have to REMOVE the related therapy data .
> 
> we either do that, or we change treatment types to avoid this weird combination logic.. and let submitters use 1 type per treatment, like `Chemo` `immunotherapy` no combining `Chemo + immuntherapy` , if needed they submit different treatment ids for each type and they end up without ability to delete it, like other clinical files.

@hknahal ^ thoughts on the treatment type change Bashar suggested above?  I think it kind of makes more sense to do that than allow combinations, bc what if there is a combination treatment that we havn't submitted a combination for?

**Comment by hknahal** [comment]
I agree, it will be difficult to manage later especially if we have more combinations. The "combined" treatments mean that for example, chemotherapy treatment and radiation treatment are given at the same time. So the `response_to_therapy` is the response to both treatments, not the individual treatments. @blabadi If we remove `Combined chemo+radiation therapy`, can the data submitter submit the two terms `Chemotherapy` and `Radiation` as an array? For example:

`treatment_type`: `Chemotherapy, Radiation`

This would allow us to capture the `response_to_therapy` once. If we were to separate them out (ie. have two separate `treatment_type` entries - one for `Chemotherapy` and one for `Radiation`) then we will capture `response_to_therapy` twice, which is misleading because the response is actually to the combination of the two treatments.

**Comment by blabadi** [comment]
summary of slack discussion:
- use arrays for treatment type, should have distinct elements, order is not significant 
- if a treatment type that requires a therapy file removed, we should delete it from the system

related dictionary change: https://github.com/icgc-argo/argo-dictionary/issues/143

**Comment by blabadi** [comment]
we will need a new indication in lectern (meta key or new field property) that if a field is array then whether elements can be repeated or not in the array

**Comment by rosibaj** [comment]
> we will need a new indication in lectern (meta key or new field property) that if a field is array then whether elements can be repeated or not in the array

should there be general array properties?  Im thinking og both `ordered` and `unique`.  would there be anything else?

**Comment by blabadi** [comment]
> > we will need a new indication in lectern (meta key or new field property) that if a field is array then whether elements can be repeated or not in the array
> 
> should there be general array properties? Im thinking og both `ordered` and `unique`. would there be anything else?

yeah those should be generic for any array field, this particular case is code validated so it doesn't need it specifically but other cases will. 

are you thinking about meta keys or field properties ?

**Comment by rosibaj** [comment]
@blabadi i guess as field properties.  `meta` propreties are more administrative (i.e dont affect the data).  the difference between an ordered and a not ordered array is a data impact though (same with unique)

**Comment by rosibaj** [comment]
Tested July 29, 2020:

I registered a donor with a chemotherapy treatment for `submitter_treatment_id =dashtr10-2`:
![image](https://user-images.githubusercontent.com/15824252/88839068-7cfeb680-d1a8-11ea-946a-a5b5a6537574.png)


After, I completely changed `submitter_treatment_id =dashtr10-2` record to a different treatment type - radiation therapy: 
![image](https://user-images.githubusercontent.com/15824252/88839206-bb947100-d1a8-11ea-870a-56b90c93d00c.png)


When i check the submission, i DO see data warning in the `treatment` section: 
![image](https://user-images.githubusercontent.com/15824252/88839586-45dcd500-d1a9-11ea-96da-573929573595.png)
 
I also see this: 
![image](https://user-images.githubusercontent.com/15824252/88840651-cd771380-d1aa-11ea-8a8b-d09b44c844ee.png)


----- 
Update from bashar; issue already ticketed
https://github.com/icgc-argo/argo-clinical/issues/590

**Comment by rosibaj** [comment]
Testing files here: https://drive.google.com/drive/u/1/folders/1bIFbT_kK3JOyB8KOTjyXh1oW9D2OKW-v

**Comment by hlminh2000** [comment]
I've moved version `1.37.0` of clinical to staging. this ticket was tagged with `1.34.0` so please confirm the ticket status before we move forward with production deploy
