### ISSUE TITLE
Get Donor API

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#442]
- add endpoints to clinical that can return donor clinical data for use by applications like `files-service` or `donor-dashboard-aggregator`

**Comment by akachru-github** [comment]
This ticket can be closed as we will not be building endpoints to access clinical data. 

- donor-dashboard-aggregator already read clinical data directly from the DB.  does not go through an endpoint. 
- proposal is to continue having services living int he same network to access clinical data in the same fashion: directly. 
  - infra configs will be needed here: ingress for DB
  - Only one DB user. aggregator and clinical are using the same user. They should be different. All services that will read clinical data directly should have their own user with read-only permissions.
