### ISSUE TITLE
Integrate with dictionary service

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/argo-clinical#45]
We need to integrate lecturn with the clinical submission instead of using the mock schema that is currently hardcoded. 

- [ ] Call lectern on start of submission service
- [ ] Check the saved schema 
- [ ] Need to fetch saved schema in case of failure
- [ ] Write mock tests 

NOT IN SCOPE :
- difs

**Comment by alekspejovic** [comment]
Hacky way to test, but I'll accept it :P

Looks great - Closing!

**Comment by blabadi** [comment]
> Hacky way to test, but I'll accept it :P
> 
> Looks great - Closing!

hahaha thank you @alekspejovic
