### ISSUE TITLE
Feature Request: Allow multiple Primary Diagnoses

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#451]
https://github.com/icgc-argo/argo-dictionary/issues/85

Address requirement from the dictionary in this ticket. Changes needed:
1. change donor model in mongo to have array of primary diagnosis (data migration)
2. As result of adding a new required field in schemas
  a. specimens / follow ups / treatments: to have the new clinical field `submitter_primary_diagnosis_id` (file re submission required, all existing donors will be invalid) 
  b. update existing primary diagnoses to have a submitter primary diagnosis id ( _how will we fill this for existing data?_)

3. change donor entity to have array of primary diagnosis
4. change schema migration to expect array of primary diagnosis (get Clinical entity function)
5. Add a validation rule that checks  if a primary_diagnosis with the id in the file has already been submitted (i.e the primary key already exists) or it is included in the current submission upload.

**Comment by blabadi** [comment]
this is now waiting on the PR in argo-dictionary to be merged

**Comment by rosibaj** [comment]
@blabadi why do we need the dictinoary PR to be merged? can't we submit the dictionary regardless?

**Comment by blabadi** [comment]
> @blabadi why do we need the dictinoary PR to be merged? can't we submit the dictionary regardless?
I just want to submit a proper dictionary that will match what will go to QA and Prod, if you want me to use the feature branch I can

**Comment by rosibaj** [comment]
@blabadi I tested this with these files: 

[primary_diagnosis_and_id_testing_files.zip](https://github.com/icgc-argo/argo-clinical/files/4654010/primary_diagnosis_and_id_testing_files.zip)

Im having this issue.  Can you help me understand what is going on validation wise? 

![image](https://user-images.githubusercontent.com/15824252/82392757-ad8cdc00-9a12-11ea-9636-9e408defd280.png)
![image](https://user-images.githubusercontent.com/15824252/82392801-c2696f80-9a12-11ea-8165-bae6bc910c88.png)

**Comment by rosibaj** [comment]
Testing note 2: 
- was able to submit multiple PD when formatted correctly
- was not allowed to submit PD with the same `submitter_primary_diagnosis_id` as expected

**Comment by blabadi** [comment]
Is there any action needed regarding the Screen shot above ?

**Comment by blabadi** [comment]
I see the problem now, yeah this happens because we look at the state of the donor specified in the donor submitter ID, after we merge the new records with existing stuff, and we check the list of PDs and we don't find that so we complain.
this error can happen if an id is missing in the PD file or just linked to a wrong donor

the message is confusing and hard to pin point I agree, this unfortunately also a production bug right now

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/argo-clinical/issues/489 Found bug is moved to this ticket 

movein this ticket forward as the primary diagnosis submission is going correctly!

**Comment by rosibaj** [comment]
confirmed on production
