### ISSUE TITLE
Incorporate Drug Name Validation 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#452]
https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Drug+Name+Specification 

- The user will be allowed to submit the `RxNormID` OR the `drug_name`  and we do the work for them
- The user will not be given any "fuzzy match" informtion of they submit a bad drugname/id.
- verification of data will be performed at `validation` state, not file upload schema validation (i.e when user clicks validate button)

### PROPOSAL: 
Dictionary Changes: change to drug_id/drug_name  for all treatment files.
``` 
   {
      "name": "drug_rxnormid",
      "description": "RxNormID assigned to the treatment regimen.",
      "valueType": "integer"
    },
   {
      "name": "drug_name",
      "description": "Name of agent or drug administered to patient as part of the treatment regimen.",
      "valueType": "string",
    },
```
When the treatment files go through validation:
-  [ ] If only `drug_rxnormid` is submitted, then check that value is a valid id.  Save the corresponding Name and ID. 
-  [ ] If only `drug_name` is submitted, then check that value is a valid drug name in the RxNorm Data Source.  Save the corresponding Name and ID to the database.
- [ ] If both `drug_rxnormid` & `drug_name`  are submitted, then check that they are a valid id/name pair in the RxNorm Data Source
- [ ] In the event that any of these cases do not apply to the submitted data, a validation-level error will appear like this:
```
This is not a valid RxNorm entry.  Please verify the drug_rxnormid or drug_name
```

UPDATE: ^ instead id/name are both required to be submitted.

**Comment by blabadi** [comment]
marking as blocked for now to wait for decision on whether to add submitter therapy id or not.

**Comment by rosibaj** [comment]
Update after the initial analysis of implementation:

Currently `donor_id`, `treatment_id`, and `chemotherapy_drug_name` form a unique record to identify the therapy. 

In validation, the order goes like this:
1. headers
2. uniqueness
3. schema. 

If we make the [suggested changes](https://github.com/icgc-argo/argo-dictionary/pull/94), when a user submits then they can submit either `drug_name` or `rxnorm_id`. The possibility of having wither of these fields be empty in this scenario means that neither can replace the current unique key (`chemotherapy_drug_name`). 


Potential solutions:
1. Leave the structure as is and import drug names as a enum instead of a validation.
2. Add a `submitter_therapy_id` field to  maintain uniqueness.
---- this adds work on the submitter to identify therapy agents uniquely, but allows them to be more flexible in how they submit the therapy identifiers (name, id, or name and id) 
3. Make `rxnorm_id` required.  Submitters have to identify the `rxnorm_id.` `rxnorm_Id` cna be used as the unique key.
---- this adds work on the submitter to identify the rxnormid of all therapies before they submit.  It creates a stricter submission regimen.

**Comment by rosibaj** [comment]
Discussed with Christina: 
- make both `rxnorm_id` and `drug_name` required fields
- can use `rx_norm_id` as the unique

**Comment by blabadi** [comment]
For the scope of this ticket the implementation includes:
- implement support for the RxNorm new headers in Chemotherapy and Hormonetherapy, instead of the drug name field
- it includes an implementation for mysql backed lookups to support importing 

it DOESN'T include:
- the logic to update the rxnorm db to a new release, including the migration of existing donor records.

**Comment by rosibaj** [comment]
@blabadi i guess i can merge the drug name pr now too?

**Comment by blabadi** [comment]
@rosibaj 
it's still not in QA, I need :
1- to deploy an rxnorm db instance in Dev & QA
2- publish a new version of the dictionary in dev  ( we can use your PR branch to test on Dev)
3- deploy & migrate clinical to the new schema
4- test in dev
then 
5- do these steps for QA

**Comment by rosibaj** [comment]
sure we can wait till qa is tested to merge then.

**Comment by rosibaj** [comment]
> it DOESN'T include:
> 
> * the logic to update the rxnorm db to a new release, including the migration of existing donor records.

Followup ticket:
https://github.com/icgc-argo/argo-clinical/issues/476

**Comment by blabadi** [comment]
before moving this I need to update the release instructions

**Comment by rosibaj** [comment]
@blabadi can you please add a version label tag to this ticket? Cannot release it till added too!

**Comment by kcullion** [comment]
@blabadi I can't test this again because collab is down, maybe it's not the case anymore - but I noticed yesterday in your demo and when I did test, that the error message doesn't have the Submitter donor id
<img width="1139" alt="Screen Shot 2020-05-06 at 9 54 11 AM" src="https://user-images.githubusercontent.com/18424138/81185507-ab8d3c80-8f7f-11ea-9a7c-d3638fafa9a2.png">

**Comment by blabadi** [comment]
@kcullion thanks, will fix this

**Comment by rosibaj** [comment]
I completed a migration to the dictionary (version 43.0) in QA: 
- I was able to successfully upload chemotherapy files with the new schemas (`rxcui` + `drugname`)
- submitting without and rxcui resulted in the correct error asking me to fill one in. 
- submitter without a drug name gave me the correct error showing a list of acceptable values.

**Comment by rosibaj** [comment]
verified that I was able to submit a chemotherapy treatment for a patient with the new drug names on production
