### ISSUE TITLE
OICR IT Internal Scan Vulnerabilities for Clinical

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/argo-clinical#459]
Below are the results of the OICR IT scan:

![image.png](https://images.zenhubusercontent.com/5d55b1b74d335f147c3e6dc0/772ff01f-1b3d-4155-ae89-320bcbe0fb95)

**Issue description**

HTTP request smuggling vulnerabilities arise when websites route HTTP requests through webservers with inconsistent HTTP parsing.
By supplying a request that gets interpreted as being different lengths by different servers, an attacker can poison the back-end TCP/TLS socket and prepend arbitrary data to the next request. Depending on the website's functionality, this can be used to bypass front-end security rules, access internal systems, poison web caches, and launch assorted attacks on users who are actively browsing the site.

**Issue remediation**

You can resolve all variants of this vulnerability by configuring the front-end server to exclusively use HTTP/2 to communicate to back-end systems, or by disabling back-end connection reuse entirely. Alternatively, you could ensure all servers in the chain run the same webserver software with the same configuration.
Specific instances of this vulnerability can be resolved by reconfiguring the front-end server to normalize ambiguous requests before routing them onward, or by configuring the back-end server to reject the message and close the connection when it encounters an ambiguous request.

**References**

HTTP Request Smuggling
HTTP Desync Attacks

**Vulnerability classifications**

CWE-444: Inconsistent Interpretation of HTTP Requests ('HTTP Request Smuggling')

**Comment by blabadi** [comment]
waiting on IT to update the ticket based on my latest comment there that this issue is in the F5 since it only supports http 1.1 and unless they fix that we can't upgrade our infra structure to only accept that to avoid the smuggling

**Comment by blabadi** [comment]
Based on latest IT comments there is no action from our end here.

**Comment by akachru-github** [comment]
Here is the IT ticket for reference: https://servicedesk.oicr.on.ca/servicedesk/customer/portal/2/IT-27849
