### ISSUE TITLE
Update clinical Completeness calulation

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#465]
https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Program+Dashboard+Page+Specs#ProgramDashboardPageSpecs-DataCalculations

**Comment by jaserud** [comment]
For specimens it is not calculated at all if a pair of tumour and normal is not available. Thats how I check the condition that a tumour and normal pair has to be submitted in addition to a record for each specimen

**Comment by rosibaj** [comment]
Just to make sure i understand:
- if a T/N pair exists, then complete the calculation specified on the wiki
- if a T/N pair does not exist at all then no calculation (hence 0 for specimens)

**Comment by kcullion** [comment]
@jaserud not sure if this is a bug...but this is what I did:
1. registered a donor with a normal specimen- clinical completeness: 0%
2. submitted a donor file - clinical completeness: 20%
3. submitted a primary diagnosis - clinical completeness: 40%
4. submitted specimen details for that normal specimen: clinical completeness is still 40% ?

**Comment by rosibaj** [comment]
so @kcullion you only have 1 specimen, and its only a normal right?

**Comment by kcullion** [comment]
@rosibaj yes just 1 normal specimen

**Comment by rosibaj** [comment]
so yes, you need to register `at least` one tumor as well to initiate the calculation.

**Comment by kcullion** [comment]
oh ok...so my specimen details for the normal don't really count until I register a tumour. I just did that and submitted the tumour details and it's at 100% now so that's good
