### ISSUE TITLE
Allow Clinical to accept array fields 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#467]
Address requirement from the dictionary in this ticket:

Changes needed:

change donor model in mongo to have array of primary diagnosis (data migration)

- for array fields, parse the field comma separated values submitted into an array
- a codelist/script needs to apply to every submitted array value
- Write the database migration for the single field which will be an array presenting_symptoms. right now this will only possibly have one value, and will need to be wrapped in an array.

**Comment by jaserud** [comment]
There is no script to change existing presenting_symptoms to array. so currently db will leave array fields with single values as is. This will not cause any issues with dictionary migration or any validations. There is a ticket to update clinical records for consistence during migrations: https://github.com/icgc-argo/argo-clinical/issues/485.

**Comment by rosibaj** [comment]
@jaserud Should this work?  I tried submitting comma separated `presenting_symptioms` and got this issue: 
![image](https://user-images.githubusercontent.com/15824252/82393429-5425ac80-9a14-11ea-9836-684a9e5504e1.png)

```
program_id	submitter_donor_id	submitter_primary_diagnosis_id	age_at_diagnosis	cancer_type_code	basis_of_diagnosis	number_lymph_nodes_positive	number_lymph_nodes_examined	clinical_tumour_staging_system	clinical_stage_group	stage_suffix	clinical_t_category	clinical_n_category	clinical_m_category	presenting_symptoms	performance_status
DASH-CA	DASH-1	dashpd-1	51	C71.1	Clinical	2		Ann Arbor	Stage I						Grade 1
DASH-CA	DASH-2	dashpd-2	53	C50.2	Histology of a primary tumour	0		AJCC 8th Edition	Stage II		T1	N0	M0		Grade 0
DASH-CA	DASH-3	dashpd-3	28	C15.2		0		AJCC 8th Edition	Stage II		T2	N0	M0		Grade 0
DASH-CA	DASH-4	dashpd-4	19	C15.5		2		AJCC 8th Edition	Stage II		T4a	N1	M1		Grade 1
DASH-CA	DASH-5	dashpd-5	20	C25.1		0		AJCC 8th Edition	Stage III		T1	N0	M0		Grade 0
DASH-CA	DASH-6	dashpd-6	63	C25.1	Specific tumour markers	2		AJCC 8th Edition	Stage II		T1	N1	M0		Grade 0
DASH-CA	DASH-7	dashpd-7	56	C25.2	Specific tumour markers	6		AJCC 8th Edition	Stage III		T1	N2	M0		Grade 0
DASH-CA	DASH-8	dashpd-8	68	C25.9	Histology of a primary tumour	1		AJCC 8th Edition	Stage I		T1	N1	M0		Grade 0
DASH-CA	DASH-9	dashpd-9	37	C18.4		0		AJCC 8th Edition	Stage I		T2	N0	M0	Nausea	Grade 0
DASH-CA	DASH-10	dashpd-10	34	C18.9		0		AJCC 8th Edition	Stage IV		T1	N0	M0	Nausea,Anemia	Grade 1
```

**Comment by rosibaj** [comment]
UPDATE:  This is actually the result of a different error:  I logged the bug for that here: https://github.com/icgc-argo/platform-ui/issues/1466 

Once the quotation marks were removed i was able to successfully submit array values in `presneting_symptoms` column. 

However, I saw the same issue when I submitted an invalid value for an enum (i appended x to anemia: 
```
DASH-CA	DASH-10	dashpd-10	34	C18.9		0		AJCC 8th Edition	Stage IV		T1	N0	M0	Nausea,Anemiax	Grade 1
``` 

In this situation i would expect to get a schema error letting me know `Anemiax` is not part of the codelist for `presenting_symptoms`

**Comment by rosibaj** [comment]
@jaserud moving back to inprogress until the above comment can be fixed

**Comment by jaserud** [comment]
Hmmm, :thinking: something very strange is going on here. Will take a look.

**Comment by rosibaj** [comment]
Re tested: 
- able to successfully upload comma delimited values
- when only one value is submittted in the array that is wrong, it now presents the correct error instead of freezing
![image](https://user-images.githubusercontent.com/15824252/82605146-74c04480-9b83-11ea-94dc-c0c7d7745959.png)

lgtm thanks @jaserud !!!!

**Comment by rosibaj** [comment]
verified as working on production
