### ISSUE TITLE
always fetch schema from db 🐛 

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/argo-clinical#472]
## Describe the bug

if the schema is updated and the schema is stored in memory then multiple instances of clinical go out of sync.

a suggested better behavior is to fetch it from db and cache it on request level

Edit: I have an Idea of instead of fetching the whole dictionary every time, to do a version check query instead and if the version changed we do load the new schema, otherwise just use what is cached. that way we save time and loading size

**Comment by blabadi** [comment]
whoever does dictionary releases should be aware of this

**Comment by blabadi** [comment]
@jaserud when you deploy and test this in dev / QA please scale up clinical to have like 3 instances to make sure requests go to different services

**Comment by jaserud** [comment]
:+1: scaled clinical to 3

**Comment by rosibaj** [comment]
I migrated to dictionary 49.0 in QA environments - despite many many file uploads, none of them failed with the unexpected schema headers errors.

lgtm! thanks @jaserud !
