### ISSUE TITLE
Refactor and add common-model

### ISSUE THREAD

**Issue by jaserud** [icgc-argo/argo-clinical#486]
The clincial setup has been revised and a new design agreed upon:
![image](https://user-images.githubusercontent.com/34698315/81203528-10ec2800-8f96-11ea-9677-43929a8ea8ff.png)

## Detailed Description
- Mostly just moving code and renaming things
- Rename root level `schema` to `dictionary` to be consistent with argo setup

**Comment by jaserud** [comment]
Some endpoints are deprecated now. These and the new endpoints are noted in swagger 
![image](https://user-images.githubusercontent.com/34698315/81737551-439a9280-9466-11ea-9696-deb8026de494.png)

**Comment by rosibaj** [comment]
@jaserud sorry this is done?  i dont see that it was on the board before - just making sure i undestand

**Comment by jaserud** [comment]
@rosibaj yes this is done

**Comment by rosibaj** [comment]
I was able to successfully use the new dictionary endpoints to migrate to dictionary `47.00` in the QA environment.
