### ISSUE TITLE
Data Connection: Download All Clinical Data

### ISSUE THREAD

**Issue by jaserud** [icgc-argo/argo-clinical#489]
@rosibaj commented on [Thu Apr 09 2020](https://github.com/icgc-argo/platform-ui/issues/1318)

When the user clicks the `Download All Clinical` button: 
- a tar zipped file should download entitled `<Program Name>_Clinical_data<Date>`. for example, `PACA-CA_Clinical_data_20200420`
- Inside the zip, there should be a set of TSV files.  There should be one TSV file per relevant clinical submission files for a program, containing all possible data for that clinical data
-- If none of a clinical entity has been submitted for no donor, a blank TSV file should not be provided.  Instead, this clinical entity should be absent from the tar. 

The clinical files should be formatted such that they could be ready to upload back to the system as soon as they are downloaded.

-- Look at the current clinical schema for headers 
-- Format the data from the documents into the schema files 
-- Export cannot block main thread 
-- Should be gated through the gateway

---

@rosibaj commented on [Tue May 05 2020](https://github.com/icgc-argo/platform-ui/issues/1318#issuecomment-624076342)

Discussion on slack: 

- I think it makes sense to put additional fields/headers that are found in records in addition to the expected headers in tsvs. 
- I imagine users would want to see the invalid fields so they can fix them before resubmission. - Missing fields can be empty for record but the header will be their. Renamed/deleted fields will show up in the tsv (at the end of the valid columns) so that users can delete or correct them. 

In general, for schema changes: 
- renamed/deleted fields should be migrated when that happens, so we shouldnt see too many of these.
- new fields added would show as blank in an export
- deleted schemas (if we didnt delete the data) should not be exported.

**Comment by rosibaj** [comment]
@jaserud which endpoint on the clinical swagger does this relate to?

**Comment by jaserud** [comment]
@rosibaj Oops sorry about that. The new endpoint is `/clinical/program/{programId}/tsv-expport`

**Comment by rosibaj** [comment]
Testing results:
Windoows Chrome
test program: dash-ca 
https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/DASH-CA/clinical-submission?tab=chemotherapy 

- I used the platform button to download all clinical files
- i got a correctly named zip file 
- i extracted the files
- i reuploaded the files directly to the clinical submission.  I did not open them in excel or  a text editor before re-upload
4 files worked, 4 files did not
![image](https://user-images.githubusercontent.com/15824252/82395178-f5aefd00-9a18-11ea-8cc9-217b8f5f6024.png)


### After analysis:
#### Chemotherapy
The chemo file from `all download` has 45 rows; this is double the expected 23 (23*2-1 bc only 1 header)
![image](https://user-images.githubusercontent.com/15824252/82395170-f0ea4900-9a18-11ea-903e-cd7c75e4721b.png)

#### Hormone Therapy
Also has double the number of rows; each row is duplicated on export
#### Primary Diagnosis
`number_of_lymph_nodes` field values that were submitted as 0 were not exported
![image](https://user-images.githubusercontent.com/15824252/82395853-66a2e480-9a1a-11ea-8360-a2bf515930f0.png)

#### Radiation 
Also has double the number of rows; each row is duplicated on export

**Comment by rosibaj** [comment]
@jaserud moving back to in progress until these issues can be resolved

**Comment by jaserud** [comment]
@rosi the tsv export is literally one to one what is in the donor. So, I took a look at the donor shape in clinical and it looks like there is a bug. The donor actually seems to have duplicate therapy info. E.g. donor dash-4 in DASH-CA has duplicate chemo-therapies:

These exsist under a treatment (this is the expected behavior)
![image](https://user-images.githubusercontent.com/34698315/82450552-d47ef880-9a7a-11ea-89b7-ea18b27c5c9a.png)

These exsist here too, under no treatment (not expected behavior)
![image](https://user-images.githubusercontent.com/34698315/82450674-02643d00-9a7b-11ea-8ce4-8041e263f9c5.png)

This is happening for radiation/hormone-therapy because they are stored the same. I don't know if this was always their or if this is a new bug. I'll take a look none the less.

**Comment by rosibaj** [comment]
@jaserud i think as you pointed out, this is a data-discrepancy issue from QA (i.e clearing data etc).  I retested with these steps:

- cleared donors from dc
- cleared all submissions (blank slate)
- registered donors
- uploaded clinical data
- sucessfull committed all data
- clicked download all button
- extracted files.  did not open files in a text editor. 
- reuploaded files.  This time, only one file did not work:

![image](https://user-images.githubusercontent.com/15824252/82583615-416cbe00-9b61-11ea-84f2-0b386453fcbb.png)

It looks like teh 0 is still not being returned correctly on `primary_diagnosis`

**Comment by rosibaj** [comment]
tested on QA: 
![image](https://user-images.githubusercontent.com/15824252/82609637-e354d080-9b8a-11ea-94fb-e688af4f536d.png)

No remaining issues observed!  Thanks so much for the changes @jaserud !!
