### ISSUE TITLE
🐛 Migration des not catch small number differences in version correctly 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#494]
## Describe the bug
When provided with an "incorrect" version, the dictionary migration ran indefinitley rather than returning an error. 
Example of bad request:
```
curl --location --request POST 'https://clinical.qa.argo.cancercollaboratory.org/submission/schema/dry-run-update' \
--header 'Authorization: Bearer <token>' \
--header 'Content-Type: application/json' \
--data-raw '{
  "version": "43.00"
}'
```
In fact, the dictionary has version 43.0.  

## Expected behaviour
- dry run should report this correctly as version not existing 
- when you get the 404 from lectern, it should abort the migration (rather than staying open)
- it should not return a migration response

**Comment by rosibaj** [comment]
Tested July 28, 2020

1. made a new dictionary 70.1 
2. did a dr-run migration with 70.1 (`5f20364831ecc90008f57121`).  This was successful
3. Did a dry-run migration with a bad id `70.11`. I got this error: 
![image](https://user-images.githubusercontent.com/15824252/88681954-1b631d00-d0c0-11ea-898d-4b4cac251cea.png)
This looked like it was saying that it could not be found. 
> note: A better error would be `This version does not exist`
4. Since it looked like the dry-run did not accept a bad id, i used the /migration endpoint to tests a migration with the same bad id. When this was done, it said i had a migration in progress already. 
![image](https://user-images.githubusercontent.com/15824252/88682144-57967d80-d0c0-11ea-9fe9-8309f6ad50cf.png)

This was concerning, as I did not have a migration started! 
5.  I looked up the current migration and see this: 
```    {
        "invalidDonorsErrors": [],
        "invalidSubmissions": [],
        "checkedSubmissions": [],
        "programsWithDonorUpdates": [],
        "_id": "5f203675356a250007127c25",
        "fromVersion": "64.5",
        "toVersion": "70.11",
        "stage": "SUBMITTED",
        "state": "OPEN",
        "createdBy": "Rosi Bajari",
        "analysis": null,
        "dryRun": true,
        "stats": {
            "invalidDocumentsCount": 0,
            "totalProcessed": 0,
            "validDocumentsCount": 0
        },
        "createdAt": "2020-07-28T14:30:13.873Z",
        "updatedAt": "2020-07-28T14:30:13.873Z",
        "__v": 0
    }
]
```
It looks like the dryrun that i thought rejected the bad version actually is still open, and is now blocking me from doing any migrations. 

## Expected behaviour 
- the dry-run should reject a version that does not exist, not leave a migration open that blocks other migrations 
- the migration endpoint should also reject a version that does not exist 
- the error on a bad version should be more understandable.

**Comment by rosibaj** [comment]
retested on QA after deploy - no issues.  thanks @Buwujiu !!

**Comment by Buwujiu** [comment]
thanks @rosibaj !
