### ISSUE TITLE
🐛 Fields should trim whitespace so that they can match enums 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#498]
To reproduce, put a space at the end of  valid drug name.  It will give you the error that it does not match. 

![image](https://user-images.githubusercontent.com/15824252/82004473-fd455f00-9630-11ea-9065-
b09acbe50412.png)

# Expected Behaviour
whitespaces at the end of submitted fields are trimmed so that only the values are submitted. for validation.

**Comment by blabadi** [comment]
implemented in #503

**Comment by rosibaj** [comment]
to be tested when https://github.com/icgc-argo/argo-clinical/issues/460 is tested

**Comment by rosibaj** [comment]
- tested on qa
- tested with this chemotherapy file
```
program_id	submitter_donor_id	submitter_treatment_id	drug_rxnormcui	drug_name	chemotherapy_dosage_units	cumulative_drug_dosage
DASH-CA	DASH-10	dashtr10-3	194000	capecitabine	mg/m2	5
DASH-CA	DASH-10	dashtr10-3	32592	oxaliplatin	mg/m2	2
DASH-CA	DASH-10	dashtr10-3	6313	leucovorin    	g/m2	8
DASH-CA	DASH-10	dashtr10-3	4492	     fluorouracil	mg/m2	1
````

results: 
- was able to successfully upload a drug name with leading and trailing whitespace with no error
- got the correct errors when either id/drug name was mutated

lgtm thanks @blabadi !!!
