### ISSUE TITLE
🐛 Double errors for emtpy ID field: not unique and required 

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/argo-clinical#510]
## Describe the bug

if a required id field is empty it shows double errors that it's not unique and required 
![image](https://user-images.githubusercontent.com/8655252/82565466-7a4c6900-9b48-11ea-8f4a-947be62d065b.png)

## Steps To Reproduce

Steps to reproduce the behaviour:
upload file with emtpy submitter Id in multiple rows 

## Expected behaviour
only required error is shown, no need for unique errors if empty

**Comment by rosibaj** [comment]
tested on QA with dictionary 49.0
tested be removing various required ids from a follow-up file

sucessfully only saw the required field error, not a unique error as well.
