### ISSUE TITLE
🐛 Unfortunate Excel bug: puts quotation marks on array values

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-clinical#514]
## Describe the bug
When I fill out presenting_symptoms in the Primary Diagnosis file using commas, and save, Excel puts quotation marks around the value. So I get this error:
<img width="1204" alt="Screen Shot 2020-05-21 at 9 19 21 AM" src="https://user-images.githubusercontent.com/18424138/82586497-a5918100-9b65-11ea-8a62-b0da88f23284.png">

From Jaser: commas need to be delimited in excel because they are saved as csv by excel (comma separated value)

## Expected behaviour
The clinical import shoudl remove ay leading/training `"` double quotations from a value in the TSV. so if a file has "value" we will save it as value

**Comment by blabadi** [comment]
Based on this I'd say excel is a bad choice to use for editing TSVs
https://superuser.com/questions/336084/preventing-quotes-from-being-used-around-text-when-exporting-to-tsv

**Comment by kcullion** [comment]
@christinayung @rosibaj maybe we can discuss this at some point. Not sure what's best here
1. Tell submitters not to use excel 
or 
2. Explain in the documentation what to do when using characters that excel does their thing with.
or
2. In this specific case, it would work in excel to use semicolons instead of commas to separate list/array items. When I save as a tsv, excel doesn't put quotations around a semicolon-separated list.

**Comment by blabadi** [comment]
@kcullion  there is a missed 3rd option
3. we implement the logic to remove any starting & trailing double quotations from a value in the TSV

so if a file has  `"value"` we will save it as `value`

**Comment by rosibaj** [comment]
@blabadi we will never include `"` as part of the actual values, so right now i dont see any issue with that!

**Comment by blabadi** [comment]
that said, this a bug in excel, because they follow the CSV RFC: https://tools.ietf.org/html/rfc4180 for TSV which is absurd

**Comment by kcullion** [comment]
@rosibaj for extended fields - it's pretty free in what they enter right? like can't they say 
value = "I don't know, what this field is"

**Comment by blabadi** [comment]
@kcullion yes, we need to provide an escape character for them to be able to do so
for example only say it will be `\` 

`\"I want this as is \"`

**Comment by rosibaj** [comment]
Comments:

- the only field at risk for said actino is this: "laterality_of_prior_malignancy"
- all other fields have a codelist, or will be getting one soon
- we should not allow said action. quotation marks shoudl not be included in submitted data.  So we dont need to include escape characters

**Comment by rosibaj** [comment]
> Based on this I'd say excel is a bad choice to use for editing TSVs
> https://superuser.com/questions/336084/preventing-quotes-from-being-used-around-text-when-exporting-to-tsv

Unfortunately, i don't think we can make this assumption.  We know that clinical submitters will be using this technology.

**Comment by kcullion** [comment]
So it seems maybe this is the winning option so far?

3. we implement the logic to remove any starting & trailing double quotations from a value in the TSV. so if a file has "value" we will save it as value

**Comment by rosibaj** [comment]
Description updated

**Comment by kcullion** [comment]
@rosibaj did we say we would include an example for this? like say 
To include multiple values, please separate values with a comma ',' within your file. For example: Anemia, Back Pain, Fatigue.

**Comment by rosibaj** [comment]
There is a dictionary ticket for that

**Comment by rosibaj** [comment]
that is not in scope for this ticket

**Comment by kcullion** [comment]
sorry, got confused with your comment on this ticket saying you updated the description

**Comment by jaserud** [comment]
With Kim's help, discovered some more cases where this occurs:
```
Methylcellulose "450" 500 mg oral tablet -> "Methylcellulose ""450"" 500 mg oral tablet"
transparent dressing 4 3/8" X 5" TOPICAL BANDAGE -> "transparent dressing 4 3/8"" X 5"" TOPICAL BANDAGE"
Health Care America Insulin Syringe 29gx1/2" -> "Health Care America Insulin Syringe 29gx1/2"""
```
I have accounted for these as well.

**Comment by kcullion** [comment]
@rosibaj did a little test with the new way of pipe delimiting 
in excel:
<img width="562" alt="Screen Shot 2020-06-01 at 1 57 46 PM" src="https://user-images.githubusercontent.com/18424138/83438712-e57f2080-a40f-11ea-9be7-ce690f4c5e92.png">

In platform:
<img width="619" alt="Screen Shot 2020-06-01 at 1 49 13 PM" src="https://user-images.githubusercontent.com/18424138/83438695-d9935e80-a40f-11ea-9371-4fb6b037e182.png">

And I am able to sign off this submission. Looks good to me!
