### ISSUE TITLE
Use Pipe as array delimiter instead of comma

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/argo-clinical#526]
## Possible Implementation

switch splitting tsv arrays based on  `|` instead of `,`

**Comment by rosibaj** [comment]
tested form ui by @kcullion

**Comment by rosibaj** [comment]
tested on QA with dictionary 49.0 

- pipe worked
- spaces and quotes were stripped correctly

**Comment by blabadi** [comment]
@rosibaj  if `1.27.0` is ok, you can move this and unblock it along with that ticket
