### ISSUE TITLE
Move lectern client to lectern and import as npm package

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/argo-clinical#527]
lectern client was designed to be generic and reusable, it's time to move it out of clinical and treat it as so

note that it does use some util functions so these need to be copied there too.

**Comment by blabadi** [comment]
there is no change in functionality. clinical now uses: https://github.com/overture-stack/js-lectern-client :tada:

**Comment by andricDu** [comment]
Released and tested in prod.
