### ISSUE TITLE
Feature Request: Update `central_pathology_confirmed` validation rule based on dictionary changes

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#531]
https://github.com/icgc-argo/argo-dictionary/issues/109 

- The name of the field `central_pathology_confirmed` has been changed to `reference_pathology_confirmed`. 
- This field `was not` indicated as a validation dependency in the meta, even though it should have been. This has been recitifed in this currently DRAFT pr (https://github.com/icgc-argo/argo-dictionary/pull/158)

Can we please update the clinical validation to the new field name so that we can complete a dictionary migration?

**Comment by rosibaj** [comment]
tested on QA with dictinoary 49.00
- was able to migrate the dictionary with the field name (same with 48.2)
- `application form`--> `radiation therapy type` worked fine and i was able to upload the radiation therapy file 

I am not sure if https://github.com/icgc-argo/argo-clinical/issues/545 is related to the  reference_pathology_confirmed validation, but i dont think the validation is working: 

![image](https://user-images.githubusercontent.com/15824252/83468615-52fc7280-a44b-11ea-92b9-548c2e92ce7d.png)

**Comment by blabadi** [comment]
#545 is not related to this.

I'm not clear if this passed QA or not, so would please confirm and update based on the statement above

**Comment by rosibaj** [comment]
Tested on qa and dont get errors when submitting the new `reference_pathology field`

Waiting on a dictioanry rc for release
