### ISSUE TITLE
Update treament validation to use treatement_type as an array

### ISSUE THREAD

**Issue by jaserud** [icgc-argo/argo-clinical#557]
Changes needed in clinical in relation to this dictionary update: https://github.com/icgc-argo/argo-dictionary/issues/143

## Detailed Description
Clinical currently expects treatment_type to be a value from a codelist and uses that to verify if certain therapy files (chemo, radiation, & hormone) are needed for a donor, Need to update this so it looks at treatment type as an array of values 

## Possible Implementation

**Comment by rosibaj** [comment]
I tested this on QA
- my old "combined" valued were not accepted
- I had to pipe delimit an array of values ( which were checked against the codelist correctly)
- When i submitted multiple treatment_types, I was required to submit the corresponding files
- when i submitted multiple treatment_types, and the matching treatment type records already existed, i was not prompted to upload more files. 

This worked really well! Thanks @jaserud !

**Comment by blabadi** [comment]
related dictionary version is `0.15`
