### ISSUE TITLE
Test DB Migration with Dictionary tickets in QA 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#573]
- [ ] Create a branch with the latest dictionary changes
- [ ] Write a data migration based on the proved mapping 
```
DETAILS HERE
```
- [ ] Test the migration in QA

- expectation is that there are part of the clinical codebase (similar to flyway; is migrate-mongo ) 

## Expected Outcome
- Merged PR with migration included  
- donor in QA are migrated, not invalidated on dictionary update 
- update wiki page with established process for data migrations to production in the SOP

**Comment by hknahal** [comment]
Data mapping for dictionary changes:

| Original field name | New field name(s) |
|------------ | -----------|
| `therapeutic_intent` | `treatment_setting` and `treatment_intent` |
| `response_to_therapy` | `response_to_treatment` |
| `outcome_of_therapy` | `outcome_of_treatment` |


Controlled terminology mapping for `therapeutic_intent` and new fields `treatment_setting` & `treatment_intent`:

| codelist for `therapeutic_intent`  | codelist for `treatment_setting` | codelist for `treatment_intent` |
| ------------- | ------------- | ------------- |
|Adjuvant|Adjuvant||
|Concurrent| (should be invalid) | (should be invalid) |
|Curative||Curative|
|Neoadjuvant|Neoadjuvant||
|Not applicable|Not applicable||
|Palliative||Palliative|
|Unknown||Unknown|
||Advanced/Metastatic||

References:
Original Issue: https://github.com/icgc-argo/argo-dictionary/issues/199
PR: https://github.com/icgc-argo/argo-dictionary/pull/203

**Comment by rosibaj** [comment]
- Discussed on Monday the 27th 
- Migrations should only be done on data that results in at least _some_ valid document.
- If there is a migration that does not help some users maintain valid data, then we can skip that as a migration and let users update all associated field(s)

@blabadi i think you said you had the migration for the renamed fields already done?  Can we move this ticket forward?

**Comment by blabadi** [comment]
based on the discussion outcomes above, the automatic migration will handle the split of the field 
as for the therapy -> treatment rename clinical has a mongo script now to migrate the data.
