### ISSUE TITLE
🐛 datawarnings has array of nulls, when it should be empty

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/argo-clinical#590]
## Describe the bug
A null array of warnings is being provided.  This is confusing. 
## Steps To Reproduce

Steps to reproduce the behaviour:
1. upload treatment + therapy
2. validate submission
3. check response in the therapy, it has array of null data warnnings
 
I also see this: 
![image](https://user-images.githubusercontent.com/15824252/88840651-cd771380-d1aa-11ea-8a8b-d09b44c844ee.png)

## Expected behaviour
If there are no warnings, there should not be a null array.

**Comment by rosibaj** [comment]
lgtm on QA Aug 12 2020 

- verified with program DASH-CA changing a radiation therapy record to chemotherapy 
- no array of nulls is observed any longer in the response in postman
