### ISSUE TITLE
Issue Kafka event from clinical to file-manager

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#601]
- When clinical data is updated, clinical will issue an event via kafka to file-manager
- Event will contain
  - Study ID
  - Donor ID
- Clinical Program Update already exists, potentially this can be updated to include the above data in the event. 
  - Evaluate whether we can add to the existing event or create a new one.

**Comment by b-f-chan** [comment]
Timebox to end of this week, then transition to HCMI start of Week of Apr 25

**Comment by b-f-chan** [comment]
@mistryrn to complete before moving onto new HCMI maintenance contract work week of Apr 25

**Comment by b-f-chan** [comment]
@mistryrn any update on status as requested?  Do I need to assign to Jon?

**Comment by mistryrn** [comment]
@joneubank cleaned up what I had in progress for this, there's two open PRs related to it:

1. https://github.com/icgc-argo/donor-submission-aggregator/pull/270 -- ensures sure the changes from this ticket don't break anything in donor-submission-aggregator (the only other service that consumes the update message)
2. https://github.com/icgc-argo/argo-clinical/pull/769 -- the actual argo-clinical changes for this ticket

Need to test the argo-clinical changes still, and there are a couple items in the PR checklist that I hadn't gotten around to yet either like checking swagger if docs need updating. The bulk of the work is done, just needs a little push to get it across the finish line.

**Comment by b-f-chan** [comment]
@joneubank will takeover & complete from @mistryrn
