### ISSUE TITLE
Investigate AJCC API Automation for Validation 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#610]
https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Validating+AJCC-related+fields

- How can clinical check this information? 
- Is there an offline version of this to use? If not, what is the rate-limit? 
- Is it worth us getting a subscription? 

## Expected Outcome 
- Decide whether or not we can use the AJCC API Validation with Clinical.  
- Make a set of tickets to implement the AJCC API Validation if so. If not, make a follow-up ticket to investigate alternate means.

**Comment by blabadi** [comment]
left comments on wiki

**Comment by rosibaj** [comment]
- @rosibaj followup with next tickets for caching solution
- verify no minor versions
