### ISSUE TITLE
🐛 Clinical validation fails on basic validation checks (id/cross file id checks)

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-clinical#641]
## Describe the bug
The submission fails to validate if it contains only the donor.tsv and specimen.tsv files. When the primary_diagnosis.tsv file is uploaded as well, the validation proceeds.

## Steps To Reproduce

1. Go to https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/HNAHAL-CA/clinical-submission?tab=donor It currently contains just the uploaded `donor` and `specimen` clinical data.
2. Click on `Validate Submission`. You will get a `Something went wrong` error message:
![error](https://user-images.githubusercontent.com/4992044/109211366-1fe9d400-777c-11eb-97a2-73b8b9259869.png)

3. If you upload the primary_diagnosis.tsv file (below), you will be able to click on `Validate Submission`.
```
program_id      submitter_donor_id      submitter_primary_diagnosis_id  age_at_diagnosis        cancer_type_code        cancer_type_additional_information      basis_of_diagnosis      number_lymph_nodes_positive     number_lymph_nodes_examined     clinical_tumour_staging_system  clinical_t_category     clinical_n_category     clinical_m_category     clinical_stage_group    presenting_symptoms     performance_status
HNAHAL-CA       DASH-1  dashpd-1        51      C71.1           Clinical        32              Ann Arbor staging system                                Stage I         Grade 1
HNAHAL-CA       DASH-10 dashpd-10       34      C18.9                   8               AJCC 8th edition        T1      N0      M0      Stage IV        Nausea|Anemia   Grade 1
HNAHAL-CA       DASH-10 dashpd-10.1     34      C44.9                   7               AJCC 8th edition        T0      N0      M0      Stage I Nausea  Grade 1
HNAHAL-CA       DASH-2  dashpd-2        53      C25.1           Histology of a primary tumour   34              AJCC 8th edition        T1      N0      M0      Stage II                Grade 0
HNAHAL-CA       DASH-3  dashpd-3        28      C15.2                   54              AJCC 8th edition        T2      N0      M0      Stage II                Grade 0
HNAHAL-CA       DASH-4  dashpd-4        19      C15.5                   34              AJCC 8th edition        T4a     N1      M1      Stage II                Grade 1
HNAHAL-CA       DASH-5  dashpd-5        20      C25.1                   32                                                              Grade 0
HNAHAL-CA       DASH-6  dashpd-6        63      C25.1           Specific tumour markers 2               AJCC 8th edition        T1      N1      M0      Stage II                Grade 0
HNAHAL-CA       DASH-7  dashpd-7        56      C25.2           Specific tumour markers 4               AJCC 8th edition        T1      N2      M0      Stage III               Grade 0
HNAHAL-CA       DASH-8  dashpd-8        68      C25.9           Histology of a primary tumour   23              Ann Arbor staging system                                Stage I         Grade 0
HNAHAL-CA       DASH-9  dashpd-9        37      C18.4                   6               AJCC 8th edition        T2      N0      M0      Stage IB        Nausea  Grade 0
HNAHAL-CA       DASH-11 dashpd-11       45      C25.1           Histology of a primary tumour   5       10      Ann Arbor staging system                                Stage I         Grade 1
```

## Expected behaviour
Expected system to validate donor and specimen files alone without the primary_diagnosis.tsv file. The error message should be more clear as well.

**Comment by rosibaj** [comment]
Failed to replicate this big, however, it is now replicatable:

Example: 
1. Go to https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/DASH-CA/clinical-submission?tab=primary_diagnosis: 
2. Click Validate. 

These were the files used: 
[primary_diagnosis.txt](https://github.com/icgc-argo/argo-clinical/files/6149981/primary_diagnosis.txt)
[sample_registration.txt](https://github.com/icgc-argo/argo-clinical/files/6149982/sample_registration.txt)
[specimen.txt](https://github.com/icgc-argo/argo-clinical/files/6149983/specimen.txt)

**Comment by rosibaj** [comment]
Second replication: 

[sample_registration.txt](https://github.com/icgc-argo/argo-clinical/files/6150411/sample_registration.txt)
[specimen.txt](https://github.com/icgc-argo/argo-clinical/files/6150412/specimen.txt)


## Expected Behaviour 

This specimen file has 2 values `dashsp14` and `dashsp14.1`, but only 1 specimen `dashsp14.1` is registered: 
```
program_id	submitter_donor_id	submitter_specimen_id	submitter_primary_diagnosis_id	pathological_tumour_staging_system	pathological_t_category	pathological_n_category	pathological_m_category	pathological_stage_group	specimen_acquisition_interval	tumour_histological_type	specimen_anatomic_location	specimen_processing	specimen_storage	reference_pathology_confirmed	tumour_grading_system	tumour_grade	percent_tumour_cells	percent_proliferating_cells	percent_inflammatory_tissue	percent_stromal_cells	percent_necrosis
MINHDASH-CA	DASH-14	dashsp-14	dashpd-1						4		C42.0
```

Error No. 12 `ID_NOT_REGISTERED` on this reference table  (https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Clinical+Submission+Validation+Errors ) should be activated, but instead we get this: 

![image](https://user-images.githubusercontent.com/15824252/111340468-0935ef00-864f-11eb-8ec6-1dd7ceed40c1.png)

**Comment by Buwujiu** [comment]
> Second replication:
> 
> [sample_registration.txt](https://github.com/icgc-argo/argo-clinical/files/6150411/sample_registration.txt)
> [specimen.txt](https://github.com/icgc-argo/argo-clinical/files/6150412/specimen.txt)
> 
> ## Expected Behaviour
> This specimen file has 2 values `dashsp14` and `dashsp14.1`, but only 1 specimen `dashsp14.1` is registered:
> 
> ```
> program_id	submitter_donor_id	submitter_specimen_id	submitter_primary_diagnosis_id	pathological_tumour_staging_system	pathological_t_category	pathological_n_category	pathological_m_category	pathological_stage_group	specimen_acquisition_interval	tumour_histological_type	specimen_anatomic_location	specimen_processing	specimen_storage	reference_pathology_confirmed	tumour_grading_system	tumour_grade	percent_tumour_cells	percent_proliferating_cells	percent_inflammatory_tissue	percent_stromal_cells	percent_necrosis
> MINHDASH-CA	DASH-14	dashsp-14	dashpd-1						4		C42.0
> ```
> 
> Error No. 12 `ID_NOT_REGISTERED` on this reference table (https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Clinical+Submission+Validation+Errors ) should be activated, but instead we get this:
> 
> ![image](https://user-images.githubusercontent.com/15824252/111340468-0935ef00-864f-11eb-8ec6-1dd7ceed40c1.png)


@rosibaj Could you please verify if this is the expected error: 
```
 "dataErrors": [
                    {
                        "type": "ID_NOT_REGISTERED",
                        "fieldName": "submitter_specimen_id",
                        "index": 0,
                        "info": {
                            "donorSubmitterId": "DASH-14",
                            "value": "dashsp-14"
                        },
                        "message": "dashsp-14 has not yet been registered. Please register samples before submitting clinical data for this identifier."
                    },
                    {
                        "type": "RELATED_ENTITY_MISSING_OR_CONFLICTING",
                        "fieldName": "submitter_primary_diagnosis_id",
                        "index": 1,
                        "info": {
                            "fieldName": "submitter_primary_diagnosis_id",
                            "childEntity": "specimen",
                            "parentEntity": "primary_diagnosis",
                            "donorSubmitterId": "DASH-14",
                            "value": "dashpd-1"
                        },
                        "message": "[submitter_primary_diagnosis_id] value in [specimen] file requires a matching [submitter_primary_diagnosis_id] in [primary_diagnosis] data. Check that it belongs to the same [submitter_donor_id] = DASH-14. It could have been previously submitted for a different donor, or if it's new in this submission, it's either missing in [primary_diagnosis] file or this [submitter_primary_diagnosis_id] is associated with different [submitter_donor_id] in the [primary_diagnosis] file."
                    },
                    {
                        "type": "NOT_ENOUGH_INFO_TO_VALIDATE",
                        "fieldName": "specimen_acquisition_interval",
                        "index": 1,
                        "info": {
                            "missingField": [
                                "donor.vital_status",
                                "donor.survival_time"
                            ],
                            "donorSubmitterId": "DASH-14",
                            "value": 4
                        },
                        "message": "[specimen_acquisition_interval] requires [donor.vital_status], [donor.survival_time] in order to complete validation.  Please upload data for all fields in this clinical data submission."
                    }
                ],```

**Comment by rosibaj** [comment]
@Buwujiu , it would be great if you could understand these errors as well since you will be working in the clinical system.  Hopefully, the error messages make sense in the scope of the data.  Can you perhaps reason out if this makes sense based on your submitted data? 
- Do these look like errors that make sense based on the data you have submitted?
- If the errors are being reported correctly, why is the front-end saying something went wrong?

**Comment by rosibaj** [comment]
Tested April 06, 2021. 
- with the provided test files, i was not able to replicate the error.  I received the expected errors. 
- tested extensively with new data files and always received the expected errors.

**Comment by rosibaj** [comment]
LGTM thanks @Buwujiu !
