### ISSUE TITLE
Feature Request: Allow Dictionary Migration of `integer` to `number`

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#644]
## Detailed Description
A dictionary change is rejected as a breaking change if a a field type is changed from  `integer` to `number`

Example: 
Migrate: to dictionary version 80.5 in the ARGO QA Environment: 

```
    {
        "_id": "604bf2c33811dc001ea01bb1",
        "name": "ICGC-ARGO Data Dictionary",
        "version": "80.5"
    },
```

There is a `migration manager` in the code that handles these rules that can be edited. 

## Expected Behaviour

This should be allowed as all numbers are integers, thus no data would be broke. It is making a field more permissive, not less permissive.

**Comment by rosibaj** [comment]
tested with several dictionary migrations in the sprint including int --> number

**Comment by blabadi** [comment]
deployed to staging

**Comment by rosibaj** [comment]
Confirmed on Ulyssus Release May 10, 2021
