### ISSUE TITLE
Implement the Endpoint to Upload a Specimen File 

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/argo-clinical#68]
**PUT /submission/programs/{programId}/specimen**

- [ ] Upload the TSV
- [ ] Get the Specimen schema
- [ ] Call schema validation and collect errors, if any
- [ ] If validation passes, save to the staging collection
- [ ] Write the endpoint to get donors from the staging collection (does this belong here)
- [ ] Write the data validation logic for donors (does this belong here)
- [ ] Add swagger 
- [ ] Add tests

The sequence diagrams for clinical submissions can be found here : https://wiki.oicr.on.ca/display/icgcargotech/Technical+Architecture.

**Comment by rosibaj** [comment]
Closing as this is already completed
