### ISSUE TITLE
🐛 Missing check on interval_of_followup and treatment_start_interval  value against survival_time

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-clinical#682]
## Describe the bug
If `survival_time` field is submitted, then all interval fields should be less than `survival_time` which is the clinical endpoint. Currently there is a check on `specimen_acquisition_interval` and `survival_time` but a similar check is missing for the `treatment_start_interval` and `interval_of_followup` fields. If `survival_time` is submitted, both should be less than `survival_time`

## Steps To Reproduce
Upload `donor` file with `survival_time` = 32
Upload `treatment` file with `treatment_start_interval` = 56
Upload `followup` file with `interval_of_followup` = 92

Click `Validate Submission`. Files will pass validation without generating an error:
`survival_time` field for submitter_donor_id "DASH-7" in donor file is 32:

![survival_time](https://user-images.githubusercontent.com/4992044/117496219-bab51a80-af44-11eb-9bbc-4e5e2bc157c7.png)

`interval_of_followup` values for submitter_donor_id "DASH-7" are all greater than the `survival_time` (32) but there is no error generated:
![followup](https://user-images.githubusercontent.com/4992044/117496212-b7219380-af44-11eb-871f-c0c35988ff8d.png)

`treatment_start_interval` values for submitter_donor_id "DASH-7" are all greater than the `survival_time (32) but there is no error generated:
![treatment](https://user-images.githubusercontent.com/4992044/117496216-b8eb5700-af44-11eb-8f33-29cb55f86cfd.png)

## Expected behaviour
An error should be generated as follows:
"interval_of_followup cannot be greater than the Donor survival_time"
"treatment_start_interval cannot be greater than the Donor survival time"

**Comment by rosibaj** [comment]
@hknahal just to confirm, is it ok  to have an interval of followup POST death (i.e did we remove the restriction that a follow-up can be > survival time if it is a record of the patients death)?

**Comment by hknahal** [comment]
@rosibaj If a medical record with follow up data is found post-death, then the `interval_of_followup` should equal the `survival_time`. If the patient is alive, `interval_of_followup` is calculated using the last date they were seen alive. If we were to allow the `interval_of_followup` to be the date when the medical record was found after the patient died, then it would be be greater than the `survival_time` which makes the clinical data confusing (we had this issue in ICGC clinical data) because it doesn't have any relevance to the patient's disease. The `age_at_diagnosis` is the reference timepoint (ie. used to calculate all the time intervals), and death (`survival_time`) is treated as the clinical endpoint. That way we can ensure all the time interval fields make sense.

**Comment by rosibaj** [comment]
- tested followup.interval_of_followup.  was not allowed to submit data that was > survival time.
- tested treatment.treatment_start_interval was not allowed to submit data that was > survival time. 

I did notice that these errors are reported in a slightly different format.  
![image](https://user-images.githubusercontent.com/15824252/123318012-be086380-d4fc-11eb-88ba-7ae2c7640a28.png)


@Buwujiu Can you please update the format of the error reporting to be consistent and look like this:

```
The treatment_start_interval should be less than Donor survival_time.
The interval_of_followup cannot be greater than the Donor survival time"
```

**Comment by Buwujiu** [comment]
@rosibaj I updated all 4 error messages to be more consistent, here is what they look like currently in dev:
![Screen Shot 2021-06-29 at 12.24.11 PM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/2ccbc5f6-3fe8-4693-a40a-fba9e0cf787d)

**Comment by rosibaj** [comment]
looks good thanks @Buwujiu !
