### ISSUE TITLE
Feature Request: Add surgery back to clinical 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#727]
RE: https://github.com/icgc-argo/argo-clinical/pull/725 

surgery was commented out for release
it can be added back now

**Comment by b-f-chan** [comment]
@blabadi - To investigate offline if blocked

**Comment by blabadi** [comment]
This ticket is blocked, because it needs the surgery schema to be published in dictionary, otherwise will error out upon migration and version 1.14 of dictionary is not ready yet as discussed on slack.

**Comment by b-f-chan** [comment]
Target this for K release, June 2-16 sprint, to support dictionary release 1.14

**Comment by b-f-chan** [comment]
Close as duplicate, @Buwujiu will handle within the Surgery Schema PR
