### ISSUE TITLE
Update Surgery schema validation to allow combination of submitter donor_id, specimen_id and treatment_id once per file

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-clinical#738]
## Description
The current validation for the surgery schema allows the combination of `submitter_donor_id` and `submitter_treatment_id` to be submitted only once per file. However, there is a use case (described [here](https://github.com/icgc-argo/argo-dictionary/pull/334#issuecomment-933677302) - see "Example 1") where `submitter_donor_id` and `submitter_treatment_id` can be submitted more than once per file if the `submitter_specimen_id` is unique in the multiple entries. The current validation prevents this from being validated correctly. If `submitter_specimen_id` is submitted (it is an optional field), then we should allow the combination of [`submitter_donor_id`, `submitter_specimen_id`, `submitter_treatment_id`] to be submitted only once per file, instead of just [`submitter_donor_id`, `submitter_treatment_id`]. The `surgery_type` field would need to be consistent too. If however the `submitter_specimen_id` is not submitted, then the combination of [`submitter_donor_id`, `submitter_treatment_id`] can only be submitted once per file.

**Example Surgery clinical submission**

For an explanation of the use case that was tested, please refer to comment [here](https://github.com/icgc-argo/argo-dictionary/pull/334#issuecomment-933677302).
- `submitter_donor_id` and `submitter_treatment_id` are submitted more than once in the file. But the `submitter_specimen_id` is unique in each entry. This should pass validation but currently fails:

| submitter_donor_id | submitter_specimen_id | submitter_treatment_id | surgery_type |
|-|-|-|-|
| Pat_2 | Sp_32 | Tr-2 | Gastric Antrectomy |
| Pat_2 | Sp_34 | Tr-2 | Gastric Antrectomy |

## Steps to Reproduce
Upload following example clinical submission files (will need to change program code):
[sample_registration.txt](https://github.com/icgc-argo/argo-clinical/files/7289181/sample_registration.txt)
[donor.txt](https://github.com/icgc-argo/argo-clinical/files/7289178/donor.txt)
[specimen.txt](https://github.com/icgc-argo/argo-clinical/files/7289182/specimen.txt)
[primary_diagnosis.txt](https://github.com/icgc-argo/argo-clinical/files/7289180/primary_diagnosis.txt)
[treatment.txt](https://github.com/icgc-argo/argo-clinical/files/7289184/treatment.txt)
[follow_up.txt](https://github.com/icgc-argo/argo-clinical/files/7289179/follow_up.txt)
[chemotherapy.txt](https://github.com/icgc-argo/argo-clinical/files/7289177/chemotherapy.txt)
[surgery_example1.txt](https://github.com/icgc-argo/argo-clinical/files/7289183/surgery_example1.txt)

**Validation result:**
![surgery_example1_validation](https://user-images.githubusercontent.com/4992044/136099743-dcd3b290-b2e2-469d-8965-04ca5da40e08.png)

## Expected behaviour:
- The above example should pass validation. In order to do so, the following would need to be implemented:

If `submitter_specimen_id` is submitted:
-  The combination of [`submitter_donor_id`, `submitter_specimen_id`, `submitter_treatment_id`] should only be submitted once per file. 
- The `surgery_type` field should have same value for the combination of [`submitter_donor_id`, `submitter_treatment_id`]. Using the example submission above, this means the `surgery_type` field in the two rows have to be the same (`Gastric Antrectomy`).

If `submitter_specimen_id` is not submitted: 
- The combination of [`submitter_donor_id`, `submitter_treatment_id`] should be submitted only once per file.

**Comment by hknahal** [comment]
@ciaranschutte @Buwujiu I added a few examples here and the expected validation (last row).

| Row | submitter_donor_id | submitter_specimen_id | submitter_treatment_id | surgery_type | Expected Validation |
| -- | -- | -- | -- | -- | --|
| 1 | Pat_2 | Sp_32 | Tr-2 | Gastric Antrectomy | This should validate. 
| 2 | Pat_2 | Sp_34 | Tr-2 | Gastric Antrectomy | Rows 1 & 2 should validate because the combination of `submitter_donor_id` ("Pat_2") and `submitter_treatment_id` ("Tr-2") are associated with the same `surgery_type` ("Gastric Antrectomy"), and two different `submitter_specimen_ids` are submitted in the two rows (since two specimens were taken out during the same surgical event).|
| 3 | Pat_2 | Sp_36 | Tr-2 | Lobectomy | This should invalidate because the combination of `submitter_donor_id` ("Pat_2") and `submitter_treatment_id` ("Tr-2") are already associated with the `surgery_type` "Gastric Antrectomy"). The data submitter can correct this if `submitter_treatment_id` is changed to "Tr-3", or if the `surgery_type` field in Rows 1 & 2 are changed to "Lobectomy". |
| 4 | Pat_2 | Sp_34 | Tr-4 | Gastric Antrectomy | This should invalidate because the `submitter_specimen_id` "Sp_34" was already taken out during a previous surgery (Row 2) |
| 5 | Pat_2 | | Tr-5 | Mastectomy | This should validate because the even though `submitter_specimen_id` is not submitted, the combination of `submitter_donor_id` ("Pat_2") and `submitter_treatment_id` "Tr-5" are associated with `surgery_type` "Mastectomy"

**Comment by hknahal** [comment]
Testing dictionary version `114.8` in QA

Test case 1: If the combination of [`submitter_donor_id` + `submitter_treatment_id`] is associated with more than one `surgery_type`, the validation should fail, but in QA it currently passes.

Validation Result:
The combination of `submitter_donor_id` "Pat-2" and `submitter_treatment_id` "Tr-2" should only be associated with one `surgery_type`, but it is associated with two here ("Gastric Antrectomy" and "Lobectomy") and should fail validation:

![surgery_example_3](https://user-images.githubusercontent.com/4992044/164331716-758d73e6-7259-42c5-886d-a7efd906a43b.png)

Expected error message: The combination of `submitter_donor_id` "Pat-2" and `submitter_treatment_id` "Tr-2" can only be associated with one `surgery_type`.



Test case 2: A `submitter_specimen_id` can only be submitted once in the Surgery schema. If it appears more than once, the validation should fail.

Validation Result:
The `submitter_specimen_id` "Sp-34" appears twice (implying the same specimen was resected twice during two different surgical procedures). This validation should fail, but it incorrectly passes validation because the specimen "Sp-34" was already taken out during treatment "Tr-2" and shouldn't appear again for treatment "Tr-4"

![surgery_example_4](https://user-images.githubusercontent.com/4992044/164467049-b39293c4-5e49-4850-aacd-ed90b072aedc.png)

Expected error message: The `submitter_specimen_id` "Sp-34" can only be submitted once.

**Comment by b-f-chan** [comment]
@ciaranschutte to make requested fixes as priority before returning to UI Kit work

**Comment by ciaranschutte** [comment]
status update. 

basic logic coded but running into some testing errors.
Can't get past submission_specimen_id being previously submitted, even though it has not.

![a](https://user-images.githubusercontent.com/1486054/166866136-7c3c007f-4940-435b-bb0b-435b0bd124f1.png)

cleaned up the code we worked on yesterday and PR open into Alexis work. 
https://github.com/icgc-argo/argo-clinical/pull/768

logic pre-cleanup : https://github.com/icgc-argo/argo-clinical/pull/768/commits/0859b0af706405f8952a324133ffee7007218b20

**Comment by b-f-chan** [comment]
@b-f-chan to followup with @ciaranschutte @Buwujiu to see the result of their meeting and who is best to complete remainder of the fixes.  Additionally, the fixes may need to be broken down into smaller tickets.

**Comment by b-f-chan** [comment]
As agreed offline with @ciaranschutte and @Buwujiu , re-assigning to @Buwujiu to complete with priority to unblock @hknahal, since @ciaranschutte is away next week

**Comment by Buwujiu** [comment]
Made a diagram of the complete validation process:
![Screen Shot 2022-05-25 at 12 21 44 PM](https://user-images.githubusercontent.com/8744047/170312046-eb53d783-1c95-40ac-a018-1cf4aec5c9f3.png)

**Comment by hknahal** [comment]
Sample registration file: [sample_registration.txt](https://github.com/icgc-argo/argo-clinical/files/8789781/sample_registration.txt)


**Test case 1:** A single specimen was resected during a surgical procedure. Submit combination of `submitter_donor_id`, `submitter_specimen_id`, `submitter_treatment_id` and `surgery_type` in one row.


Sample file
[donor.csv](https://github.com/icgc-argo/argo-clinical/files/8789822/donor.csv)
[specimen.csv](https://github.com/icgc-argo/argo-clinical/files/8789823/specimen.csv)
[primary_diagnosis.csv](https://github.com/icgc-argo/argo-clinical/files/8789824/primary_diagnosis.csv)
[treatment_example1.csv](https://github.com/icgc-argo/argo-clinical/files/8789825/treatment_example1.csv)
[surgery_example1-2.csv](https://github.com/icgc-argo/argo-clinical/files/8789826/surgery_example1-2.csv)

Expected validation: 
Should pass validation because the combination of `submitter_donor_id`, `submitter_specimen_id`, `submitter_treatment_id` and `surgery_type` is unique:

| Row | submitter_donor_id | submitter_specimen_id | submitter_treatment_id | surgery_type |
| -- | -- | -- | -- | -- |
| 1 | Pat_2 | Sp-32 | Tr-2 | Gastric Antrectomy |

Validation result:

Validates as expected:
![example1](https://user-images.githubusercontent.com/4992044/170781576-9a41e3d2-f0d1-4bf6-a8dd-bd5c8982a29b.png)


**Test case 2:** Two specimens were resected during the same surgical procedure. Submit the same combination of [`submitter_donor_id`, `submitter_treatment_id`, `surgery_type`] for two rows, each with a different `submitter_specimen_id`.

Sample Files:
[donor.csv](https://github.com/icgc-argo/argo-clinical/files/8789828/donor.csv)
[specimen.csv](https://github.com/icgc-argo/argo-clinical/files/8789829/specimen.csv)
[primary_diagnosis.csv](https://github.com/icgc-argo/argo-clinical/files/8789830/primary_diagnosis.csv)
[treatment_example2.csv](https://github.com/icgc-argo/argo-clinical/files/8789831/treatment_example2.csv)
[surgery_example2.csv](https://github.com/icgc-argo/argo-clinical/files/8789832/surgery_example2.csv)

Expected validation: 
Should pass validation because the combination of `submitter_donor_id` and `treatment_id` and `surgery_type` can be submitted twice, _provided_ the `submitter_specimen_id` is different.

| Row | submitter_donor_id | submitter_specimen_id | submitter_treatment_id | surgery_type |
| -- | -- | -- | -- | -- |
| 1 | Pat_2 | Sp-32 | Tr-2 | Gastric Antrectomy |
| 2 | Pat_2 | Sp-34 | Tr-2 | Gastric Antrectomy |

Validation result:

Validates as expected:
![example2](https://user-images.githubusercontent.com/4992044/170782812-d4559016-e023-4eef-aff1-a8d08015c12e.png)

**Test case 3:** A donor's `submitter_treatment_id` is associated with two different surgery types. Submit the same combination of [`submitter_donor_id`, `submitter_treatment_id`] for two rows, each with a different `surgery_type`.

Sample Files:
[donor.csv](https://github.com/icgc-argo/argo-clinical/files/8789834/donor.csv)
[specimen.csv](https://github.com/icgc-argo/argo-clinical/files/8789835/specimen.csv)
[primary_diagnosis.csv](https://github.com/icgc-argo/argo-clinical/files/8789836/primary_diagnosis.csv)
[treatment_example3.csv](https://github.com/icgc-argo/argo-clinical/files/8789837/treatment_example3.csv)
[surgery_example3.csv](https://github.com/icgc-argo/argo-clinical/files/8789838/surgery_example3.csv)

Expected validation: 
Should fail validation because the combination of `submitter_donor_id` and `submitter_treatment_id` should always associate with the _same_ `surgery_type`, but in this case, it is associated with two different `surgery_types`.

Validation result:
Fails validation as expected:
![example3](https://user-images.githubusercontent.com/4992044/170785835-f06f8417-4def-4ff5-a506-c7256a6ac8ae.png)

**Test case 4:** A `submitter_specimen_id` is submitted twice in the Surgery table. This should invalidate because a given specimen can only be re-sected once. Submit the same combination of [`submitter_donor_id`, `submitter_specimen_id`, `submitter_treatment_id`, `surgery_type`] for two rows.

Sample Files:
[donor.csv](https://github.com/icgc-argo/argo-clinical/files/8789813/donor.csv)
[specimen.csv](https://github.com/icgc-argo/argo-clinical/files/8789814/specimen.csv)
[primary_diagnosis.csv](https://github.com/icgc-argo/argo-clinical/files/8789815/primary_diagnosis.csv)
[treatment_example4.csv](https://github.com/icgc-argo/argo-clinical/files/8789816/treatment_example4.csv)
[surgery_example4.csv](https://github.com/icgc-argo/argo-clinical/files/8789818/surgery_example4.csv)


Expected validation: Should fail validation because the submitter_specimen_id "Sp-34" is submitted twice (in Rows 2 & 3):

| Row | submitter_donor_id | submitter_specimen_id | submitter_treatment_id | surgery_type |
| -- | -- | -- | -- | -- |
| 1 | Pat_2 | Sp-32 | Tr-2 | Gastric Antrectomy |
| 2 | Pat_2 | Sp-34 | Tr-2 | Gastric Antrectomy |
| 3 | Pat_2 | Sp-34 | Tr-4 | Gastric Antrectomy |

Validation result:

This invalidates as expected:
![example4](https://user-images.githubusercontent.com/4992044/170786791-9393a8f1-6167-4298-819a-f100d4bbeec8.png)

**Test case 5:** A donor has had two different surgeries (each associated with a different submitter_treatment_id), one with a specimen resected, the other without. Submit two different combinations of [`submitter_donor_id`, `submitter_treatment_id`, `surgery_type] for two rows, one with a specimen re-sected, the other without.

Samples Files:

[donor.csv](https://github.com/icgc-argo/argo-clinical/files/8789841/donor.csv)
[specimen.csv](https://github.com/icgc-argo/argo-clinical/files/8789842/specimen.csv)
[primary_diagnosis.csv](https://github.com/icgc-argo/argo-clinical/files/8789843/primary_diagnosis.csv)
[treatment_example5.csv](https://github.com/icgc-argo/argo-clinical/files/8789844/treatment_example5.csv)
[surgery_example5.csv](https://github.com/icgc-argo/argo-clinical/files/8789845/surgery_example5.csv)

Expected validation: should pass validation because the combination of `submitter_donor_id` and `submitter_treatment_id` are associated with two different surgery types.

| Row | submitter_donor_id | submitter_specimen_id | submitter_treatment_id | surgery_type |
| -- | -- | -- | -- | -- |
| 1 | Pat_2 | Sp-32 | Tr-2 | Gastric Antrectomy |
| 2 | Pat_2 | Sp-34 | Tr-2 | Gastric Antrectomy |
| 3 | Pat_2 | | Tr-1 | Mastectomy |

Validation result:

Validates as expected
![example5](https://user-images.githubusercontent.com/4992044/170788404-afccb050-85f4-4776-9209-d2689317a266.png)

**Test case 6:** A donor has two different surgeries, one with a specimen re-sected, the other without a specimen re-sected, but both surgery types are associated with the same `submitter_treatment_id`. Submit the same combination of [`submitter_donor_id`, `submitter_treatment_id`] for two rows, one row with a `submitter_specimen_id` submitted, the other without, and each row is associated with a different `surgery_type`.

Sample Files:
[donor.csv](https://github.com/icgc-argo/argo-clinical/files/8789852/donor.csv)
[specimen.csv](https://github.com/icgc-argo/argo-clinical/files/8789853/specimen.csv)
[primary_diagnosis.csv](https://github.com/icgc-argo/argo-clinical/files/8789854/primary_diagnosis.csv)
[treatment_example6.csv](https://github.com/icgc-argo/argo-clinical/files/8789855/treatment_example6.csv)
[surgery_example6.csv](https://github.com/icgc-argo/argo-clinical/files/8789857/surgery_example6.csv)

Expected validation: 
Should fail validation because even though `submitter_specimen_id` is not submitted for one of the row,  the combination of [`submitter_donor_id` + `submitter_treatment_id`] ("Pat_2" + "Tr-2") is associated with two different surgery_types ("Gastric Antrectomy" and "Mastectomy") which is not valid.

| Row | submitter_donor_id | submitter_specimen_id | submitter_treatment_id | surgery_type |
| -- | -- | -- | -- | -- |
| 1 | Pat_2 | Sp-34 | Tr-2 | Gastric Antrectomy |
| 2 | Pat_2 | | Tr-2 | Mastectomy |

Validation result:
Fails validation as expected
![example6](https://user-images.githubusercontent.com/4992044/170792336-d163e7f7-323e-4fa3-9fe5-69faf949523b.png)

Test case 7: A donor has the same surgery type, each associated with the same `submitter_treatment_id`, but one has a specimen re-sected, and the other without a specimen resected. Submit the same combination of [`submitter_donor_id`, `submitter_treatment_id`, `surgery_type`] for two rows, one with a `submitter_specimen_id`, the other without. 

Sample Files:
[donor.csv](https://github.com/icgc-argo/argo-clinical/files/8789861/donor.csv)
[specimen.csv](https://github.com/icgc-argo/argo-clinical/files/8789863/specimen.csv)
[primary_diagnosis.csv](https://github.com/icgc-argo/argo-clinical/files/8789864/primary_diagnosis.csv)
[treatment_example7.csv](https://github.com/icgc-argo/argo-clinical/files/8789865/treatment_example7.csv)
[surgery_example7.csv](https://github.com/icgc-argo/argo-clinical/files/8789866/surgery_example7.csv)

Expected validation: 
Should fail validation because the only way the combination of [`submitter_donor_id`, `submitter_treatment_id`, `surgery_type`] can appear more than once in the Surgery table, is if they are associated with different `submitter_specimen_id`. In this case, the second row does not have a submitted `submitter_specimen_id` so it should fail.

**Passes validation incorrectly:**

![example7](https://user-images.githubusercontent.com/4992044/170790955-caa579aa-b297-4b5e-abc0-e706c85d8256.png)

**Comment by b-f-chan** [comment]
@Buwujiu - Looks like the testing is done, if you can please review and address these results, thanks!

**Comment by hknahal** [comment]
Thanks @Buwujiu The "Test case 7" works now (it invalidates as expected). 

Can we update the error messages as follows?

1. For "Test case 3": Can we update the error messages to include the bolded sentence? "The combination of submitter_donor_id 'Pat-2' and submitter_treatment_id 'Tr-2' can only be associated with one surgery_type. **Please review your data submission.**"

2. For "Test case 4": Revise current error message ("Surgery with The submitter_specimen_id 'Sp-34' has already been submitted either in current or previous submission, submitter_specimen_id can only be submitted once in Surgery.") to say this instead:

> "The submitter_specimen_id 'Sp-34' has already been indicated as resected during a surgery in the current or previous submission. The submitter_specimen_id 'Sp-34' can only be submitted once in the Surgery schema. Please review your data submission."

3. For "Test case 6": Revise current error message ("When submitter_specimen_id is not submitted, the combination of [ submitter_donor_id 'Pat-2' ] and [ submitter_treatment_id 'Tr-2' ] should only be submitted once in Surgery") to say this instead:

> "When submitter_specimen_id is not submitted, the combination of submitter_donor_id 'Pat-2' and submitter_treatment_id 'Tr-2' should only be submitted once in the Surgery schema. Please review your data submission."

4. Revise current error message ("You are trying to submit the same [submitter_donor_id, submitter_treatment_id, submitter_specimen_id] in multiple rows. [submitter_donor_id, submitter_treatment_id, submitter_specimen_id] can only be submitted once per file.") to say this instead (add the bolded part):

> You are trying to submit the same [submitter_donor_id, submitter_treatment_id, submitter_specimen_id] in multiple rows. **The  combination of** [submitter_donor_id, submitter_treatment_id, submitter_specimen_id] can only be submitted once per file. **The same submitter_specimen_id cannot be resected more than once. Please review your data submission.**

The reason I added "Please review data submission", is because we can't assume what exactly the error is (ie. maybe they meant to submit a different submitter_treatment_id in Test case 3 and 6).

**Comment by b-f-chan** [comment]
Finishing this ticket off includes reverting the changes in Clinical Service that suppressed/commented out the Surgery Table (i.e. must restore Surgery Table in Clinical)

**Comment by hknahal** [comment]
All test cases tested in DEV (dictionary version `118`) and QA (dictionary version `116.0`).

**Comment by b-f-chan** [comment]
Moving to Awaiting for Release
