### ISSUE TITLE
SOP: Request to "change" ID fields in sample registration table

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/argo-clinical#770]
ID fields changes are NOT allowed. In this scenario:
1. DCC:  remove the existing samples/specimen/donor data in Clinical database (Ref: icgc-argo/argo-clinical#771)
2. Data submitter: re-submit the updated sample registration table

If molecular data has been submitted and process, for SONG database, 
- DCC: remove samples/specimen/donor data in Song database (Ref: https://github.com/icgc-argo/roadmap/issues/900)
- DCC: suppress the analysis which belong to removed samples/specimen/donor in Song

Expect output:
- We need to have a strategy/technical approach/SOP to lay out the steps which are needed

**NOTE:** You can't actually "CHANGE" IDs, system won't allow it, you have to remove the offending ID and resubmit at which point a new ID generated for that sample

**Comment by b-f-chan** [comment]
Long-term - Bashar will write SOP, but there is still technical work that would need to be done to make the SOP usable

Short-term - What can we do to unblock them now?  Bashar will work on that

**Comment by lindaxiang** [comment]
@blabadi - https://github.com/icgc-argo/workflow-roadmap/issues/235
- There was an error in the data for the normal sample P02374, the submitter_specimen_id should be 38119-PB-P02374 instead of 38119-OCT-1-P02374

**Comment by blabadi** [comment]
the SOP started by Christina is here: https://wiki.oicr.on.ca/pages/viewpage.action?pageId=150638363

**Comment by lindaxiang** [comment]
@blabadi I tested the `DELETE /studies/{studyId}/samples/{ids}` endpoint in QA for the following study/analysis/sample
```
studyId: TEST-INTL
analysisId: 9ec36cb8-31d4-4def-836c-b831d47def90
sampleId: SA622751
songURL: https://submission-song.rdpc-qa.cancercollaboratory.org/
```
step 1: suppress the analysis in submission-song by call: PUT /studies/{studyId}/analysis/suppress/{id} ---- Complete
step 2: delete the sample by call: DELETE /studies/{studyId}/samples/{ids}. ----- Failed with 500 error:
```
 cache-control: no-cache, no-store, max-age=0, must-revalidate 
 date: Wed, 25 May 2022 14:13:25 GMT 
 expires: 0 
 pragma: no-cache 
 strict-transport-security: max-age=15724800; includeSubDomains 
 x-content-type-options: nosniff 
 x-frame-options: DENY 
 x-xss-protection: 1; mode=block 
```

**Comment by b-f-chan** [comment]
dev test, then @lindaxiang verify on QA

**Comment by b-f-chan** [comment]
dev test first, then Linda can test on QA

**Comment by blabadi** [comment]
SOP for samples removal is documented here: https://wiki.oicr.on.ca/pages/viewpage.action?pageId=150638363

**Comment by lindaxiang** [comment]
Sample removal for scenario #1 in above SOP have been tested in QA. 
See https://github.com/icgc-argo/argo-clinical/issues/771#issuecomment-1151371773

**Comment by lindaxiang** [comment]
Yes. I think so. @b-f-chan

**Comment by b-f-chan** [comment]
Closing, since changes are tested & verified in #771
