### ISSUE TITLE
Bug: Donor aggregator not receiving clinical index event 

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/argo-clinical#775]
### The Issue
Argo DEV: after registering new samples using program `ALEXIS-CA`, the donor dashboard did not populate the registered samples. Donor aggregator log showed no sign of clinical index even being queued, therefore nothing was indexed. Possible cause is clinical service failed to send message to kafka. 

After manually triggered index, new samples did get indexed correctly. 

Similar issues have been observed in staging and prod. 

![Screen Shot 2022-05-27 at 11.50.02 AM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/5cf15a38-d6e9-4a0c-b0fb-bbf8091acb1d)

**Comment by lindaxiang** [comment]
Related issue: https://github.com/icgc-argo/roadmap/issues/883
