### ISSUE TITLE
Add clearer error description for missing error_types

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-clinical#789]
There are some error types without descriptions coming through on the submitted data section. Can you implement the clearer descriptions please.

1. `UNRECOGNIZED_FIELD` - use description:
`[field-name] is not a field within the latest dictionary. Please remove this from the [file_type].tsv file before submitting.`

For an example, see https://platform-ui.dev.argo.cancercollaboratory.org/submission/program/DASH-CA/clinical-data?tab=donor 
![image](https://user-images.githubusercontent.com/18424138/176740645-95f7565b-0e76-4b8a-a8bb-14a8d45678bb.png)

**Comment by Buwujiu** [comment]
Tested in QA https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/HNAHAL-CA/clinical-data?donorId=&tab=donor, working as expected.

**Comment by Buwujiu** [comment]
Tested in staging, working as expected.
