### ISSUE TITLE
Submitted Data: clinical completeness specimen should be counting DNA normal and tumour only

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-clinical#790]
For clinical completeness, a data submitter needs at least one Tumour/ Normal `DNA` Specimen submitted.

Complete requirements are here: https://wiki.oicr.on.ca/display/icgcargotech/Submitted+Clinical+Section+with+Invalid+Donors#SubmittedClinicalSectionwithInvalidDonors-UISpecifications

So we need to take that into account with these counts here

![image](https://user-images.githubusercontent.com/18424138/177177907-11409a8c-83b1-4cef-8824-02d3ffc137a8.png)

@demariadaniel 
Requirement Updates: 
  - For donor, treatment, PD, follwup 
      - For the core completeness table, based on the current calculation rules: https://wiki.oicr.on.ca/display/icgcargotech/Core+Clinical+Data+Exceptions#CoreClinicalDataExceptions-CoreClinicalDataCalculation, the completeness number for donor, specimen, primary diagnosis, follow up, treatment a**re either 1 or 0**. 1 means it's core complete, 0 means it's not. the core complete is calculated here: https://github.com/icgc-argo/argo-clinical/blob/develop/src/submission/submission-to-clinical/stat-calculator.ts#L95

The mockups shows some cells are `2`, but it's not align with the core completion calculation rule. 
I will try to update the mockups. The core completion table should display: 
- For DO, PD, TR, FO
  - display a green checkmark when the api returns '1'.
  - display '0' with red highlight when the api returns '0'

- For NS, TS
   - Please display a green checkmark when there is at least 1 tumour or normal DNA specimen registered
   - if there is none, display '0' with red highlight.

**Comment by Buwujiu** [comment]
Requirement Updates: 
  - For donor, treatment, PD, follwup 
      - For the core completeness table, based on the current calculation rules: https://wiki.oicr.on.ca/display/icgcargotech/Core+Clinical+Data+Exceptions#CoreClinicalDataExceptions-CoreClinicalDataCalculation, the completeness number for donor, specimen, primary diagnosis, follow up, treatment a**re either 1 or 0**. 1 means it's core complete, 0 means it's not. the core complete is calculated here: https://github.com/icgc-argo/argo-clinical/blob/develop/src/submission/submission-to-clinical/stat-calculator.ts#L95

The mockups shows some cells are `2`, but it's not align with the core completion calculation rule. 
I will try to update the mockups, for now, @demariadaniel just display whatever the db returns under `coreCompletion` is fine. 

- For NS, TS
   - Please show the actual number of tumour and normal DNA specimens that are registered.

**Comment by Buwujiu** [comment]
Tested in QA on DATA-CA, working as expected, thank you! @demariadaniel
