### ISSUE TITLE
Add a Clear Program Level Exception endpoint

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/argo-clinical#811]
## Detailed Description
Add a clear endpoint for deleting existing program level exceptions by program Id.

## Possible Implementation
- add a new swagger endpoint to clinical.

**Comment by Buwujiu** [comment]
tested in QA, working as expected.

**Comment by Buwujiu** [comment]
tested in Staging, working as expected.

**Comment by lindaxiang** [comment]
It will return `200` even if the project_id does not exist in ARGO?

**Comment by Buwujiu** [comment]
Made a feedback ticket: https://github.com/icgc-argo/argo-clinical/issues/880. This ticket can move forward.
