### ISSUE TITLE
Add a get program level exceptions by program Id

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/argo-clinical#812]
## Detailed Description
Add an endpoint for getting program level exceptions by program id.
it's only allowed for DCC admins.
CLINICAL.WRITE

## Possible Implementation
- Add a new swagger endpoint

**Comment by Buwujiu** [comment]
tested in QA, working as expected.

**Comment by Buwujiu** [comment]
tested in Staging, working as expected.

**Comment by lindaxiang** [comment]
@ciaranschutte @Buwujiu What's the expected output from this `GET` endpoint? I got  the following `200` response, but `content-length` is 0.
```
 connection: keep-alive 
 content-length: 0 
 date: Mon,16 Jan 2023 21:01:26 GMT 
 strict-transport-security: max-age=16070400 
 x-powered-by: Express 
 x-response-time: 8.740ms 
```

**Comment by Buwujiu** [comment]
To address the issue Linda found, made a feedback ticket: https://github.com/icgc-argo/argo-clinical/issues/880
