### ISSUE TITLE
rename registration fields based on latest tsv sample file

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/argo-clinical#82]
`< entity > _submitter_id ->   submitter_ < entity > _id`

**Comment by blabadi** [comment]
https://docs.google.com/spreadsheets/d/1UlqR8_8hgAQmKrOZj4qoxlmt3WLVwQU3zWiL1385wZg/edit#gid=588564836

**Comment by alekspejovic** [comment]
Tested in QA - looks good.
