### ISSUE TITLE
Clinical API should accept API Keys from Ego

### ISSUE THREAD

**Issue by sifavahora** [icgc-argo/argo-clinical#820]
Clinical API auth checks currently only accept Ego JWTs, they should also accept API Keys from Ego.
If the Authorization header on a request contains a UUID instead of a JWT, this should be considered an API Key. To check if this provides the user permission to access the requested data clinical needs to:

- send this API Key to Ego Check API Key endpoint, clinical will receive back a list of user permissions (same as in scopes of JWT): https://ego.icgc-argo.org/api/swagger-ui.html#/Api%20Keys/checkApiKeyUsingPOST
- clincial can use these permissions to check if user can be granted access (same rules as for  permissions from JWT)

**Comment by lindaxiang** [comment]
Test all API Get endpoints for [Clinical Data](https://clinical.qa.argo.cancercollaboratory.org/api-docs/#/Clinical%20Data), all can use API keys as token.

**Comment by edsu7** [comment]
List of GET points that failed on staging
```
https://clinical.platform.staging.icgc-argo.org/api-docs/#/Submission%20Configurations/get_submission_configs
https://clinical.platform.staging.icgc-argo.org/api-docs/#/Dictionary/get_dictionary_changes
https://clinical.platform.staging.icgc-argo.org/api-docs/#/Sample%20Registration/get_submission_program__programId__registration:~:text=GET-,/submission/program/%7BprogramId%7D/registration,-Get%20active%20registration
https://clinical.platform.staging.icgc-argo.org/api-docs/#/Submission/get_submission_program__programId__clinical_
https://clinical.platform.staging.icgc-argo.org/api-docs/#/Clinical%20Data/get_clinical_program__programId__donor__donorId_
https://clinical.platform.staging.icgc-argo.org/api-docs/#/Clinical%20Data/get_clinical_program__programId_clinical_data
https://clinical.platform.staging.icgc-argo.org/api-docs/#/Clinical%20Data/
https://clinical.platform.staging.icgc-argo.org/api-docs/#/Clinical%20Data/get_clinical_program__programId_clinical_errorsget_clinical_program__programId__clinical_tsv
https://clinical.platform.staging.icgc-argo.org/api-docs/#/Clinical%20Data/get_clinical_program__programId__tsv_all
https://clinical.platform.staging.icgc-argo.org/api-docs/#/Clinical%20Data/get_clinical_program__programId__tsv__entityType_
```

**Comment by lindaxiang** [comment]
Save observation as what Edmund listed above.

**Comment by Buwujiu** [comment]
issue will be fix under https://github.com/icgc-argo/argo-clinical/issues/852.
