### ISSUE TITLE
Allow Sample Registration Updates

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/argo-clinical#839]
## Detailed Description
This is the API task of https://github.com/icgc-argo/platform-ui/issues/2434. 

Currently on the platform, users can only register samples once, without having the chance to update the form once it's submitted. If users made mistakes, they have no way of correcting. For example, they may want to change the gender, sample type in sample registrations that have already been submitted. We want to add the ability to allow updates on sample registrations.
 
Complete specs: 
https://wiki.oicr.on.ca/display/icgcargotech/Sample+Registration+Updates+Specs

## Possible Implementation
Modify clinical system to 
- provide a summary of which columns and what values are being updated
- let data submitters reopen unsaved updates
- let DCC admins approve pending updates, and reopen pending updates 
- save updated sample registration records 

## Exit Criteria
As a data submitter, I shall
- see a modal asking me if I want to continue with updating sample registration, after uploading sample registration file to overwrite existing records
- see a summary of what's being updated
- have the option to reopen the submission on the summary page
- not be able to register any more samples, there is a lock icon on Sample Registration Page
- when the admin approves my updates, I shall see the updated samples on the submitted data page.

As a DCC admin, I shall
- go to the sample registration page if there is a lock icon, I shall see the summary of updated values
- have 1 reopen button, 1 approve button on the summary page
- be able to cancel the updates by using reopen
- be able to approve the updates by using approve
- the lock icon on the sample registration page shall be gone if either reopened or approved

**Comment by Buwujiu** [comment]
Let's 
1. break down once @samrichca looks at the code
2. make an epic for the feature

**Comment by patrickdsantos** [comment]
Hello! Here are the links to the updated pages:

Copy update for Register Samples page: https://zpl.io/awOeOLg
Update Registered Samples Pop-up: https://zpl.io/7wLe4Yj
Registered Samples, Pending Approval: https://zpl.io/5EMxqYJ
Validate Submission: https://zpl.io/2ZXEgAL
