### ISSUE TITLE
Lost to Follow up field cross-file validation

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-clinical#854]
This is related to https://github.com/icgc-argo/argo-dictionary/issues/358

A new optional field called `lost_to_followup_after_clinical_event_id` will be added to the Donor schema (see https://github.com/icgc-argo/argo-dictionary/blob/6de639fc8637e4843b203620fcda213b0cc8e03c/schemas/donor.json#L342) which will require cross-file validation checks in clinical.

### Clinical changes required:
If `lost_to_followup_after_clinical_event_id` is submitted:

1. The identifier submitted in the `lost_to_followup_after_clinical_event_id` must exist in the clinical submission in either the `submitter_primary_diagnosis_id` or `submitter_treatment_id` or `submitter_follow_up_id` field. This check will need to be done against the active submission and signed-off submission. If it does not match any of the existing IDs in the `submitter_primary_diagnosis_id` or `submitter_treatment_id` or `submitter_follow_up_id` fields, then the validation should fail and report an error message (eg. "The ID submitted in the 'lost_to_followup_after_clinical_event_id' does not exist in your clinical submission. Check your submission to ensure you submit the correct clinical event ID")

**Example of valid submission:**

The identifier submitted in the `lost_to_followup_after_clinical_even_id` field ("FL-22") exists in the `submitter_follow_up_id` column in the `Follow up` schema. This means the donor was last known to be alive 230 days after their primary diagnosis (this is the "interval_of_followup" value for submitter_follow_up_id "FL-22").
![ltf_valid](https://github.com/icgc-argo/argo-clinical/assets/4992044/95faa795-1f77-4303-947d-954c7aa3538b)

Test files:
NOTE: Change file suffix to *.tsv when using test files
[sample_registration.txt](https://github.com/icgc-argo/argo-clinical/files/11567373/sample_registration.txt)
[donor_valid.txt](https://github.com/icgc-argo/argo-clinical/files/11567081/donor_valid.txt)
[specimen_valid.txt](https://github.com/icgc-argo/argo-clinical/files/11567084/specimen_valid.txt)
[primary_diagnosis_valid.txt](https://github.com/icgc-argo/argo-clinical/files/11567083/primary_diagnosis_valid.txt)
[treatment_valid.txt](https://github.com/icgc-argo/argo-clinical/files/11567086/treatment_valid.txt)
[surgery_valid.txt](https://github.com/icgc-argo/argo-clinical/files/11567085/surgery_valid.txt)
[chemotherapy_valid.txt](https://github.com/icgc-argo/argo-clinical/files/11567080/chemotherapy_valid.txt)
[follow_up_valid.txt](https://github.com/icgc-argo/argo-clinical/files/11567082/follow_up_valid.txt)

**Example 1 of invalid submission:**
The identifier submitted in `lost_to_followup_after_clinical_event` ("TR-3") doesn't exist in any of the `submitter_primary_diagnosis_id`, `submitter_treatment_id` or `submitter_follow_up_id` fields.
![ltf_invalid1](https://github.com/icgc-argo/argo-clinical/assets/4992044/06ebc903-35e8-4fb1-92ee-c971ee8cfcb7)

**Error Message**: "The identifier 'TR-3' submitted in the 'lost_to_followup_after_clinical_event_id' field does not exist in your clinical submission."

Test files:
[donor_invalid_case1.txt](https://github.com/icgc-argo/argo-clinical/files/11567112/donor_invalid_case1.txt)
[specimen_invalid_case1.txt](https://github.com/icgc-argo/argo-clinical/files/11567115/specimen_invalid_case1.txt)
[primary_diagnosis_invalid_case1.txt](https://github.com/icgc-argo/argo-clinical/files/11567114/primary_diagnosis_invalid_case1.txt)
[treatment_invalid_case1.txt](https://github.com/icgc-argo/argo-clinical/files/11567117/treatment_invalid_case1.txt)
[surgery_invalid_case1.txt](https://github.com/icgc-argo/argo-clinical/files/11567116/surgery_invalid_case1.txt)
[chemotherapy_invalid_case1.txt](https://github.com/icgc-argo/argo-clinical/files/11567111/chemotherapy_invalid_case1.txt)
[follow_up_invalid_case1.txt](https://github.com/icgc-argo/argo-clinical/files/11567113/follow_up_invalid_case1.txt)

2. No additional entries are allowed to be submitted in any of the clinical events (Specimen, Primary Diagnosis, Treatment, Follow Up) where the new entry's time interval field is greater than the time interval associated with the ID in the `lost_to_followup_after_clinical_event_id` field. 

| Matching clinical ID for lost_to_followup_after_clinical_event ID | Time interval to check against |
|--|--|
| submitter_primary_diagnosis_id | age_at_diagnosis |
| submitter_treatment_id | treatment_start_interval |
| submitter_follow_up_id | interval_of_followup |

**Example 2 of invalid submission:**
The data submitter indicated the donor was lost to follow up after a follow up that happened 230 days after their primary diagnosis (`lost_to_followup_after_clinical_event_id` = "FL-22").
The data submitter submits a new entry in the Treatment schema (last row highlighted in red text) where the donor has a new treatment (submitter_treatment_id = "TR-33") that started 250 days after their primary diagnosis (the "treatment_start_interval" field). 
However, this does not make sense because the donor was lost to follow up before this (230 days after primary diagnosis). In this case, TR-33.treatment_start_interval (250 days) is greater than FL-22.interval_of_followup (230 days).

![ltf_invalid2](https://github.com/icgc-argo/argo-clinical/assets/4992044/788d5aa0-d128-4ab4-9531-3c4dcc3d023c)

**Error message:** "A clinical event that occurs after the donor was lost to follow up cannot be submitted. The donor was indicated to be lost to follow up 230 days after their primary diagnosis ("lost_to_followup_after_clinical_event_id" = "FL-22"), but a new treatment ("TR-33") that started after the donor was lost to follow up has been submitted. If the donor was found later on, then update the "lost_to_followup_after_clinical_event_id" field to be empty."

Test files:
[donor_invalid_case2.txt](https://github.com/icgc-argo/argo-clinical/files/11567142/donor_invalid_case2.txt)
[specimen_invalid_case2.txt](https://github.com/icgc-argo/argo-clinical/files/11567145/specimen_invalid_case2.txt)
[primary_diagnosis_invalid_case2.txt](https://github.com/icgc-argo/argo-clinical/files/11567144/primary_diagnosis_invalid_case2.txt)
[treatment_invalid_case2.txt](https://github.com/icgc-argo/argo-clinical/files/11567147/treatment_invalid_case2.txt)
[surgery_invalid_case2.txt](https://github.com/icgc-argo/argo-clinical/files/11567146/surgery_invalid_case2.txt)
[chemotherapy_invalid_case2.txt](https://github.com/icgc-argo/argo-clinical/files/11567140/chemotherapy_invalid_case2.txt)
[follow_up_invalid_case2.txt](https://github.com/icgc-argo/argo-clinical/files/11567143/follow_up_invalid_case2.txt)

**Comment by puneet-oicr** [comment]
Dev needed on this from the clinical submission side. @Buwujiu @b-f-chan  - who should we assign this to?

**Comment by Buwujiu** [comment]
Hardeep added a new field `lost_to_followup_after_clinical_event` to the donor schema, PR: https://github.com/icgc-argo/argo-dictionary/pull/383

**Comment by Buwujiu** [comment]
Can release in dictionary 1.18, Hardeep will release the rest of dictionary 1.17 first.

**Comment by hknahal** [comment]
Tested valid case in QA using `TEST-CA`. Validation failed with incorrect error message because a submitter_treatment_id `TR-5` was never submitted in the Treatment file:

![donor_error](https://github.com/icgc-argo/argo-clinical/assets/4992044/61548676-c9ed-4baf-973a-815e74c521aa)

**Details about error:**

The follow up identifier `fl-22` indicated in the `lost_to_followup_after_clinical_event_id` field is correct and indicates the donor was lost to follow up 230 days after their primary diagnosis:
![follow_up](https://github.com/icgc-argo/argo-clinical/assets/4992044/4f8442e7-3662-4f94-ac8b-679a0bfb3fe8)

However, the error message says that a new treatment `TR-5` was submitted which starts after the donor was lost to follow up, but this submitter_treatment_id does not exist in the Treatment file. Only submitter_treatment_ids `TR-1` and `TR-2` exist, so unsure where it is retrieving `TR-5` from:
![treatment](https://github.com/icgc-argo/argo-clinical/assets/4992044/09c7b85d-5bf9-4ce0-bc19-406ca59bc305)

**Comment by Buwujiu** [comment]
A small feedback in the error message when submitting an non-existing submitter id. 
![Screenshot 2023-07-20 at 3 53 40 PM](https://github.com/icgc-argo/argo-clinical/assets/8744047/6daaf6ee-1fd5-4f2a-8238-57588b4fd1a0)

**Comment by hknahal** [comment]
Tested `Example 1 of invalid submission` from above in QA using `TEST-CA`. Validation fails as expected:

![invalid_case_result](https://github.com/icgc-argo/argo-clinical/assets/4992044/ecaf58af-8ef1-440a-a89c-35afbde740b3)

**Comment by hknahal** [comment]
Tested `Example 2 of invalid submission` from above in QA using `TEST-CA`. Failed validation as expected:

![invalid_case2](https://github.com/icgc-argo/argo-clinical/assets/4992044/dce0694e-b43d-4940-97fa-97b075a8db0b)

**Comment by hknahal** [comment]
Found test case that fails validation

Test case 1:
TEST-INTL on QA

- Submit [donor.csv](https://github.com/icgc-argo/argo-clinical/files/12155772/donor.csv) where identifier submitted in the `lost_to_followup_after_clinical_event_id` field belongs to a different donor.
- Fails as expected but error message is misleading

![donor_error](https://github.com/icgc-argo/argo-clinical/assets/4992044/7eeb2532-77a9-4b9f-b030-f09a294ad18a)

The `lost_to_followup_after_clinical_event_id` belongs to a different submitter_donor_id `DN429`:

![follow_up](https://github.com/icgc-argo/argo-clinical/assets/4992044/be614c1d-4c74-4dc2-a7ef-79ca9fac0ae0)

**Comment by demariadaniel** [comment]
Tested and working on localhost:
![Screenshot 2023-08-09 at 12.42.01 PM.png](https://images.zenhubusercontent.com/619d338b44e7d7d8ae43f6df/23157f0a-90aa-49ee-a03c-99829e756220)

**Comment by hknahal** [comment]
Tested in Staging using `TEST-CA` with `lost_to_followup_after_clinical_event_id` submitted in donor file. Validation failed as expected. Confirmed lost to followup feature is hidden in Staging
![test-ca_ltf_feature_hidden_staging](https://github.com/icgc-argo/argo-clinical/assets/4992044/5896ec97-df46-4544-872d-05b6ecca91d4)

**Comment by hknahal** [comment]
Tested in QA using dictionary version `127.0`

[Alexis's `Test case 2`](https://github.com/icgc-argo/argo-clinical/issues/854#issuecomment-1644516981) fails validation. Expected this test case to pass validation because there is no clinical event after submitter_treatment_id `tr4-1`, but it fails.

[Alexis's `Test case 3` ](https://github.com/icgc-argo/argo-clinical/issues/854#issuecomment-1644516981) fails validation. Expected this test case to pass validation because there are no new clinical events after the `lost_to_followup_after_clinical_event_id` = `pd4-2` which is a primary diagnosis that occurs at `age_at_diagnosis` = `60`. 

![error](https://github.com/icgc-argo/argo-clinical/assets/4992044/915b9024-d9c6-45d1-9693-5cd001cb29d9)

![pd](https://github.com/icgc-argo/argo-clinical/assets/4992044/abe036ca-37a7-4173-add7-f854b889762b)

The error message reports that a new treatment clinical event `tr4-1` has been submitted after `pd4-2`, but this submitter_treatment_id is related to `submitter_primary_diagnosis_id` = `pd4-1` which occurs at `age_at_diagnosis` = 50. So  `lost_to_followup_after_clinical_event_id` = `pd4-2` should be allowed 

![tr4-1](https://github.com/icgc-argo/argo-clinical/assets/4992044/f18269dc-70c0-4537-bb15-9dd491e317d5)

[Hardeep's `Test case 2`](https://github.com/icgc-argo/argo-clinical/issues/854#issuecomment-1648767640) fails validation. Expected this test case to pass validation (see details above).

**Comment by hknahal** [comment]
All test cases from above pass/fail as expected, except this test case:

**Test case 6:**
Tested using `TEST-CA` on DEV:

- Donor `DN190` has two primary diagnoses - `pd4-1` which has `age_at_diagnosis` = `55` and `pd4-2` which has `age_at_diagnosis` = `60`.
- `lost_to_followup_after_clinical_event_id` = `pd4-2` (the second most recent primary diagnosis that happened at age 60)
- A new treatment event `TR-2` that is associated with this second primary diagnosis ("pd4-2") is submitted as well, so the validation fails because `TR-2` is not allowed because it is submitted after the donor is lost to follow up.
- The validation reports 6 errors, but only the 2nd error message (highlighted in green below) is correct. The other error messages are incorrect and do not need to be displayed. Even though the other 5 error messages are incorrect, the clinical event the IDs are reporting against are incorrect (see explanation in red text below):
![test-ca_test6](https://github.com/icgc-argo/argo-clinical/assets/4992044/5c52dd5e-23bf-41e5-b343-795631628805)

Submission files used in `TEST-CA` on DEV:
[donor_ininvalidltf6.csv](https://github.com/icgc-argo/argo-clinical/files/12825175/donor_ininvalidltf6.csv)[specimen_invalidltf6.csv](https://github.com/icgc-argo/argo-clinical/files/12825183/specimen_invalidltf6.csv)
[primary_diagnosis_invalidltf6.csv](https://github.com/icgc-argo/argo-clinical/files/12825178/primary_diagnosis_invalidltf6.csv)
[treatment_invalidltf6.csv](https://github.com/icgc-argo/argo-clinical/files/12825184/treatment_invalidltf6.csv)
[chemotherapy_invalidltf6.csv](https://github.com/icgc-argo/argo-clinical/files/12825172/chemotherapy_invalidltf6.csv)
[radiation_invalidltf6.csv](https://github.com/icgc-argo/argo-clinical/files/12825179/radiation_invalidltf6.csv)
[follow_up_invalidltf6.csv](https://github.com/icgc-argo/argo-clinical/files/12825176/follow_up_invalidltf6.csv)

**Comment by hknahal** [comment]
**Test case 8:**

NOTE: **This is an edge case**

- `lost_to_followup_after_clinical_event_id` = `TR-2` which happened 215 days after the donor's _second_ primary diagnosis at age 60.
- A new follow up event `fl-22` that is associated with donor's _first_ primary diagnosis (`pd4-1`) at age 55 is submitted. It started 2300 days after the donor's first primary diagnosis. 
- But we can't assume all clinical events associated with the first primary diagnosis (`pd4-1`) would happen before the donor's second primary diagnosis `pd4-2`. For example, a donor could be diagnosed with breast cancer at age 55 (their first primary diagnosis) and then pancreatic cancer at age 60 (their second primary diagnosis). The donor could be followed-up in regards to their first primary diagnosis of breast cancer after they received treatment for their pancreatic cancer (their second diagnosis that happened 5 years later).
- When you compare `fl-22` in relation to `TR-2` in terms of days since the donor's **_first_** primary diagnosis `pd4-1`, the follow up event `fl-22` actually occurs after the `lost_to_followup_clinical_event_id` of `TR-2`, because `TR-2` happened 2040 days after the donor's first primary diagnosis `pd4-1` (365 days * 5 years (difference between `pd4-1` and `pd4-2`) + 215 days (days since donor's second primary diagnosis for when `TR-2` started) = 2040 days.)
- This means the donor had a follow up regarding their first primary diagnosis after they received treatment for their second primary diagnosis, in which they became lost to follow up.
- This submission passed validation but it should actually fail and report an error: `A clinical event that occurs after the donor was lost to follow up cannot be submitted. The donor was indicated to be lost to follow up 215 days after their primary diagnosis ("lost_to_followup_after_clinical_event_id" = "TR-2"), but a new follow up ("fl-22") that started after the donor was lost to follow up has been submitted.` 

![test_case8-1](https://github.com/icgc-argo/argo-clinical/assets/4992044/484325fa-3138-4896-9498-ff9362f837f5)

![test_case8-2](https://github.com/icgc-argo/argo-clinical/assets/4992044/ccdff60d-22fa-43fd-ab86-33e07ed5f5a1)

![test_case8-3](https://github.com/icgc-argo/argo-clinical/assets/4992044/ec3b49a8-8c47-4f58-90e7-d577dfd8d824)

Submission files used in `TEST-CA` on DEV:

[donor_invalid8.csv](https://github.com/icgc-argo/argo-clinical/files/12875046/donor_invalid8.csv)
[specimen_invalid8.csv](https://github.com/icgc-argo/argo-clinical/files/12875050/specimen_invalid8.csv)
[primary_diagnosis_invalid8.csv](https://github.com/icgc-argo/argo-clinical/files/12875048/primary_diagnosis_invalid8.csv)
[treatment_invalid8.csv](https://github.com/icgc-argo/argo-clinical/files/12875051/treatment_invalid8.csv)
[chemotherapy_invalid8.csv](https://github.com/icgc-argo/argo-clinical/files/12875045/chemotherapy_invalid8.csv)
[radiation_invalid8.csv](https://github.com/icgc-argo/argo-clinical/files/12875049/radiation_invalid8.csv)
[follow_up_invalid8.csv](https://github.com/icgc-argo/argo-clinical/files/12875047/follow_up_invalid8.csv)

**Comment by hknahal** [comment]
Tested corrections in DEV. Issues regarding Test cases 6,7 and 8 have been resolved and validation works correctly now.

`Test case 6` (from [this comment](https://github.com/icgc-argo/argo-clinical/issues/854#issuecomment-1749759892)) now reports the correct error message:

![test-case6_correctError](https://github.com/icgc-argo/argo-clinical/assets/4992044/48a3def9-db4b-4912-9d83-5657fa5b73f9)

`Test case 7` (from [above comment](https://github.com/icgc-argo/argo-clinical/issues/854#issuecomment-1758657947)) passes validation as expected

`Test case 8` (from [above comment](https://github.com/icgc-argo/argo-clinical/issues/854#issuecomment-1758657947)) fails validation as expected now:

![test-case8_correctError](https://github.com/icgc-argo/argo-clinical/assets/4992044/ca62b8e7-6f02-48d7-b8fc-d2b47b54f685)

**Comment by hknahal** [comment]
All test cases tested in QA using dictionary `127.1`. They all pass/fail validation as expected, except the error message for the following test case is incorrect. The `submitter_primary_diagnosis_id` and age values are switched around:

![qa_testcase4_error](https://github.com/icgc-argo/argo-clinical/assets/4992044/290e90e3-b19b-4d9a-810a-18fe3d253343)

Submission files used in `TEST-INTL`:
[sample_registration_ltf4.csv](https://github.com/icgc-argo/argo-clinical/files/12921767/sample_registration_ltf4.csv)
[donor_ltf4.csv](https://github.com/icgc-argo/argo-clinical/files/12921763/donor_ltf4.csv)
[specimen_ltf4.csv](https://github.com/icgc-argo/argo-clinical/files/12921768/specimen_ltf4.csv)
[primary_diagnosis_ltf4.csv](https://github.com/icgc-argo/argo-clinical/files/12921765/primary_diagnosis_ltf4.csv)
[treatment_ltf4.csv](https://github.com/icgc-argo/argo-clinical/files/12921769/treatment_ltf4.csv)
[chemotherapy_ltf4.csv](https://github.com/icgc-argo/argo-clinical/files/12921761/chemotherapy_ltf4.csv)
[radiation_ltf4.csv](https://github.com/icgc-argo/argo-clinical/files/12921766/radiation_ltf4.csv)
[follow_up_ltf4.csv](https://github.com/icgc-argo/argo-clinical/files/12921764/follow_up_ltf4.csv)

**Comment by hknahal** [comment]
Above error is resolved now after testing in QA using `TEST-INTL` program:
![correct_message](https://github.com/icgc-argo/argo-clinical/assets/4992044/28c5a387-0aa2-44a6-8bd7-e891c65d1e94)

**Comment by hknahal** [comment]
All test cases tested in Staging using Dictionary 1.19 pass/fail validation as expected.
