### ISSUE TITLE
Validate "reference_radiation_treatment_id" against previously submitted or currently submitting "submitter_treatment_id"

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-clinical#856]
### Description:
This is related to https://github.com/icgc-argo/argo-dictionary/issues/375
Cross-validation required between Radiation and Treatment tables, specifically the `submitter_donor_id` and `reference_radiation_treatment_id` in the Radiation table, and the `submitter_donor_id`, `submitter_treatment_id` and `treatment_type` fields in the Treatment table.

### Background:
Two new optional fields will be added to the "Radiation" schema: 
[radiation_boost](https://github.com/icgc-argo/argo-dictionary/blob/9f4a04f7e4828679015c5c6d70286a5b9100541a/schemas/radiation.json#L140)
[reference_radiation_treatment_id](https://github.com/icgc-argo/argo-dictionary/blob/9f4a04f7e4828679015c5c6d70286a5b9100541a/schemas/radiation.json#L151)

The `reference_radiation_treatment_id` is only required if `radiation_boost` = `Yes` (this is taken care by validation script). The field tells us which treatment the radiation boost was linked to.

### Requirements for `reference_radiation_treatment_id`
- The `reference_radiation_treatment_id` requires a submitter_treatment_id that has either been submitted previously in the Radiation table or is currently being submitted in the Radiation table.
- The submitted submitter_treatment_id must belong to the same submitter_donor_id
- The submitted submitter_treatment_id must be associated with radiation treatment (ie. `treatment_type` = `Radiation therapy`).

### Example of validation that will pass:
**Example 1:**  If `reference_radiation_treatment_id` matches a previous or existing `submitter_treatment_id` and it is associated with `treatment_type` = `Radiation therapy`, then validation will pass.

**Test files**
[sample_registration.txt](https://github.com/icgc-argo/argo-clinical/files/11251152/sample_registration.txt)
[donor.txt](https://github.com/icgc-argo/argo-clinical/files/11251149/donor.txt)
[primary_diagnosis.txt](https://github.com/icgc-argo/argo-clinical/files/11251150/primary_diagnosis.txt)
[chemotherapy.txt](https://github.com/icgc-argo/argo-clinical/files/11251148/chemotherapy.txt)
[radiation_pass.txt](https://github.com/icgc-argo/argo-clinical/files/11251151/radiation_pass.txt)
[treatment_pass.txt](https://github.com/icgc-argo/argo-clinical/files/11251153/treatment_pass.txt)

The submitter_treatment_id "TR-4" submitted in the `reference_radiation_treatment_id` exists in the Treatment table. 

**Radiation table:**
![radiation_pass](https://user-images.githubusercontent.com/4992044/232512002-e7a5014a-ef5e-420a-b0a9-302baf8cae80.png)

**Treatment table:**
![radiation_treatment_pass](https://user-images.githubusercontent.com/4992044/232512030-68312725-e949-470a-902f-e84ef3a911dd.png)

### Examples of validations that will fail:

**Example 1:** If `reference_radiation_treatment_id` does not match a previous or existing `submitter_treatment_id`, then validation will fail with an error message ("The submitter_treatment_id submitted in the "reference_radiation_treatment_id" field does not exist.")

**Test files:**
[sample_registration.txt](https://github.com/icgc-argo/argo-clinical/files/11251172/sample_registration.txt)
[donor.txt](https://github.com/icgc-argo/argo-clinical/files/11251169/donor.txt)
[primary_diagnosis.txt](https://github.com/icgc-argo/argo-clinical/files/11251170/primary_diagnosis.txt)
[chemotherapy.txt](https://github.com/icgc-argo/argo-clinical/files/11251168/chemotherapy.txt)
[radiation_fail1.txt](https://github.com/icgc-argo/argo-clinical/files/11251171/radiation_fail1.txt)
[treatment_fail1.txt](https://github.com/icgc-argo/argo-clinical/files/11251173/treatment_fail1.txt)

The submitter_treatment_id "TR-9" submitted in the `reference_radiation_treatment_id` does not exist in the Treatment table.

**Radiation table:**
![radiation_fail1](https://user-images.githubusercontent.com/4992044/232507788-821ca0ed-f80c-4fe9-84a9-994cbda20d5c.png)

**Treatment table:**
![radiaton_treatment_fail1](https://user-images.githubusercontent.com/4992044/232507803-3dcdf3a5-e3a8-49d9-bffc-d092e639a572.png)

**Example 2:** If `reference_radiation_treatment_id` matches a previous or existing `submitter_treatment_id` but it is associated with a different treatment type other than `Radiation therapy`, then validation will fail with an error message ("The submitter_treatment_id submitted in the "reference_radiation_treatment_id" field is not for radiation treatment.")

Test files:
[sample_registration.txt](https://github.com/icgc-argo/argo-clinical/files/11251184/sample_registration.txt)
[donor.txt](https://github.com/icgc-argo/argo-clinical/files/11251181/donor.txt)
[primary_diagnosis.txt](https://github.com/icgc-argo/argo-clinical/files/11251182/primary_diagnosis.txt)
[chemotherapy.txt](https://github.com/icgc-argo/argo-clinical/files/11251180/chemotherapy.txt)
[radiation_fail2.txt](https://github.com/icgc-argo/argo-clinical/files/11251183/radiation_fail2.txt)
[treatment_fail2.txt](https://github.com/icgc-argo/argo-clinical/files/11251185/treatment_fail2.txt)

The submitter_treatment_id "TR-1" submitted in the `reference_radiation_treatment_id` is not associated with radiation treatment in the Treatment table (it is for Chemotherapy)

**Radiation table:**
![radiation_fail2](https://user-images.githubusercontent.com/4992044/232508323-9783b6fa-e600-40db-abfe-3ab5f733779b.png)

**Treatment table:**
![radiation_treatment_fail2](https://user-images.githubusercontent.com/4992044/232508356-967a3c39-2d93-43cf-b0cc-c0f90cbbf2c6.png)

**Example 3:** The `reference_radiation_treatment_id` exists in the Treatment table, but it belongs to a different submitter_donor_id. (The `reference_radiation_treatment_id` "TR-5" belongs to `submitter_donor_id` "DN425", not "DN290"). This should fail validation.

Test files:
[sample_registration.txt](https://github.com/icgc-argo/argo-clinical/files/11251203/sample_registration.txt)
[donor.txt](https://github.com/icgc-argo/argo-clinical/files/11251200/donor.txt)
[primary_diagnosis.txt](https://github.com/icgc-argo/argo-clinical/files/11251201/primary_diagnosis.txt)
[chemotherapy.txt](https://github.com/icgc-argo/argo-clinical/files/11251208/chemotherapy.txt)
[radiation_fail3.txt](https://github.com/icgc-argo/argo-clinical/files/11251202/radiation_fail3.txt)
[treatment_fail3.txt](https://github.com/icgc-argo/argo-clinical/files/11251204/treatment_fail3.txt)

**Radiation table:**
![radiation_fail3](https://user-images.githubusercontent.com/4992044/232510869-b1e73b13-25b4-4cb5-9431-f3bff79f5036.png)

**Treatment table:**
![radiation_treatment_fail3](https://user-images.githubusercontent.com/4992044/232510901-4d47df9f-ba3a-4fb5-b568-28e74a7b4a58.png)

**Comment by puneet-oicr** [comment]
Dev needed from the clinical submission side. @Buwujiu @b-f-chan - who can we assign this to? 
Release pending till we get a validation in.

**Comment by Buwujiu** [comment]
@hknahal will make a new dictionary in qa and test cases.

**Comment by demariadaniel** [comment]
Testing, but unit tests are working properly:
https://github.com/icgc-argo/argo-clinical/pull/928

**Comment by demariadaniel** [comment]
Bug fix from Dev testing:
https://github.com/icgc-argo/argo-clinical/pull/1008

**Comment by hknahal** [comment]
Test cases that fail

1. Tested "**Example 2**" from `Examples of validations that will fail` from [above](https://github.com/icgc-argo/argo-clinical/issues/856#issue-1469862937) on QA using `TEST-GR`

Validation passed but expected validation to fail because the submitter_treatment_id submitted in the `reference_radiation_treatment_id` is not for radiation treatment. Instead it is for chemotherapy treatment. 
![radiation_example3](https://github.com/icgc-argo/argo-clinical/assets/4992044/839b76f5-c064-4774-9acd-28c31e9e6515)
![treatment_example3](https://github.com/icgc-argo/argo-clinical/assets/4992044/f0278f5d-c865-4a47-941a-c1da283951cd)

Expected error message: `The submitter_treatment_id "TR-1" submitted in the `reference_radiation_treatment_id` is not associated with radiation treatment in the Treatment table`

2. Tested "**Example 3**" from `Examples of validations that will fail` from [above](https://github.com/icgc-argo/argo-clinical/issues/856#issue-1469862937) on QA using `TEST-GR`

Validation passed but expected validation to fail because the submitter_treatment_id submitted in the `reference_radiation_treatment_id` field does not belong to the same submitter_donor_id
![radiation_example4](https://github.com/icgc-argo/argo-clinical/assets/4992044/c7e60217-1f73-47cc-90da-c7ba937ae335)
![treatment_example4](https://github.com/icgc-argo/argo-clinical/assets/4992044/6f4aeb7f-74b5-4c06-bae7-dacd015f6d0c)

Expected error message: The `reference_radiation_treatment_id` "TR-5" belongs to a different submitter_donor_id instead of "DN290".

**Comment by Buwujiu** [comment]
This feature will be hidden in staging and prod until the issues are fixed.

**Comment by demariadaniel** [comment]
Tested and working on localhost:
![Screenshot 2023-08-09 at 11.36.00 AM.png](https://images.zenhubusercontent.com/619d338b44e7d7d8ae43f6df/a30552cd-da49-4edd-9ec5-1a857bd00e2f)

**Comment by demariadaniel** [comment]
![Screenshot 2023-08-09 at 11.33.43 AM.png](https://images.zenhubusercontent.com/619d338b44e7d7d8ae43f6df/5ea2ceb2-9cf9-474b-bb0c-48a067e5c2ef)

**Comment by hknahal** [comment]
> This feature will be hidden in staging and prod until the issues are fixed.

Tested in Staging using `TEST-CA` by submitting radiation file with the `reference_radiation_treatment_id` and `radiation_boost` fields. Validation failed as expected. Confirmed feature is hidden in Staging
![radiation_test-ca](https://github.com/icgc-argo/argo-clinical/assets/4992044/c7a0a59e-e16a-4a31-80de-17c199df8268)
