### ISSUE TITLE
Get Endpoint for Specimen/Followup Level Exceptions

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/argo-clinical#860]
## Detailed Description
Create an endpoint that returns both specimen and followup level exceptions by program name.
Specs: refer to `Get exception` in
https://wiki.oicr.on.ca/display/icgcargotech/Core+Clinical+Data+Exceptions#CoreClinicalDataExceptions-APIEndpoints.1

**Comment by ciaranschutte** [comment]
@ciaranschutte  GET with entitie(s) param 
[specimen, followup] = returns specimen and followup
[specimen] = return specimen
