### ISSUE TITLE
Apply Followup Level Exceptions

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/argo-clinical#864]
## Detailed Description
Apply exceptions for Followup schema's requested_core_field using implemented exceptions endpoints.

Example:
When DCC admins submit:
https://docs.google.com/spreadsheets/d/1fukrqcqNccAVbzWRdB3dMJ69jfdWfs0oAXSurU1xEz0/edit#gid=836628442
Allow the requested_exception_value in addition to the permissible values for a requested_core_field

Expected results: users are able to submit requested_exception_value for these core fields by uploading tsv file.

**Comment by ciaranschutte** [comment]
https://github.com/icgc-argo/argo-clinical/pull/945
included in this code
generic apply exceptions
