### ISSUE TITLE
Sample Registration: allow updates

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/argo-clinical#867]
- Update endpoints to allow updates, and send back data with update data
  - Only update samples with existing IDs, not donors or specimens
  - Check for updates to existing samples, after checking if the file matches the schema
  - Return a response similar to clinical submission endpoint, with updatedAt, updatedBy, state, and entities
- Use a feature flag

Original ticket: https://github.com/icgc-argo/argo-clinical/issues/839

**Comment by Buwujiu** [comment]
This is feature is not needed anymore, closing.
