### ISSUE TITLE
Add validation rule for new `percent_tumour_cells_measurement_method` required field in Specimen schema

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-clinical#872]
This is related to https://github.com/icgc-argo/argo-dictionary/issues/388

A new required field called `percent_tumour_cells_measurement_method` is being added to the `specimen` schema: https://github.com/icgc-argo/argo-dictionary/blob/388_percent_tumour_cells_method/schemas/specimen.json#L339. This field is only required if the specimen is tumour (eg. `sample_registration.tumour_normal_designation` = `Tumour`), so it will require a validation rule in clinical to allow for this (similar to `percent_tumour_cells` field).

**Comment by demariadaniel** [comment]
Multiple failing unit tests in pipeline, needs more review

**Comment by hknahal** [comment]
Tested in QA using TEST-CA program dictionary version 124.0

Use Case 1: If `percent_tumour_cells_measurement_method` is submitted when specimen is normal, validation should fail
--> Fails validation as expected
Use Case 2: If `percent_tumour_cells_measuremenet_method` is missing when specimen is tumour, validation should fail.
--> Fails validation as expected
![use_case_1and2](https://user-images.githubusercontent.com/4992044/225454329-1232b106-fd17-4b4e-9fef-6747b6d1321b.png)


Use Case 3: If `percent_tumour_cells_measurement_method` is submitted when subnmitted is tumour, validation should pass.
--> Passes validation as expected

**Comment by Buwujiu** [comment]
Tested in staging, working as expected!

**Comment by hknahal** [comment]
Tested in Prod:

- An error is correctly reported for active clinical submissions if `percent_tumour_cells_measurement_method` is missing for specimen tumours:
![missing_field](https://github.com/icgc-argo/argo-clinical/assets/4992044/70380166-cc23-4a70-97a4-7e073cd8d1e3)

- However the dictionary migration to Dictionary version 1.17 did not report missing `percent_tumour_cells_measurement_method` for submitted clinical data. Example from PTC-SA signed-off Specimen clinical table: https://platform.icgc-argo.org/submission/program/PTC-SA/clinical-data?donorId=&tab=specimen The `percent_tumour_cells_measurement_method` field is missing, but after dictionary migration, no error was reported.
