### ISSUE TITLE
🐛 Get and Delete Should Return 40x When Program Does Not Exist

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/argo-clinical#880]
## Describe the bug
Endpoints: 
- https://clinical.qa.argo.cancercollaboratory.org/api-docs/#/Exception/get_exception__programId_
- https://clinical.qa.argo.cancercollaboratory.org/api-docs/#/Exception/delete_exception__programId_
Currently returns 200 when the requested program does not exist. This is confusing to users because they wouldn't know if they entered a wrong program name. 

## Steps To Reproduce
Go to QA clinical get or delete exception endpoint, enter a non-existent program name:
![Screen Shot 2023-01-18 at 12 05 26 PM](https://user-images.githubusercontent.com/8744047/213247485-7d392a8a-d5e2-49a1-a755-bf2d747c56ca.png)

## Expected behaviour
- [ ] When get or delete exceptions by a non-existent program name, the endpoints should return 40x errors with a message indicating the program does not exist.

**Comment by ciaranschutte** [comment]
registration and submission get endpoints return a 200 status code with an empty object when program id param does not exist. Originally coded this to be consistent.

might be bug on other endpoints too?

**Comment by joneubank** [comment]
Agreed other endpoints could improve this error message, that sounds like an error 400 for invalid parameters.

**Comment by Buwujiu** [comment]
Tested in QA, working as expected!
