### ISSUE TITLE
Unit Tests for program Level Exceptions

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/argo-clinical#918]
## Goal
Add unit tests to capture all program level exception test cases. Refer to test cases in https://wiki.oicr.on.ca/display/icgcargotech/Program+Level+Clinical+Exception+Test+Cases

**Comment by ciaranschutte** [comment]
https://github.com/icgc-argo/argo-clinical/blob/develop/test/unit/exception/applyException.spec.ts
