### ISSUE TITLE
Fix Record Counts for Entity Tables

### ISSUE THREAD

**Issue by demariadaniel** [icgc-argo/argo-clinical#922]
Outcome of investigation for https://github.com/icgc-argo/platform-ui/issues/2535

Clinical Entity Table is showing incorrect record counts
Total count is coming from Clinical SearchResult query returning false positives
This has cascading effects on Error query causing Error Icon to show at incorrect times

![Screen Shot 2023-03-13 at 2.05.58 PM.png](https://images.zenhubusercontent.com/619d338b44e7d7d8ae43f6df/e463dafe-f46a-4f4b-a261-1c2f99a9e03b)

**Comment by Buwujiu** [comment]
Tested in QA, working as expected!

**Comment by hknahal** [comment]
Tested in Staging using `DASH-CA` and the number of records match the row count:

![dash-ca](https://user-images.githubusercontent.com/4992044/236905819-08c854f2-bc6b-4539-bedd-aa1037703a1e.png)

**Comment by hknahal** [comment]
Tested in Prod using `APGI-AU`. Number of records do not match the row count in the `Primary Diagnosis` table view:
- "# of Affected Records" is 20 (in red box) but table shows 100 records:

![apgi-au_pd_errors](https://github.com/icgc-argo/argo-clinical/assets/4992044/42015564-a2cf-4200-b44a-5e39521ba151)

**Comment by hknahal** [comment]
Tested in Prod using `PTC-SA` and search for donor `DO234139`:
- Returns correct number of affected records and number of records in table.
- One minor issue: the `response_to_treatment` column is not highlighted when it has an error (`The value is not permissible for this field.`).
![ptc-sa_treatment_errors](https://github.com/icgc-argo/argo-clinical/assets/4992044/50e37d60-ba6c-4997-a848-75633a9c8544)
