### ISSUE TITLE
🐛 Core Complete - Dictionary Migrations and data validity should not impact Core Complete stats

### ISSUE THREAD

**Issue by joneubank** [icgc-argo/argo-clinical#950]
## Describe the bug

The current state:
if a donor has any invalid core entities from a migration, that entity will be marked as 0 and the donor is marked as invalid.
donors marked invalid never have their core-clinical stats recalculated until they are valid again
so the logic is basically “you are marked as incomplete until you clear all your errors, then we will recalculate for you”

Core complete stats should reflect the data submitted by the program and not be affected by the validity of that data. If a donor has a treatment submitted, then their core complete data should indicate that they have a treatment submitted. To accomplish this, we need to make two changes:
1. in the dictionary migration code, remove the section of logic that modifies core completion stats based on migration errors.
2. in the data submission code, remove the clause that prevents calculating core completion if the donor data is invalid

This change in logic is being made because we plan to only consider a donor complete if they have core data submitted and all their data is valid.

## Expected behaviour

In all cases, the core clinical stats reflect the submitted data.

1. When data is submitted, the core clinical stats reflect the submitted data, ignoring invalid states
steps: 
  - DO262500 in ALEXIS-INTL in QA, has 2 FO records submitted, but because there are errors in other entities, the core completion `FO` still shows 0, it should be a green check. 
2. when a dictionary migration occurs, the core clinical stats are unchanged

**Comment by edsu7** [comment]
Scenario to test as per Dan:

_Submit core completion record (Treatment, Follow Up) to an invalid donor, confirm 'Clinical Core Completion' is correctly updated on Submitted Data page, and state looks correct on Program Dashboard. Core completion is updated, but Donor remains invalid._

Tested in QA on DATA-CA on `DO262515` and core completion updated accordingly.

Core % completion with an invalid donor:
No screenshots available. Grabbed the wrong ones at the time.

Post clinical data submission:
![Screen Shot 2023-04-19 at 2 52 17 PM](https://user-images.githubusercontent.com/22638361/233174243-d346d0e8-fc8e-4632-9d80-8d7932c4cb39.png)
![Screen Shot 2023-04-19 at 2 52 39 PM](https://user-images.githubusercontent.com/22638361/233174256-2e899165-6040-4f68-b8d4-a612d9df67ae.png)

**Comment by hknahal** [comment]
Tested following scenario:

**Comment by hknahal** [comment]
Tested following scenario as per Dan: 

_"Find an analysis for a donor that is not clinical complete and has invalid data, submit data until it is core complete, the files should remain unreleased (not started embargo). fix the data issues (make it valid) the file should get indexed and start embargo."_

Tested on QA on RDPCDEV-QA program using donor `DO262477`

Donor not clinically complete and has invalid data after a dictionary migration:
![rdpcdev-qa](https://user-images.githubusercontent.com/4992044/235251668-88e50022-8e25-491e-8c47-1e85c66b83ab.png)


Corrected clinical data to make it valid:

![valid](https://user-images.githubusercontent.com/4992044/235252112-6cf36a33-b5a6-42b1-ba44-33052f28987f.png)
![valid_dashboard](https://user-images.githubusercontent.com/4992044/235252124-22c236f5-b92c-477d-a5c1-24ccc5ad5a2d.png)


In the File Repository, the files for `DO262477` remain in `Restricted` access (see [here](https://platform-ui.qa.argo.cancercollaboratory.org/repository?filters=%7B%22content%22%3A%5B%7B%22content%22%3A%7B%22field%22%3A%22donors.donor_id%22%2C%22value%22%3A%22DO262477%22%7D%2C%22op%22%3A%22in%22%7D%2C%7B%22content%22%3A%7B%22field%22%3A%22study_id%22%2C%22value%22%3A%22RDPCDEV-CA%22%7D%2C%22op%22%3A%22in%22%7D%5D%2C%22op%22%3A%22and%22%7D))
