### ISSUE TITLE
🐛 Dictionary migration error in QA

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-clinical#959]
## Describe the bug
Dictionary migration is QA is failing.

## Steps To Reproduce
Dictionary `124.9` contains the following updates since Dictionary `1.16` was deployed in early January 2023: https://github.com/icgc-argo/argo-dictionary/commits/develop (all commits on/after  Mar 13, 2023)
- new `percent_tumour_cells_measurement_method` field added to Specimen schema: https://github.com/icgc-argo/argo-dictionary/commit/410d0eda989d50a5c30d80f675facdacd2751bb2
- new `specimen_type` term added to Sample Registration schema: https://github.com/icgc-argo/argo-dictionary/commit/fd2bb7aa12097d22e2e4426b26cc5e9c31a6c146
- Changed `anatomic_site_progression_or_recurrence` to accept multiple values: https://github.com/icgc-argo/argo-dictionary/commit/76824af6c476d8fc95c9a34d1af34e17cb07a358
- Updated validation script for `lymph_nodes_examined_method`: https://github.com/icgc-argo/argo-dictionary/commit/f24975d5b4ac4ebf4357e1a085a7b5add4302bcb and https://github.com/icgc-argo/argo-dictionary/commit/8c1b4df1a05a31724ef2cfac501dc7cfdaaec349

1. Dictionary was uploaded to QA Lecturn successfully.
2. A `dry-run-update` was done in QA but returned the following error message:
```
{
  "error": "TypeError",
  "message": "Cannot read property 'trim' of null"
}
```
If there is an issue with one of the validation scripts, normally the dictionary migration document will show an error like this: `     "message": "failed to run script validation, check script and the input"`. But this recent dictionary migration still shows the above error "Cannot read property 'trim' of null") but there is nothing in the dictionary migration document (dictionary ID `6442dacba4a3d60009f30052`) to indicate where the error is coming from.

Dan helped retrieve more detailed error logs that show this:
![Screen Shot 2023-04-21 at 4 50 55 PM (1)](https://user-images.githubusercontent.com/4992044/233735689-af45a67d-ee15-48d9-ad69-7cfc063ed137.png)

However, none of the fields indicated in the error log (`clinical_n_category`, `clinical_m_category`, `performance_status`) were changed in the dictionary, so it's not clear why this "TypeError" is appearing now.

**Comment by demariadaniel** [comment]
Validated that issue is breaking at: https://github.com/icgc-argo/argo-clinical/blob/develop/src/submission/submission-service.ts#L943

<img width="684" alt="Screen Shot 2023-04-21 at 4 46 19 PM" src="https://user-images.githubusercontent.com/15621876/235493197-ea0f8104-bee2-4d31-85aa-5136d8650f65.png">

<img width="975" alt="Screen Shot 2023-04-27 at 2 33 21 PM" src="https://user-images.githubusercontent.com/15621876/235493243-7a12a839-aa35-46a3-bb67-b1fa4c539db1.png">
