### ISSUE TITLE
🐛 Surgery fields appended to Treatment table in Submitted Data view.

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-clinical#970]
## Describe the bug
When viewing the `Treatment` table in the `Submitted Data` view, the `Surgery` table fields are appended to the `Treatment` table. This only happens when a program has both the `Treatment` and `Surgery` tables submitted.

Also in QA. 

## Steps To Reproduce
- Go to `Submitted Data` view for `APGI-AU` program and click on `Treatment` table: https://platform.icgc-argo.org/submission/program/APGI-AU/clinical-data?tab=treatment
- Scroll to the right to see the `Surgery` fields appended to the `Treatment` table:
![surgery_appended_to_treatment](https://github.com/icgc-argo/argo-clinical/assets/4992044/a8e31d83-4e53-49c4-bcd5-35ad22943b57)

## Expected behaviour
The `Surgery` fields show not show in the `Treatment` table view.

**Comment by hknahal** [comment]
This issue is appearing in QA as well, but was not detected at time of testing.

If multiple treatment tables are submitted (ie. Surgery and Radiation tables are submitted as well), the fields from those tables get appended to Treatment table as well. In this example, the `DATA-CA` program submitted both the `Surgery` and `Radiation` tables, and fields for both tables are appended to the `Treatment` table:
https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/DATA-CA/clinical-data?donorId=&tab=treatment

**Comment by hknahal** [comment]
Following APGI-AU program's correction of the Treatment table errors, the program validated their submission and then signed-off. But now the Submitted Data view looks different than the error reported earlier. Before, if a donor had an entry in the Surgery table, the Surgery fields were appended to the end of the Treatment fields for that donor (donor showed up in Submitted Data Treatment table only once as shown [here](https://github.com/icgc-argo/argo-clinical/issues/970#issue-1706126871)). But now if a donor has an entry in the Surgery table, the donor appears twice in the Submitted Data view for the Treatment table - once for Treatment, and again for Surgery (if it has an entry in the Surgery table).

![apgi-au_submitted_data_treatment](https://github.com/icgc-argo/argo-clinical/assets/4992044/4e5d0ce1-9fd3-4f75-b8e6-e68f2e83afe2)

**Comment by hknahal** [comment]
Following APGI-AU program's correction of the Treatment table errors, the program validated their submission and then signed-off. But now the Submitted Data view looks different than the error reported earlier. Before, if a donor had an entry in the Surgery table, the Surgery fields were appended to the end of the Treatment fields for that donor (donor showed up in Submitted Data Treatment table only once as shown [here](https://github.com/icgc-argo/argo-clinical/issues/970#issue-1706126871)). But now if a donor has an entry in the Surgery table, the donor appears twice in the Submitted Data view for the Treatment table - once for Treatment, and again for Surgery (if it has an entry in the Surgery table).

![apgi-au_submitted_data_treatment](https://github.com/icgc-argo/argo-clinical/assets/4992044/4e5d0ce1-9fd3-4f75-b8e6-e68f2e83afe2)

**Comment by Buwujiu** [comment]
Tested in QA, working as expected!

**Comment by hknahal** [comment]
Tested in QA using `APGI-AU`. Signed-off on `Treatment` and `Surgery` clinical submission. The `Submitted Data` view for the `Treatment` table no longer shows the appended `Surgery` fields.
