### ISSUE TITLE
🐛 No error reported for missing required `percent_tumour_cells_measurement_method` field after migration to Dict 1.17

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-clinical#972]
## Describe the bug
A new required field called `percent_tumour_cells_measurement_method` field was added to Dictionary version 1.17. But after migrating to the new dictionary, no error is reported in the `Submitted Data` view in `Specimen` table when new required `percent_tumour_cells_measurement_method` field is missing for tumour specimens.

## Steps To Reproduce
- Go to `Specimen` table in `Submitted Data` view for `APGI-AU` program: https://platform.icgc-argo.org/submission/program/APGI-AU/clinical-data?donorId=&tab=specimen
- There is no error reported for the missing required `percent_tumour_cells_measurement_method` field which was added in Dictionary 1.17.
![apgi-au](https://github.com/icgc-argo/argo-clinical/assets/4992044/da2c4fa1-a287-492e-81b1-55782292e954)

## Expected behaviour
Was expecting an alert on the `Specimen` table and error message reporting that the `percent_tumour_cells_measurement_method` field is missing for tumour specimens after migrating to the new Dictionary version 1.17.

**Comment by joneubank** [comment]
The field is not marked as required in the dictionary:
```
        {
          "name": "percent_tumour_cells_measurement_method",
          "description": "Indicate method used to measure percent_tumour_cells.",
          "valueType": "string",
          "meta": {
            "core": true,
            "dependsOn": "sample_registration.tumour_normal_designation",
            "notes": "This field is only required if the specimen is a tumour.",
            "displayName": "Percent Tumour Cells Measurement Method"
          },
          "restrictions": {
            "codeList": [
              "Genomics",
              "Image analysis",
              "Pathology estimate by percent nuclei"
            ]
          }
        },
```
https://lectern.platform.icgc-argo.org/dictionaries/645bef33d6ccc60031fa68dc

**Comment by hknahal** [comment]
The validation check for `percent_tumour_cells_measurement_method` works correctly for **active submissions** (ie. not signed-off)

Example of active submission from `TEST-INTL` project in Prod where Specimen file is missing the `percent_tumour_cells_measurement_method` for a tumour specimen: https://platform.icgc-argo.org/submission/program/TEST-INTL/clinical-submission?tab=specimen

- When the submission is validated (clicked on `Validate Submission` button), it reports an error as expected:

![test-intl](https://github.com/icgc-argo/argo-clinical/assets/4992044/81279c7c-98c0-41ee-b3cc-8a4daf35f364)

**Comment by Buwujiu** [comment]
Regarding percent_tumour_cells_measurement_method not being validated during migration, could it be because it was not set as a required field? Clinical doesn't validate non-core during validation?
