### ISSUE TITLE
🐛 Errors in Submitted Data view persist after clinical data corrections are signed-off

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-clinical#985]
## Describe the bug
The `Submitted Data` view is not updated after the clinical file with errors is re-uploaded, validated with corrected data and signed-off on. The error message box at the top continues to persist, even though the table view shows the updated corrected data.

@hknahal to reproduce it in QA.

## Steps To Reproduce
1. Before corrections, the PTC-SA program was showing errors in the Submitted Data view for the "Primary Diagnosis" and "Treatment" tables. Specifically, the `response_to_treatment_criteria_method` field was missing, and some of the `response_to_treatment` terms needed to be updated (eg. change "NED" to "No evidence of disease (NED) and change "Disease progression" to "Progressive disease").
2. Correct Treatment file was uploaded, validated and signed-off on.
3. But the PTC-SA Submitted Data Treatment view error reporting persists, even though the table shows the updated clinical data: https://platform.icgc-argo.org/submission/program/PTC-SA/clinical-data?donorId=&tab=treatment

**Submitted Data errors:**
![ptc-sa_submitted_data_persisting_error](https://github.com/icgc-argo/argo-clinical/assets/4992044/26e7099e-ea6c-433a-a409-8d72bac9d447)

**Actual updated Treatment data:**
Scrolling through each page fails to show highlighted errors.
![updated_ptc-sa_treatment_data](https://github.com/icgc-argo/argo-clinical/assets/4992044/5db87c28-a66f-446a-b04c-a0924261a4e3)
 

## Expected behaviour
Expected errors in the `Treatment` table to clear in the Submitted Data view after correct clinical data was uploaded, validated and signed-off on.

**Comment by hknahal** [comment]
Another example of error in APGI-AU program:
- Data submitter corrected the Primary Diagnosis table based on errors reported in `Submitted Data` view. She submitted the required `'lymph_nodes_examined_method` field when `lymph_nodes_examined_status` = `Yes`.
- However, the `Submitted Data` view still reports an error even though the entry has been updated:
![apgi-au_submitted_data_error](https://github.com/icgc-argo/argo-clinical/assets/4992044/755beb37-3689-4efa-a3d4-62dd17d9075e)

**Comment by hknahal** [comment]
@Buwujiu This was the ticket we tested in QA for the same issue: https://github.com/icgc-argo/platform-ui/issues/2551

**Comment by Buwujiu** [comment]
Found a similar issue in APGI-AU in Prod: https://platform.icgc-argo.org/submission/program/APGI-AU/clinical-data?donorId=&tab=primary_diagnosis
<img width="1455" alt="Screenshot 2023-05-31 at 2 28 21 PM" src="https://github.com/icgc-argo/argo-clinical/assets/8744047/be863424-8914-4777-935d-afd91db1d1bd">

**Comment by hknahal** [comment]
Tested in TEST-INTL on prod

Before corrections: Shows errors in Primary Diagnosis table where 3 donors are missing `lymph_nodes_examined_method` field:
![test-intl_submitted_data_errors_pd](https://github.com/icgc-argo/argo-clinical/assets/4992044/401bf6d5-055c-48ef-9b5d-7882e254d1ee)


Corrections made to Primary Diagnosis table (submitted missing `lymph_nodes_examined_method` for 3 donors):
![test-intl_pd_corrected](https://github.com/icgc-argo/argo-clinical/assets/4992044/a2826b61-28ee-4fec-b9db-110976700029)


After signing off on corrected/validated Primary Diagnosis data:
- Error box no longer appears after corrections are validated/signed-off on
![test-intl_pd-corrected_submitted_data_view](https://github.com/icgc-argo/argo-clinical/assets/4992044/789085cb-3910-4dac-8e69-a3282354731c)

**Comment by hknahal** [comment]
Tested in QA using `PTC-SA` program. Was able to submit corrected Treatment file and no longer see the errors in the Submitted Data view.
