### ISSUE TITLE
🐛 Program Exception for `treatment_setting` = `Not applicable` not validated

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-clinical#996]
## Describe the bug
Program exception for `treatment_setting` = `Not applicable` is not accepted by clinical submission system in Staging. But other applied program exceptions such as those applied to the specimen schema are accepted by the clinical submission system.

## Steps To Reproduce
**Example 1: Applied program exception for `tumour_grading_system` = `Not applicable` and `tumour_grade` = `Not applicable` and `percent_tumour_cells_measurement_method` = `Unknown` in specimen schema work:** 

1. Upload [APGI-AU_specimen_programException.csv](https://github.com/icgc-argo/argo-clinical/files/11579597/APGI-AU_specimen_programException.csv) file to `allow tumour_grading_system` = `Not applicable` and `tumour_grade` = `Not applicable` and `percent_tumour_cells_measurement_method` = `Unknown`.
2. Confirm program exception:
```
{
  "success": true,
  "exception": {
    "_id": "6470f744b1f9ed9a512b6515",
    "programId": "APGI-AU",
    "exceptions": [
      {
        "_id": "64710e52614bcb0008e01578",
        "program_name": "APGI-AU",
        "schema": "specimen",
        "requested_core_field": "percent_tumour_cells_measurement_method",
        "requested_exception_value": "Unknown"
      },
      {
        "_id": "64710e52614bcb0008e01579",
        "program_name": "APGI-AU",
        "schema": "specimen",
        "requested_core_field": "tumour_grading_system",
        "requested_exception_value": "Not applicable"
      },
      {
        "_id": "64710e52614bcb0008e0157a",
        "program_name": "APGI-AU",
        "schema": "specimen",
        "requested_core_field": "tumour_grade",
        "requested_exception_value": "Not applicable"
      }
    ],
    "__v": 0
  }
}
```
3. Upload test clinical submission files where `tumour_grading_system` = `Not applicable` and `tumour_grade` = `Not applicable` and `percent_tumour_cells_measurement_method` = `Unknown` in the specimen.tsv file. (NOTE: Rename files to *.tsv):
[donor.txt](https://github.com/icgc-argo/argo-clinical/files/11579601/donor.txt)
[specimen_tumour_grade_na.txt](https://github.com/icgc-argo/argo-clinical/files/11579603/specimen_tumour_grade_na.txt)
[primary_diagnosis.txt](https://github.com/icgc-argo/argo-clinical/files/11579602/primary_diagnosis.txt)

Validation accepts applied program exception
![apgi-au_specimen_ProgExcep_pass](https://github.com/icgc-argo/argo-clinical/assets/4992044/f4a534c3-8501-4820-b51f-b8f9229c0709)

**Example 2: Applied program exception for `treatment_setting` = `Not applicable` in treatment schema fails**
1. Upload [APGI-AU_treatment_programException.csv](https://github.com/icgc-argo/argo-clinical/files/11579642/APGI-AU_treatment_programException.csv)   to allow `treatment_setting` = `Not applicable`.

2. Confirm program exception for APGI-AU:
```
{
  "success": true,
  "exception": {
    "_id": "6470f744b1f9ed9a512b6515",
    "programId": "APGI-AU",
    "exceptions": [
      {
        "_id": "6471110e0a9f630008663db9",
        "program_name": "APGI-AU",
        "schema": "specimen",
        "requested_core_field": "percent_tumour_cells_measurement_method",
        "requested_exception_value": "Unknown"
      },
      {
        "_id": "6471110e0a9f630008663dba",
        "program_name": "APGI-AU",
        "schema": "specimen",
        "requested_core_field": "tumour_grading_system",
        "requested_exception_value": "Not applicable"
      },
      {
        "_id": "6471110e0a9f630008663dbb",
        "program_name": "APGI-AU",
        "schema": "specimen",
        "requested_core_field": "tumour_grade",
        "requested_exception_value": "Not applicable"
      },
      {
        "_id": "6471110e0a9f630008663dbc",
        "program_name": "APGI-AU",
        "schema": "treatment",
        "requested_core_field": "treatment_setting",
        "requested_exception_value": "Not applicable"
      }
    ],
    "__v": 0
  }
}
```
2. Upload test clinical submission files (NOTE: Rename files to *.tsv)
[donor.txt](https://github.com/icgc-argo/argo-clinical/files/11579656/donor.txt)
[specimen_tumour_grade_na.txt](https://github.com/icgc-argo/argo-clinical/files/11579658/specimen_tumour_grade_na.txt)
[primary_diagnosis.txt](https://github.com/icgc-argo/argo-clinical/files/11579657/primary_diagnosis.txt)
[treatment.txt](https://github.com/icgc-argo/argo-clinical/files/11579660/treatment.txt)
[surgery.txt](https://github.com/icgc-argo/argo-clinical/files/11579659/surgery.txt)

Clinical validation fails and won't accept `treatment_setting` = `Not applicable`:

![apgi-au_treatment_setting_progExcep_fail](https://github.com/icgc-argo/argo-clinical/assets/4992044/d6d878cb-af8e-4611-bfc9-991318ee1947)

## Expected behaviour
Expect validation to pass when `treatment_setting` = `Not applicable` program exception is applied.

**Comment by hknahal** [comment]
Tested some other core fields in primary_diagnosis, treatment and chemotherapy schemas (in QA):

1. Uploaded [TEST-CA_program_exceptions.csv](https://github.com/icgc-argo/argo-clinical/files/11580028/TEST-CA_program_exceptions.csv) file to https://clinical.qa.argo.cancercollaboratory.org/api-docs/#/Exception/post_exception__programId_
2. Confirm applied program exceptions for TEST-CA using GET endpoint:
```
{
  "success": true,
  "exception": {
    "_id": "6470fc6078867b9d9a54bd1b",
    "programId": "TEST-CA",
    "exceptions": [
      {
        "_id": "64711d1311cf1400098c5b46",
        "program_name": "TEST-CA",
        "schema": "specimen",
        "requested_core_field": "pathological_tumour_staging_system",
        "requested_exception_value": "Not applicable"
      },
      {
        "_id": "64711d1311cf1400098c5b47",
        "program_name": "TEST-CA",
        "schema": "specimen",
        "requested_core_field": "pathological_stage_group",
        "requested_exception_value": "Not applicable"
      },
      {
        "_id": "64711d1311cf1400098c5b48",
        "program_name": "TEST-CA",
        "schema": "specimen",
        "requested_core_field": "tumour_grading_system",
        "requested_exception_value": "Not applicable"
      },
      {
        "_id": "64711d1311cf1400098c5b49",
        "program_name": "TEST-CA",
        "schema": "specimen",
        "requested_core_field": "tumour_grade",
        "requested_exception_value": "Not applicable"
      },
      {
        "_id": "64711d1311cf1400098c5b4a",
        "program_name": "TEST-CA",
        "schema": "specimen",
        "requested_core_field": "percent_tumour_cells_measurement_method",
        "requested_exception_value": "Unknown"
      },
      {
        "_id": "64711d1311cf1400098c5b4b",
        "program_name": "TEST-CA",
        "schema": "primary_diagnosis",
        "requested_core_field": "lymph_nodes_examined_status",
        "requested_exception_value": "Unknown"
      },
      {
        "_id": "64711d1311cf1400098c5b4c",
        "program_name": "TEST-CA",
        "schema": "primary_diagnosis",
        "requested_core_field": "lymph_nodes_examined_method",
        "requested_exception_value": "Unknown"
      },
      {
        "_id": "64711d1311cf1400098c5b4d",
        "program_name": "TEST-CA",
        "schema": "primary_diagnosis",
        "requested_core_field": "clinical_tumour_staging_system",
        "requested_exception_value": "Unknown"
      },
      {
        "_id": "64711d1311cf1400098c5b4e",
        "program_name": "TEST-CA",
        "schema": "primary_diagnosis",
        "requested_core_field": "clinical_stage_group",
        "requested_exception_value": "Unknown"
      },
      {
        "_id": "64711d1311cf1400098c5b4f",
        "program_name": "TEST-CA",
        "schema": "treatment",
        "requested_core_field": "is_primary_treatment",
        "requested_exception_value": "Unknown"
      },
      {
        "_id": "64711d1311cf1400098c5b50",
        "program_name": "TEST-CA",
        "schema": "treatment",
        "requested_core_field": "treatment_intent",
        "requested_exception_value": "Unknown"
      },
      {
        "_id": "64711d1311cf1400098c5b51",
        "program_name": "TEST-CA",
        "schema": "treatment",
        "requested_core_field": "treatment_setting",
        "requested_exception_value": "Not applicable"
      },
      {
        "_id": "64711d1311cf1400098c5b52",
        "program_name": "TEST-CA",
        "schema": "chemotherapy",
        "requested_core_field": "chemotherapy_drug_dose_units",
        "requested_exception_value": "Unknown"
      }
    ],
    "__v": 0
  }
}
```

3. Submitted test clinical submission files to TEST-CA in QA:
[donor.txt](https://github.com/icgc-argo/argo-clinical/files/11580053/donor.txt)
[specimen.txt](https://github.com/icgc-argo/argo-clinical/files/11580057/specimen.txt)
[primary_diagnosis.txt](https://github.com/icgc-argo/argo-clinical/files/11580055/primary_diagnosis.txt)
[treatment.txt](https://github.com/icgc-argo/argo-clinical/files/11580058/treatment.txt)
[chemotherapy.txt](https://github.com/icgc-argo/argo-clinical/files/11580052/chemotherapy.txt)
[radiation.txt](https://github.com/icgc-argo/argo-clinical/files/11580056/radiation.txt)
[follow_up.txt](https://github.com/icgc-argo/argo-clinical/files/11580054/follow_up.txt)

Validation fails for the following fields in the primary_diagnosis, treatment and chemotherapy schemas that had applied program exceptions:
![test-ca_pd](https://github.com/icgc-argo/argo-clinical/assets/4992044/29c18178-024d-4202-bdf9-5f74f2451897)
![TEST-CA_trt](https://github.com/icgc-argo/argo-clinical/assets/4992044/e4621363-6da3-4f32-aef0-4f1d364980c4)
![TEST-CA_chemo](https://github.com/icgc-argo/argo-clinical/assets/4992044/b91c7d40-cd2d-496f-b4ba-378362075549)

Summary:

|program_name|	schema	|requested_core_field|	requested_exception_value|Result|
|--|--|--|--|--|
|TEST-CA	|specimen	|pathological_tumour_staging_system	|Not applicable|passes|
|TEST-CA	|specimen	|pathological_stage_group	|Not applicable|passes|
|TEST-CA	|specimen	|tumour_grading_system	|Not applicable|passes|
|TEST-CA	|specimen	|tumour_grade	|Not applicable|passes|
|TEST-CA	|specimen	|percent_tumour_cells_measurement_method	|Unknown|passes|
|TEST-CA	|primary_diagnosis	|lymph_nodes_examined_status	|Unknown|fails|
|TEST-CA	|primary_diagnosis	|lymph_nodes_examined_method	|Unknown|fails|fails|
|TEST-CA	|primary_diagnosis	|clinical_tumour_staging_system	|Unknown|fails|
|TEST-CA	|primary_diagnosis	|clinical_stage_group	|Unknown|fails|
|TEST-CA	|treatment	|is_primary_treatment	|Unknown|fails|
|TEST-CA	|treatment	|treatment_intent	|Unknown|fails|
|TEST-CA	|treatment	|treatment_setting	|Not applicable|fails|
|TEST-CA	|chemotherapy	|chemotherapy_drug_dose_units	|Unknown|fails|

**Comment by ciaranschutte** [comment]
@Buwujiu I was wrong. Both program and entity exceptions are constrained to `follow_up` and `specimen` right now. 

On adding `treatment` to allowed schemas this works as expected.

**Comment by joneubank** [comment]
@Buwujiu please confirm the requirement: We need to make program work for all schemas, not limited like entities.

**Comment by joneubank** [comment]
https://github.com/icgc-argo/argo-clinical/pull/998

**Comment by hknahal** [comment]
Tests in Staging:

**Test 1: Test some core fields in primary_diagnosis, treatment and chemotherapy schemas:**

1. Uploaded program exceptions file [TEST-CA_program_exceptions.csv](https://github.com/icgc-argo/argo-clinical/files/11680949/TEST-CA_program_exceptions.csv) for TEST-CA program
2. Used GET endpoint to confirm program exceptions for TEST-CA:
```
{
  "success": true,
  "exception": {
    "_id": "6480ae1eb1f9ed9a5153c3db",
    "programId": "TEST-CA",
    "exceptions": [
      {
        "_id": "6480ae1ed65c9e00081a53bf",
        "program_name": "TEST-CA",
        "schema": "specimen",
        "requested_core_field": "pathological_tumour_staging_system",
        "requested_exception_value": "Not applicable"
      },
      {
        "_id": "6480ae1ed65c9e00081a53c0",
        "program_name": "TEST-CA",
        "schema": "specimen",
        "requested_core_field": "pathological_stage_group",
        "requested_exception_value": "Not applicable"
      },
      {
        "_id": "6480ae1ed65c9e00081a53c1",
        "program_name": "TEST-CA",
        "schema": "specimen",
        "requested_core_field": "tumour_grading_system",
        "requested_exception_value": "Not applicable"
      },
      {
        "_id": "6480ae1ed65c9e00081a53c2",
        "program_name": "TEST-CA",
        "schema": "specimen",
        "requested_core_field": "tumour_grade",
        "requested_exception_value": "Not applicable"
      },
      {
        "_id": "6480ae1ed65c9e00081a53c3",
        "program_name": "TEST-CA",
        "schema": "specimen",
        "requested_core_field": "percent_tumour_cells_measurement_method",
        "requested_exception_value": "Unknown"
      },
      {
        "_id": "6480ae1ed65c9e00081a53c4",
        "program_name": "TEST-CA",
        "schema": "primary_diagnosis",
        "requested_core_field": "lymph_nodes_examined_status",
        "requested_exception_value": "Unknown"
      },
      {
        "_id": "6480ae1ed65c9e00081a53c5",
        "program_name": "TEST-CA",
        "schema": "primary_diagnosis",
        "requested_core_field": "lymph_nodes_examined_method",
        "requested_exception_value": "Unknown"
      },
      {
        "_id": "6480ae1ed65c9e00081a53c6",
        "program_name": "TEST-CA",
        "schema": "primary_diagnosis",
        "requested_core_field": "clinical_tumour_staging_system",
        "requested_exception_value": "Unknown"
      },
      {
        "_id": "6480ae1ed65c9e00081a53c7",
        "program_name": "TEST-CA",
        "schema": "primary_diagnosis",
        "requested_core_field": "clinical_stage_group",
        "requested_exception_value": "Unknown"
      },
      {
        "_id": "6480ae1ed65c9e00081a53c8",
        "program_name": "TEST-CA",
        "schema": "treatment",
        "requested_core_field": "is_primary_treatment",
        "requested_exception_value": "Unknown"
      },
      {
        "_id": "6480ae1ed65c9e00081a53c9",
        "program_name": "TEST-CA",
        "schema": "treatment",
        "requested_core_field": "treatment_intent",
        "requested_exception_value": "Unknown"
      },
      {
        "_id": "6480ae1ed65c9e00081a53ca",
        "program_name": "TEST-CA",
        "schema": "treatment",
        "requested_core_field": "treatment_setting",
        "requested_exception_value": "Not applicable"
      },
      {
        "_id": "6480ae1ed65c9e00081a53cb",
        "program_name": "TEST-CA",
        "schema": "chemotherapy",
        "requested_core_field": "chemotherapy_drug_dose_units",
        "requested_exception_value": "Unknown"
      }
    ],
    "__v": 0
  }
}
```

3. Upload test clinical submission files with exceptions:
[sample_registration.txt](https://github.com/icgc-argo/argo-clinical/files/11681014/sample_registration.txt)
[donor.txt](https://github.com/icgc-argo/argo-clinical/files/11681002/donor.txt)
[specimen.txt](https://github.com/icgc-argo/argo-clinical/files/11681006/specimen.txt)
[primary_diagnosis.txt](https://github.com/icgc-argo/argo-clinical/files/11681004/primary_diagnosis.txt)
[treatment.txt](https://github.com/icgc-argo/argo-clinical/files/11681007/treatment.txt)
[chemotherapy.txt](https://github.com/icgc-argo/argo-clinical/files/11681001/chemotherapy.txt)
[radiation.txt](https://github.com/icgc-argo/argo-clinical/files/11681005/radiation.txt)
[follow_up.txt](https://github.com/icgc-argo/argo-clinical/files/11681003/follow_up.txt)

4. All exception values passed validation:

Primary Diagnosis schema:

Validation passed for `lymph_nodes_examined_status` = `Unknown` and `lymph_nodes_examined_method` = `Unknown`:

![pd](https://github.com/icgc-argo/argo-clinical/assets/4992044/a4587223-e0df-459b-91d0-be63af88b37b)

Validation passed for `clinical_tumour_staging_system` = `Unknown` and `clinical_tumour_stage` = `Unknown`:
![pd-1](https://github.com/icgc-argo/argo-clinical/assets/4992044/9182de1f-a194-42f3-8bc4-543275c663ae)

Specimen schema:
Validation passed for `pathological_tumour_staging_system` = `Unknown` and `pathological_tumour_stage` = `Unknown`:
![specimen](https://github.com/icgc-argo/argo-clinical/assets/4992044/705b95c5-5e77-4792-843f-da7714ac1232)

Treatment schema:
Validation passed for `is_primary_treatment` = `Unknown`, `treatment_intent` = `Unknown` and `treatment_setting` = `Not applicable`:
![treatment](https://github.com/icgc-argo/argo-clinical/assets/4992044/75b74300-9036-4ee7-8d14-5ab530744dcf)

Chemotherapy schema:
Validation passed for `chemotherapy_drug_dose_units` = `Unknown`:
![chemotherapy](https://github.com/icgc-argo/argo-clinical/assets/4992044/b84c3fd1-6931-4f0f-b582-2f7c2d365446)

**Comment by hknahal** [comment]
Test 2: Submit an exception value that is not one of the exception values registered.

Example: We registered `lymph_nodes_examined_method` = `Unknown` as a program exception. Tried submitting `lymph_nodes_examined_method` = `Not applicable`. This failed validation as expected.

![pd_error](https://github.com/icgc-argo/argo-clinical/assets/4992044/ecc2b9aa-2fa9-43b6-9304-1736194a372c)

Test 3:

**Comment by hknahal** [comment]
Testing of program exceptions on core fields in other schema pass validation in Staging

**Comment by hknahal** [comment]
Testing program exceptions for APGI-AU data in PROD:

Test case 1: Testing program exceptions for just one schema (treatment):

1. Use`TEST-INTL` project to test APGI-AU program-level exceptions.
2. Uploaded [sample_registration.txt](https://github.com/icgc-argo/argo-clinical/files/11727089/sample_registration.txt) file to register same samples as APGI-AU, but in TEST-INTL.
3. Uploaded program-level exception ([TEST-CA_prod_test-APGI-AU_program_exceptions.csv](https://github.com/icgc-argo/argo-clinical/files/11727170/TEST-CA_prod_test-APGI-AU_program_exceptions.csv)) for `treatment_setting` = `Not applicable`. Output from GET endpoint confirm this program exception: 

```
{
  "success": true,
  "exception": {
    "_id": "64874c4a25fec125ea2a51a6",
    "programId": "TEST-INTL",
    "exceptions": [
      {
        "_id": "64874c4ac741d100095bc2f2",
        "program_name": "TEST-INTL",
        "schema": "treatment",
        "requested_core_field": "treatment_setting",
        "requested_exception_value": "Not applicable"
      }
    ],
    "__v": 0
  }
}
```
4. Uploaded APGI-AU clinical submission files (changed `program_name` from `APGI-AU` to `TEST-INTL`):
[donor.txt](https://github.com/icgc-argo/argo-clinical/files/11727121/donor.txt)
[primary_diagnosis.txt](https://github.com/icgc-argo/argo-clinical/files/11727123/primary_diagnosis.txt)
[treatment.txt](https://github.com/icgc-argo/argo-clinical/files/11727126/treatment.txt)
[surgery.txt](https://github.com/icgc-argo/argo-clinical/files/11727125/surgery.txt)
[follow_up.txt](https://github.com/icgc-argo/argo-clinical/files/11727122/follow_up.txt)

5. Validate submission with `treatment_setting` = `Not applicable` in Treatment schema. This validates as expected:
![treatment_program-level_trt_setting_valid](https://github.com/icgc-argo/argo-clinical/assets/4992044/a9de92e3-daac-4479-8d64-964d6f9f5d91)

**Comment by Buwujiu** [comment]
All test cases passed, closing.
